// Knowledge base — short, evidence-based coping articles.
// Sources: Marlatt RP, CDC, Cochrane reviews, USPSTF, Surgeon General 2020,
// Brewer "Craving to Quit", Taylor 2007 (exercise & craving), West 2017 (stress).

import { Image } from 'react-native';
import type { IconKey } from '../components/Icon';

export type ArticleCategory = 'craving' | 'slip' | 'triggers' | 'body' | 'meds' | 'motivation';

// A body block: 'h' is a section subheading, 'p' is a paragraph.
export type ArticleBlock = { type: 'h' | 'p'; text: string };

export type Article = {
  id: string;
  category: ArticleCategory;
  icon: IconKey;
  color: string;
  readMin: number;
  titleRu: string; titleEn: string;
  leadRu: string;  leadEn: string;
  bodyRu: ArticleBlock[]; bodyEn: ArticleBlock[];
  takeawayRu: string; takeawayEn: string;
};

export const ARTICLE_CATEGORY: Record<ArticleCategory, { ru: string; en: string; icon: IconKey; color: string }> = {
  craving:    { ru: 'Тяга',        en: 'Cravings',   icon: 'flame',   color: '#FF9500' },
  slip:       { ru: 'Срыв',        en: 'Slips',      icon: 'feather', color: '#5AC8FA' },
  triggers:   { ru: 'Триггеры',    en: 'Triggers',   icon: 'bolt',    color: '#BF5AF2' },
  body:       { ru: 'Тело',        en: 'Your body',  icon: 'heart',   color: '#FF453A' },
  meds:       { ru: 'Лекарства',   en: 'Medication', icon: 'shield',  color: '#30D158' },
  motivation: { ru: 'Мотивация',   en: 'Motivation', icon: 'sparkle', color: '#34C759' },
};

export const ARTICLES: Article[] = [
  {
    id: 'craving-wave', category: 'craving', icon: 'wave2', color: '#FF9500', readMin: 5,
    titleRu: 'Тяга — это волна', titleEn: 'A craving is a wave',
    leadRu: 'Почему тяга всегда проходит сама, если её не кормить.',
    leadEn: 'Why a craving always passes on its own if you do not feed it.',
    bodyRu: [
      { type: 'h', text: 'Тяга притворяется бесконечной' },
      { type: 'p', text: 'Представь: ты на работе, конец тяжёлого дня, и вдруг накрывает — «надо закурить, прямо сейчас». Кажется, что это чувство будет только расти, давить всё сильнее, пока ты не сдашься. Именно так тяга и обманывает: она прикидывается бесконечной. Но это иллюзия.' },
      { type: 'p', text: 'На самом деле тяга устроена как волна. Она поднимается, доходит до пика — и спадает. Сама. Без твоего участия. Обычно весь цикл занимает 3–5 минут. Не час, не «весь вечер» — несколько минут. Пик, который сейчас кажется невыносимым, длится секунды.' },
      { type: 'p', text: 'Это не метафора для красоты, а буквальное описание того, как работает желание в мозге. У любого импульса есть начало, вершина и хвост. Тяга не умеет держаться на пике — у неё просто нет такого механизма. Она обязана пойти на спад, вопрос только в том, дашь ли ты ей это сделать.' },
      { type: 'h', text: 'Почему сигарета будто «помогает»' },
      { type: 'p', text: 'Тут и кроется ловушка. Ты закуриваешь как раз тогда, когда волна и без того пошла на спад — и мозг делает ложный вывод: «вот что меня спасло». Но если бы ты не закурил, волна спала бы ровно так же. Просто без новой дозы никотина, без подкормки зависимости, без отката завтра.' },
      { type: 'p', text: 'Каждый раз курильщик «доказывает» себе, что без сигареты тягу не пережить. И каждый раз ошибается — он просто не дал волне доиграть до конца. А зря: именно прожитая до конца волна и есть лекарство.' },
      { type: 'h', text: 'Каждая волна ослабляет следующую' },
      { type: 'p', text: 'Дело в том, что каждая пережитая волна ослабляет следующую. Ты буквально переучиваешь мозг: оказывается, тягу можно пережить, и ничего страшного не случится. Это не сила воли — это новый навык, и он накапливается.' },
      { type: 'p', text: 'Через 2–4 недели волны становятся короче, приходят реже и бьют слабее. Первые дни они могут накатывать по десять раз в день — потом раз в день, потом раз в неделю, потом ты вдруг замечаешь, что не вспоминал о сигарете уже давно. Это не магия и не везение, это прямое следствие того, что ты раз за разом не кормил зависимость.' },
      { type: 'h', text: 'Что делать, когда накрыло' },
      { type: 'p', text: 'Не бороться и не уговаривать себя — это только раскручивает. Наоборот, стань наблюдателем. Где именно ощущение в теле — в груди, в горле, в руках? Какое оно — жжёт, давит, крутит, зудит? Назови его про себя, спокойно, как будто описываешь погоду.' },
      { type: 'p', text: 'Потом — несколько длинных, медленных выдохов. Не вдохов, а именно выдохов: они переключают нервную систему в спокойный режим. И просто наблюдай, как волна растёт и опадает, словно ты сёрфер, который не дерётся с волной, а скользит по ней.' },
      { type: 'p', text: 'Эта техника так и называется — «скольжение по тяге», urge surfing. Ты не подавляешь желание и не выполняешь его. Ты его пережидаешь. И с каждым разом это получается всё легче, потому что ты уже знаешь концовку: волна спадёт, а ты останешься некурящим.' },
    ],
    bodyEn: [
      { type: 'h', text: 'A craving pretends to be endless' },
      { type: 'p', text: 'Picture this: you are at work, the end of a brutal day, and suddenly it hits — "I need to smoke, right now." It feels like this feeling will only grow, press harder and harder until you give in. That is exactly how a craving fools you: it pretends to be endless. But it is an illusion.' },
      { type: 'p', text: 'In reality a craving works like a wave. It rises, reaches a peak — and falls. On its own. Without your help. The whole cycle usually takes 3–5 minutes. Not an hour, not "the whole evening" — a few minutes. The peak that feels unbearable right now lasts seconds.' },
      { type: 'p', text: 'This is not a pretty metaphor but a literal description of how desire works in the brain. Every impulse has a beginning, a peak and a tail. A craving cannot hold at the peak — it simply has no mechanism for that. It is bound to come down; the only question is whether you let it.' },
      { type: 'h', text: 'Why a cigarette seems to "help"' },
      { type: 'p', text: 'That is where the trap is. You light up exactly when the wave is already on its way down — and the brain draws a false conclusion: "that is what saved me." But if you had not smoked, the wave would have fallen just the same. Only without a new dose of nicotine, without feeding the dependence, without the rebound tomorrow.' },
      { type: 'p', text: 'Every time, a smoker "proves" to themselves that a craving cannot be survived without a cigarette. And every time, they are wrong — they simply never let the wave play out to the end. A shame, because a wave ridden all the way through is the actual cure.' },
      { type: 'h', text: 'Every wave weakens the next one' },
      { type: 'p', text: 'The thing is, every wave you ride weakens the next one. You are literally retraining the brain: it turns out a craving can be survived, and nothing terrible happens. This is not willpower — it is a new skill, and it accumulates.' },
      { type: 'p', text: 'Within 2–4 weeks waves get shorter, come less often and hit weaker. In the first days they may roll in ten times a day — then once a day, then once a week, then you suddenly notice you have not thought about a cigarette in a long while. That is not magic or luck, it is the direct result of you not feeding the dependence, time after time.' },
      { type: 'h', text: 'What to do when it hits' },
      { type: 'p', text: 'Do not fight or argue with yourself — that only winds it up. Instead, become an observer. Where exactly is the sensation in the body — chest, throat, hands? What is it like — burning, pressing, twisting, itching? Name it silently, calmly, as if describing the weather.' },
      { type: 'p', text: 'Then take a few long, slow exhales. Not inhales — exhales: they switch the nervous system into a calm mode. And just watch the wave grow and fade, like a surfer who does not fight the wave but glides over it.' },
      { type: 'p', text: 'This technique is called urge surfing. You are not suppressing the urge and not obeying it. You are riding it out. And each time it gets easier, because you already know the ending: the wave will fall, and you will still be a non-smoker.' },
    ],
    takeawayRu: 'Тяга длится 3–5 минут и проходит сама. Твоя задача — не закурить, а переждать волну.',
    takeawayEn: 'A craving lasts 3–5 minutes and passes by itself. Your job is not to smoke — just to ride the wave.',
  },
  {
    id: 'craving-now', category: 'craving', icon: 'bolt', color: '#FF9500', readMin: 4,
    titleRu: 'Тянет прямо сейчас — что сделать', titleEn: 'Craving right now — what to do',
    leadRu: 'Короткий план на ближайшие 5 минут.',
    leadEn: 'A short plan for the next 5 minutes.',
    bodyRu: [
      { type: 'h', text: 'Ты уже сделал первый шаг' },
      { type: 'p', text: 'Если ты открыл эту статью прямо сейчас, потому что тянет, — хорошо, что открыл. Это уже выигранные тридцать секунд. А тяга, как ты помнишь, живёт всего 3–5 минут. Дальше — простой план, который их закроет.' },
      { type: 'p', text: 'Не нужно делать всё сразу и идеально. Достаточно начать с первого пункта — а пока ты его делаешь, волна уже пойдёт на спад. План работает не потому, что он хитрый, а потому что он занимает тебя ровно на те минуты, что длится пик.' },
      { type: 'h', text: 'Засеки 5 минут — и только их' },
      { type: 'p', text: 'Прямо сейчас скажи себе: «я не курю ближайшие 5 минут». Не «никогда», не «всю оставшуюся жизнь» — это слишком огромно, мозг такое не берёт. Только 5 минут. Вот это посильно. С такой задачей справится кто угодно.' },
      { type: 'p', text: 'Это не самообман, а рабочий приём. Бросать «навсегда» страшно, а не курить пять минут — совсем не страшно. А вся жизнь без сигарет как раз и состоит из таких отрезков по пять минут, прожитых один за другим.' },
      { type: 'h', text: 'Дыши и смени обстановку' },
      { type: 'p', text: 'Дыши. Звучит банально, но это работает на уровне физиологии: длинный выдох, вдвое длиннее вдоха, переключает нервную систему в спокойный режим примерно за минуту. Открой в приложении дыхательную практику или просто сделай 10 медленных выдохов, считая про себя. Вдох на 4 — выдох на 8.' },
      { type: 'p', text: 'Смени обстановку. Тяга крепко привязана к месту и позе: тот самый стул, то самое окно, тот самый угол у подъезда. Разорви связку — встань, выйди из комнаты, умой лицо холодной водой, выпей стакан воды залпом. Тело удивится, и тяга на секунду потеряет нить.' },
      { type: 'h', text: 'Займи руки и рот' },
      { type: 'p', text: 'Сигарета — это ведь не только никотин, это ещё и ритуал «рука-рот», который повторялся тысячи раз. Дай этому ритуалу замену: орех, мятную жвачку, кубик льда, эспандер, ручку повертеть. Это не «детский сад» и не несерьёзно — это конкретный способ разорвать привычный жест.' },
      { type: 'p', text: 'А если совсем накрыло — не геройствуй в одиночку. Открой SOS в приложении, отвлекись на быструю игру, напиши кому-нибудь, выйди на короткую прогулку. Подойдёт что угодно, что займёт голову на пару минут.' },
      { type: 'h', text: 'Через 5 минут проверь себя' },
      { type: 'p', text: 'А теперь главное: через 5 минут вернись и проверь себя. Почти наверняка волна уже спала — стала тише, отступила, отпустила. Ты только что прожил тягу и не закурил.' },
      { type: 'p', text: 'Запомни это ощущение: именно так выглядит победа, и она будет повторяться. Каждый такой эпизод — это маленькое доказательство, которое ты собираешь сам себе: «я могу». Чем больше таких доказательств, тем тише становится тяга.' },
    ],
    bodyEn: [
      { type: 'h', text: 'You already took the first step' },
      { type: 'p', text: 'If you opened this article right now because a craving hit — good that you did. That is already thirty seconds won. And a craving, remember, lives only 3–5 minutes. Below is a simple plan to cover them.' },
      { type: 'p', text: 'You do not need to do everything at once and perfectly. It is enough to start with the first point — and while you are doing it, the wave is already on its way down. The plan works not because it is clever, but because it occupies you for exactly the minutes the peak lasts.' },
      { type: 'h', text: 'Start a 5-minute timer — and only that' },
      { type: 'p', text: 'Right now, tell yourself: "I will not smoke for the next 5 minutes." Not "never", not "for the rest of my life" — that is too vast, the brain cannot hold it. Just 5 minutes. That is doable. Anyone can manage that.' },
      { type: 'p', text: 'This is not self-deception but a working technique. Quitting "forever" is scary, while not smoking for five minutes is not scary at all. And a whole life without cigarettes is made up of exactly these five-minute stretches, lived one after another.' },
      { type: 'h', text: 'Breathe and change your setting' },
      { type: 'p', text: 'Breathe. It sounds trivial, but it works on a physiological level: a long exhale, twice as long as the inhale, switches the nervous system into a calm mode in about a minute. Open the breathing practice in the app, or just do 10 slow exhales, counting silently. Inhale for 4 — exhale for 8.' },
      { type: 'p', text: 'Change your setting. A craving is firmly tied to place and posture: that chair, that window, that corner by the door. Break the link — stand up, leave the room, splash cold water on your face, drink a glass of water in one go. The body will be surprised, and the craving loses its thread for a second.' },
      { type: 'h', text: 'Occupy hands and mouth' },
      { type: 'p', text: 'A cigarette is not only nicotine — it is also the hand-to-mouth ritual repeated thousands of times. Give that ritual a substitute: a nut, mint gum, an ice cube, a hand gripper, a pen to fidget with. This is not childish or unserious — it is a concrete way to break the familiar gesture.' },
      { type: 'p', text: 'And if it really overwhelms you — do not tough it out alone. Open SOS in the app, distract yourself with a quick game, text someone, step out for a short walk. Anything that occupies your mind for a couple of minutes will do.' },
      { type: 'h', text: 'After 5 minutes, check yourself' },
      { type: 'p', text: 'And now the main thing: after 5 minutes, come back and check yourself. Almost certainly the wave has passed — gone quieter, receded, let go. You have just lived through a craving without smoking.' },
      { type: 'p', text: 'Remember this feeling: this is what a win looks like, and it will keep happening. Every such episode is a small piece of proof you gather for yourself: "I can do this." The more proof you collect, the quieter the craving becomes.' },
    ],
    takeawayRu: 'Не «бросить навсегда», а «не курить 5 минут». Дыши, двигайся, займи руки — волна спадёт.',
    takeawayEn: 'Not "quit forever" — just "do not smoke for 5 minutes". Breathe, move, occupy your hands.',
  },
  {
    id: 'craving-day3', category: 'craving', icon: 'flame', color: '#FF9500', readMin: 4,
    titleRu: 'Почему 3-й день самый трудный', titleEn: 'Why day 3 is the hardest',
    leadRu: 'И почему это хорошая новость.',
    leadEn: 'And why that is good news.',
    bodyRu: [
      { type: 'h', text: 'Ты не сходишь с ума — ты по графику' },
      { type: 'p', text: 'Если ты на втором или третьем дне без сигарет и тебе кажется, что ты сходишь с ума, — остановись на секунду. Ты не сходишь с ума. Ты ровно по графику. То, что ты сейчас чувствуешь, чувствуют почти все, и этому есть точное объяснение.' },
      { type: 'p', text: 'Когда понимаешь, что твоё состояние — это предсказуемый, описанный этап, а не личная катастрофа, оно сразу становится переносимее. Это не «со мной что-то не так». Это «мой мозг проходит ровно то, что должен пройти».' },
      { type: 'h', text: 'Что происходит на 2–4 день' },
      { type: 'p', text: 'Никотин уходит с рецепторов мозга примерно за 72 часа. Всё это время мозг, привыкший получать дозу каждый час, недоумённо требует своё.' },
      { type: 'p', text: 'Именно поэтому на 2–4 день симптомы отмены достигают пика: раздражительность по пустякам, тревога без причины, рваный сон, сильная тяга, ощущение «не в своей тарелке». Это не твой характер испортился — это химия отмены, и она временная.' },
      { type: 'h', text: 'Пик — это не начало, а вершина' },
      { type: 'p', text: 'И вот тут — главная ловушка момента. Кажется, что раз так плохо уже сейчас, то дальше будет только хуже, и впереди недели такого ада. Это неправда. Всё наоборот.' },
      { type: 'p', text: 'Пик — это не начало подъёма в гору. Пик — это вершина. Поворотная точка. После 3-го дня физическая зависимость резко слабеет, просто потому что никотина в теле уже почти не осталось — нечему больше требовать дозу. Дальше идёт спуск.' },
      { type: 'p', text: 'Подумай об этом так: если ты дошёл до 3-го дня, значит, самое тяжёлое происходит с тобой прямо сейчас, в эту минуту, — а не где-то впереди. Худшее не «надвигается». Худшее ты уже проходишь. И это не повод сдаться — это повод стиснуть зубы ещё на чуть-чуть, потому что обиднее всего сорваться именно на вершине.' },
      { type: 'h', text: 'Как пройти эти дни мягче' },
      { type: 'p', text: 'Чтобы пройти эти дни мягче, помоги телу. Больше сна — отмена выматывает, и это нормально. Меньше кофе и алкоголя — они подстёгивают тягу. Лёгкая физическая нагрузка — даже короткая прогулка сбивает напряжение. Простая еда и побольше воды.' },
      { type: 'p', text: 'Не грузи себя в эти дни сложными задачами, если есть возможность их отложить. Это нормально — пару дней пожить в щадящем режиме. Ты не ленишься, ты проходишь пик отмены, и беречь себя сейчас разумно.' },
      { type: 'h', text: 'Это буря, а не новая норма' },
      { type: 'p', text: 'Запомни: симптомы отмены — это не новая норма, это временная буря. Через неделю их почти не будет.' },
      { type: 'p', text: 'То, что сейчас ощущается как «я так не выдержу», через семь дней станет фразой «а ведь уже почти отпустило». Тебе нужно просто продержаться через вершину — а ты уже на ней.' },
    ],
    bodyEn: [
      { type: 'h', text: 'You are not losing your mind — you are on schedule' },
      { type: 'p', text: 'If you are on day two or three without cigarettes and feel like you are losing your mind — stop for a second. You are not losing your mind. You are exactly on schedule. What you feel right now is felt by almost everyone, and there is a precise explanation for it.' },
      { type: 'p', text: 'When you understand that your state is a predictable, well-described stage rather than a personal catastrophe, it immediately becomes more bearable. It is not "something is wrong with me". It is "my brain is going through exactly what it has to go through".' },
      { type: 'h', text: 'What happens on days 2–4' },
      { type: 'p', text: 'Nicotine clears the brain receptors in about 72 hours. All that time the brain, used to a dose every hour, keeps demanding its share in confusion.' },
      { type: 'p', text: 'That is why on days 2–4 withdrawal symptoms peak: irritability over trifles, anxiety with no cause, broken sleep, strong cravings, a general "off" feeling. It is not your character that has soured — it is the chemistry of withdrawal, and it is temporary.' },
      { type: 'h', text: 'The peak is not the start, it is the summit' },
      { type: 'p', text: 'And here is the main trap of the moment. It feels like, since it is already this bad, it will only get worse, with weeks of this hell ahead. That is not true. The opposite is the case.' },
      { type: 'p', text: 'The peak is not the start of a climb up a mountain. The peak is the summit. The turning point. After day 3 the physical dependence drops sharply, simply because there is almost no nicotine left in the body — nothing left to demand a dose. From here it is the descent.' },
      { type: 'p', text: 'Think of it this way: if you have reached day 3, then the hardest part is happening to you right now, this very minute — not somewhere ahead. The worst is not "approaching". The worst is what you are already going through. And that is not a reason to give up — it is a reason to grit your teeth a little longer, because slipping right at the summit would be the most heartbreaking timing of all.' },
      { type: 'h', text: 'How to get through these days more gently' },
      { type: 'p', text: 'To get through these days more gently, help your body. More sleep — withdrawal is exhausting, and that is normal. Less coffee and alcohol — they fuel cravings. Light exercise — even a short walk knocks down the tension. Simple food and plenty of water.' },
      { type: 'p', text: 'Do not load yourself with hard tasks these days if you can postpone them. It is okay to live in an easy mode for a couple of days. You are not being lazy — you are passing the peak of withdrawal, and protecting yourself now is sensible.' },
      { type: 'h', text: 'It is a storm, not a new normal' },
      { type: 'p', text: 'Remember: withdrawal symptoms are not a new normal, they are a temporary storm. In a week they will be almost gone.' },
      { type: 'p', text: 'What now feels like "I cannot stand this" will, in seven days, become "it has almost let go already". You just need to hold on through the summit — and you are already on it.' },
    ],
    takeawayRu: 'Пик отмены — 2–4 день. Это значит: дальше будет легче, а не тяжелее.',
    takeawayEn: 'Withdrawal peaks on days 2–4. It means it gets easier from here, not harder.',
  },
  {
    id: 'craving-halt', category: 'craving', icon: 'pulse', color: '#FF9500', readMin: 4,
    titleRu: 'HALT: проверь 4 нужды', titleEn: 'HALT: check 4 needs',
    leadRu: 'Часто тебе нужен не никотин, а что-то другое.',
    leadEn: 'Often you need something other than nicotine.',
    bodyRu: [
      { type: 'h', text: 'Тяга редко приходит «на ровном месте»' },
      { type: 'p', text: 'Бывает так: вроде день идёт нормально, и вдруг — резко, сильно — тянет закурить. Будто на ровном месте. Но на ровном месте тяга почти не приходит. Если присмотреться, под ней почти всегда лежит что-то ещё. И есть простой способ это «что-то» поймать.' },
      { type: 'p', text: 'Он называется HALT — по первым буквам четырёх английских слов. Это четыре состояния, в которых тяга резко усиливается: Hungry — голоден, Angry — зол или раздражён, Lonely — одинок, Tired — устал. Зависимость хитрая: она пользуется любой из этих дыр, чтобы протолкнуть мысль о сигарете.' },
      { type: 'h', text: 'Пауза на 10 секунд и четыре вопроса' },
      { type: 'p', text: 'В момент, когда хочется закурить, не хватайся сразу за пачку. Сделай паузу на десять секунд и спокойно пройдись по списку, по очереди: я голоден? я злюсь или чем-то раздражён? мне одиноко? я устал?' },
      { type: 'p', text: 'Очень часто ответ «да» найдётся в одном из четырёх пунктов — и вот она, настоящая причина. Сигарета её просто маскировала. Эта пауза стоит десять секунд, а экономит тебе целую сигарету и откат после неё.' },
      { type: 'h', text: 'Как это выглядит в жизни' },
      { type: 'p', text: 'Ты не обедал с утра, к пяти часам сахар в крови упал — и ты «вдруг» захотел курить. На самом деле ты захотел есть. Или совещание вывело из себя, внутри всё кипит — рука сама тянется к сигарете, потому что курение годами было способом «спустить пар».' },
      { type: 'p', text: 'Или ты весь вечер один в пустой квартире, и накатывает тоскливое «надо бы покурить». Это не никотин зовёт — это одиночество ищет, чем себя занять. Стоит написать другу или выйти к людям, и тяга часто тает на глазах.' },
      { type: 'h', text: 'Сигарета не закрывает ни одну из четырёх нужд' },
      { type: 'p', text: 'И вот что важно понять: ни одну из этих четырёх нужд сигарета на самом деле не закрывает. Голоден — поешь нормально, а не «заешь» голод дымом. Зол — выпусти эмоцию по-настоящему: подвигайся, быстро пройдись, напиши всё, что думаешь, проговори вслух. Одинок — напиши близкому человеку, позвони, не сиди один. Устал — дай себе отдохнуть или поспать, хотя бы двадцать минут.' },
      { type: 'p', text: 'Сигарета не кормит, не успокаивает злость, не лечит одиночество и не даёт отдыха. Она лишь на несколько минут приглушает сигнал тела — а потом сигнал возвращается, и нужда никуда не делась, только добавилась доза никотина.' },
      { type: 'h', text: 'HALT — это рабочая привычка' },
      { type: 'p', text: 'Поэтому HALT — это не просто аббревиатура, это рабочая привычка. Закрой настоящую потребность — поешь, остынь, поговори, отдохни — и обнаружишь, что тяга часто растворяется сама, без всякой борьбы.' },
      { type: 'p', text: 'Ты дал телу то, что ему было нужно на самом деле. Со временем эта проверка становится автоматической: ты ловишь себя на тяге — и почти сразу понимаешь, какая из четырёх дыр под ней открылась.' },
    ],
    bodyEn: [
      { type: 'h', text: 'A craving rarely comes "out of nowhere"' },
      { type: 'p', text: 'It happens like this: the day seems to be going fine, and suddenly — sharply, strongly — you want to smoke. As if out of nowhere. But a craving almost never comes out of nowhere. Look closer, and there is almost always something else underneath it. And there is a simple way to catch that "something".' },
      { type: 'p', text: 'It is called HALT — from the first letters of four words. These are four states in which cravings spike sharply: Hungry, Angry, Lonely, Tired. The dependence is cunning: it uses any of these gaps to push the thought of a cigarette through.' },
      { type: 'h', text: 'A 10-second pause and four questions' },
      { type: 'p', text: 'The moment you want to smoke, do not reach straight for the pack. Pause for ten seconds and calmly run through the list, one by one: am I hungry? am I angry or irritated? am I lonely? am I tired?' },
      { type: 'p', text: 'Very often a "yes" turns up in one of the four — and there it is, the real cause. The cigarette was simply masking it. This pause costs ten seconds and saves you a whole cigarette and the rebound after it.' },
      { type: 'h', text: 'How it looks in life' },
      { type: 'p', text: 'You skipped lunch, by five o’clock your blood sugar dropped — and you "suddenly" wanted to smoke. In fact you wanted to eat. Or a meeting got you worked up, everything is boiling inside — your hand reaches for a cigarette, because smoking was for years your way to "let off steam".' },
      { type: 'p', text: 'Or you have spent the whole evening alone in an empty flat, and a gloomy "I should have a smoke" creeps in. It is not nicotine calling — it is loneliness looking for something to do. Text a friend or go out among people, and the craving often melts before your eyes.' },
      { type: 'h', text: 'A cigarette meets none of the four needs' },
      { type: 'p', text: 'And here is the key thing to grasp: a cigarette does not actually meet any of those four needs. Hungry — eat properly, do not "smother" hunger with smoke. Angry — release the emotion for real: move, walk fast, write down everything you think, say it out loud. Lonely — text someone close, call them, do not sit alone. Tired — let yourself rest or sleep, even twenty minutes.' },
      { type: 'p', text: 'A cigarette does not feed you, does not calm anger, does not cure loneliness and gives no rest. It only mutes the body signal for a few minutes — and then the signal returns, the need is still there, only now with an added dose of nicotine.' },
      { type: 'h', text: 'HALT is a working habit' },
      { type: 'p', text: 'So HALT is not just an acronym, it is a working habit. Meet the real need — eat, cool down, talk, rest — and you will find the craving often dissolves on its own, with no fight at all.' },
      { type: 'p', text: 'You gave the body what it actually needed. Over time this check becomes automatic: you catch yourself in a craving — and almost at once you see which of the four gaps has opened underneath it.' },
    ],
    takeawayRu: 'Голоден, зол, одинок, устал? Закрой настоящую нужду — и тяга часто уходит сама.',
    takeawayEn: 'Hungry, angry, lonely, tired? Meet the real need and the craving often fades on its own.',
  },
  {
    id: 'slip-not-fail', category: 'slip', icon: 'feather', color: '#5AC8FA', readMin: 4,
    titleRu: 'Срыв — это не провал', titleEn: 'A slip is not a failure',
    leadRu: 'Почти все, кто бросил насовсем, срывались по пути.',
    leadEn: 'Almost everyone who quit for good slipped along the way.',
    bodyRu: [
      { type: 'h', text: 'Сначала самое главное' },
      { type: 'p', text: 'Если ты сорвался и читаешь это с тяжёлым чувством — давай сразу, без предисловий: срыв не означает, что «всё пропало». И ты не «всё испортил». Это просто часть процесса, через который проходят почти все.' },
      { type: 'p', text: 'Вот что показывают исследования: большинству людей нужно несколько попыток, прежде чем бросить окончательно. Не одна, идеальная, с первого раза — а несколько. Это не признак слабости и не твоя личная неудача. Это статистика, обычный путь, по которому шли миллионы бросивших.' },
      { type: 'h', text: 'Разница не в том, кто споткнулся' },
      { type: 'p', text: 'Подумай вот о чём. Разница между человеком, который в итоге бросил, и человеком, который вернулся к пачке в день, — вовсе не в том, что первый ни разу не споткнулся. Споткнулись оба. Разница только в том, что они сделали сразу после.' },
      { type: 'p', text: 'Один человек закурил сигарету и сказал себе: «ну всё, я провалился, нет смысла, я слабак» — и эта мысль потянула за собой вторую сигарету, третью, пачку. Другой закурил ровно такую же сигарету и сказал: «окей, это просто данные — где я оступился и почему» — и пошёл дальше. Сигарета у обоих была одна и та же. Разошлись они в реакции.' },
      { type: 'h', text: 'Одна сигарета не обнуляет прогресс' },
      { type: 'p', text: 'И ещё важное, про цифры. Одна сигарета не отменяет, скажем, 14 дней без курения. Твоё тело всё равно очищалось все эти две недели — кровь, лёгкие, сосуды реально восстанавливались. Этого у тебя никто не отнимет.' },
      { type: 'p', text: 'Именно поэтому счётчик в приложении намеренно не обнуляется до нуля от одной сигареты: прогресс действительно есть, и он реальный. Ты не «начинаешь с нуля» — ты продолжаешь с того места, где оступился.' },
      { type: 'h', text: 'Опасна не первая сигарета, а вторая' },
      { type: 'p', text: 'После срыва опасна не первая сигарета — она уже случилась, её не вернёшь. Опасна вторая. Именно она превращает разовый эпизод в возврат к курению.' },
      { type: 'p', text: 'Поэтому всё внимание — не на том, что уже произошло, а на следующем шаге. Первая сигарета — это случайность. Вторая — это уже решение. И вот это решение полностью в твоих руках.' },
      { type: 'h', text: 'Что сделать прямо сейчас' },
      { type: 'p', text: 'Сделай ровно одно: не тяни. Сразу спокойно разбери — что было триггером? что застало врасплох? что в следующий раз попробуешь сделать иначе? — и вернись на путь. Не завтра, не «с понедельника» — сейчас.' },
      { type: 'p', text: 'Чем быстрее вернёшься, тем меньше этот срыв вообще значит. Через месяц он будет просто строчкой в истории, а не концом истории. А разобранный триггер сделает тебя сильнее, чем ты был до срыва.' },
    ],
    bodyEn: [
      { type: 'h', text: 'First, the main thing' },
      { type: 'p', text: 'If you slipped and are reading this with a heavy feeling — let us say it straight, no preamble: a slip does not mean "everything is lost". And you did not "ruin everything". It is simply part of the process almost everyone goes through.' },
      { type: 'p', text: 'Here is what research shows: most people need several attempts before quitting for good. Not one perfect attempt on the first try — several. That is not a sign of weakness or your personal failure. It is statistics, the ordinary path that millions of quitters walked.' },
      { type: 'h', text: 'The difference is not who stumbled' },
      { type: 'p', text: 'Think about this. The difference between someone who eventually quit and someone who went back to a pack a day is not that the first never stumbled. Both stumbled. The difference is only in what they did right afterwards.' },
      { type: 'p', text: 'One person smoked a cigarette and told themselves: "that is it, I failed, no point, I am weak" — and that thought dragged a second cigarette behind it, a third, a pack. The other smoked exactly the same cigarette and said: "okay, this is just data — where did I trip and why" — and carried on. The cigarette was identical for both. They parted ways in the reaction.' },
      { type: 'h', text: 'One cigarette does not zero your progress' },
      { type: 'p', text: 'And another important point, about the numbers. One cigarette does not cancel, say, 14 smoke-free days. Your body still healed across those two weeks — blood, lungs, vessels really did recover. No one can take that from you.' },
      { type: 'p', text: 'That is exactly why the counter in the app deliberately does not reset to zero from a single cigarette: the progress is real. You are not "starting from scratch" — you are continuing from the spot where you tripped.' },
      { type: 'h', text: 'The danger is the second cigarette, not the first' },
      { type: 'p', text: 'After a slip the danger is not the first cigarette — it has already happened, you cannot undo it. The danger is the second. That is what turns a one-off episode into a return to smoking.' },
      { type: 'p', text: 'So all attention goes not to what already happened but to the next step. The first cigarette is an accident. The second is already a decision. And that decision is entirely in your hands.' },
      { type: 'h', text: 'What to do right now' },
      { type: 'p', text: 'Do exactly one thing: do not delay. Calmly review right away — what was the trigger? what caught you off guard? what will you try differently next time? — and return to the path. Not tomorrow, not "from Monday" — now.' },
      { type: 'p', text: 'The faster you return, the less this slip means at all. In a month it will be just a line in the story, not the end of it. And a trigger you have understood will make you stronger than you were before the slip.' },
    ],
    takeawayRu: 'Срыв ≠ провал. Опасна не первая сигарета, а вторая. Разбери триггер и вернись.',
    takeawayEn: 'A slip is not a failure. The danger is not the first cigarette but the second. Review and return.',
  },
  {
    id: 'slip-ave', category: 'slip', icon: 'brain', color: '#5AC8FA', readMin: 4,
    titleRu: 'Эффект «раз сорвался — гори всё»', titleEn: 'The "I blew it" effect',
    leadRu: 'Самая опасная мысль после срыва — и как её обезвредить.',
    leadEn: 'The most dangerous thought after a slip — and how to defuse it.',
    bodyRu: [
      { type: 'h', text: 'У этой мысли есть имя' },
      { type: 'p', text: 'После срыва в голове почти всегда щёлкает одна и та же мысль: «всё, я сорвался, я слабак, день потерян — какая теперь разница, можно курить дальше». Если ты её узнаёшь — ты не один. Это настолько типичная штука, что у неё есть научное название: эффект нарушения воздержания, по-английски AVE.' },
      { type: 'p', text: 'И вот в чём ключевой момент, который стоит понять раз и навсегда: именно эта мысль, а не сама сигарета, превращает разовый срыв в полный возврат к курению.' },
      { type: 'h', text: 'Посчитай буквально' },
      { type: 'p', text: 'Одна сигарета — это одна сигарета. Один эпизод. Небольшой откат, который легко наверстать. А вот пачка, выкуренная за вечер, — это уже не «срыв», это работа AVE. Это та самая мысль «гори всё», доведённая до логического конца.' },
      { type: 'p', text: 'Вред нанесла не первая сигарета, а разрешение, которое ты сам себе выдал после неё. Между первой сигаретой и пачкой стоит не никотин — стоит одна мысль. И с этой мыслью можно работать.' },
      { type: 'h', text: 'Как обезвредить: смени объяснение' },
      { type: 'p', text: 'Хорошая новость: эту мысль можно обезвредить. Способ называется переатрибуция — если проще, смена объяснения. Сравни две формулировки одного и того же срыва.' },
      { type: 'p', text: 'Первая: «я сорвался, потому что я слабый и безвольный». Это объяснение внутреннее (дело во мне самом), постоянное (я такой всегда) и глобальное (это про всю мою личность). Из него нет выхода — оно просто бьёт по самооценке и оставляет в яме.' },
      { type: 'p', text: 'Вторая: «я сорвался, потому что попал в сильный триггер — выпил на дне рождения, рядом курили — и не подготовил план на эту ситуацию». Это объяснение внешнее, конкретное и, главное, исправимое. Причина не в том, что ты «такой», а в том, что конкретная ситуация застала врасплох.' },
      { type: 'h', text: 'Разница — в наличии двери' },
      { type: 'p', text: 'Разница не в словах — разница в том, что из второй формулировки есть конкретное действие: продумать, как вести себя на следующем дне рождения. Из первой действия нет вообще, только чувство вины.' },
      { type: 'p', text: 'Поэтому правило простое: после срыва осознанно выбирай ту формулировку, из которой ведёт дверь, а не ту, что просто запирает тебя внутри. Это не самообман — это честный и точный взгляд на причину, потому что у срыва почти всегда есть конкретный, исправимый триггер.' },
    ],
    bodyEn: [
      { type: 'h', text: 'This thought has a name' },
      { type: 'p', text: 'After a slip, almost always the same thought clicks in your head: "that is it, I slipped, I am weak, the day is lost — what difference does it make now, I might as well keep smoking". If you recognise it — you are not alone. It is so typical it has a scientific name: the Abstinence Violation Effect, or AVE.' },
      { type: 'p', text: 'And here is the key point worth understanding once and for all: it is this thought, not the cigarette itself, that turns a one-off slip into a full relapse.' },
      { type: 'h', text: 'Count it literally' },
      { type: 'p', text: 'One cigarette is one cigarette. A single episode. A small setback that is easy to make up. But a pack smoked in an evening is no longer a "slip" — it is AVE at work. It is that very "I blew it" thought taken to its logical end.' },
      { type: 'p', text: 'The harm was done not by the first cigarette but by the permission you handed yourself after it. Between the first cigarette and a pack stands not nicotine — one thought stands there. And that thought can be worked with.' },
      { type: 'h', text: 'How to defuse it: change the explanation' },
      { type: 'p', text: 'Good news: this thought can be defused. The method is called reattribution — put simply, changing the explanation. Compare two framings of the very same slip.' },
      { type: 'p', text: 'The first: "I slipped because I am weak and have no willpower". This explanation is internal (it is about me), permanent (I am always like this) and global (it is about my whole personality). There is no way out of it — it just hits your self-esteem and leaves you in the pit.' },
      { type: 'p', text: 'The second: "I slipped because I hit a strong trigger — I drank at a birthday party, people around were smoking — and I had no plan for that situation". This explanation is external, specific and, crucially, fixable. The cause is not that you "are like that", but that a particular situation caught you off guard.' },
      { type: 'h', text: 'The difference is having a door' },
      { type: 'p', text: 'The difference is not in the words — it is that the second framing leads to a concrete action: thinking through how to handle the next birthday party. The first leads to no action at all, only guilt.' },
      { type: 'p', text: 'So the rule is simple: after a slip, consciously choose the framing that has a door out, not the one that just locks you inside. This is not self-deception — it is an honest, accurate look at the cause, because a slip almost always has a concrete, fixable trigger.' },
    ],
    takeawayRu: 'Срыв в рецидив превращает мысль «гори всё», а не сигарета. Причина — триггер, а не «я слабак».',
    takeawayEn: 'It is the "I blew it" thought, not the cigarette, that causes relapse. The cause is a trigger, not weakness.',
  },
  {
    id: 'trig-coffee', category: 'triggers', icon: 'drop', color: '#BF5AF2', readMin: 4,
    titleRu: 'Кофе и сигарета: разорвать связку', titleEn: 'Coffee and cigarette: break the link',
    leadRu: 'Почему утренний кофе так тянет закурить.',
    leadEn: 'Why morning coffee makes you want to smoke.',
    bodyRu: [
      { type: 'h', text: 'Рука сама тянется к сигарете' },
      { type: 'p', text: 'Утро. Ты наливаешь чашку кофе — и рука почти сама тянется к сигарете. Без раздумий, без особой тяги, просто потому что «так положено». Если узнаёшь себя — это очень частая история, и у неё есть понятный механизм.' },
      { type: 'p', text: 'Дело в том, что если ты годами курил вместе с кофе, мозг прочно склеил их в одну пару. Утренняя чашка, перекур после обеда, кофе в перерыве с коллегами — десятки тысяч повторений. И в какой-то момент сам по себе вид и запах кофе стал сигналом «пора курить» — даже без всякой тяги к никотину.' },
      { type: 'h', text: 'Это рефлекс, а не зависимость от кофе' },
      { type: 'p', text: 'Это важно понять: ты не зависим от кофе и кофе тут не виноват. Это условный рефлекс — та же механика, что у собаки Павлова, у которой текла слюна на звонок. У тебя «звонок» — это кофе, а «слюна» — желание закурить.' },
      { type: 'p', text: 'И раз это рефлекс, у новости есть отличная сторона: рефлекс можно разорвать ровно так же, как он сложился — повторением нового сценария. Не силой воли, а переучиванием. Тебе не нужно «держаться» — тебе нужно несколько недель делать кофе-ритуал по-новому.' },
      { type: 'h', text: 'Поменяй весь ритуал кофе' },
      { type: 'p', text: 'Конкретно: первые недели две сознательно меняй весь ритуал кофе. Пей его в другом месте — не на том балконе или у того окна, где курил, а, скажем, за кухонным столом. Держи чашку другой рукой. Пей чуть быстрее обычного, не растягивая. Можно сменить саму чашку.' },
      { type: 'p', text: 'Чем меньше похоже на старый сценарий — тем слабее срабатывает рефлекс. Ты как будто запутываешь привычку: она ищет знакомую обстановку, а её нет, и сигнал «пора курить» гаснет.' },
      { type: 'h', text: 'Вставь новое звено' },
      { type: 'p', text: 'Хорошо помогает добавить новое действие в начало: сделай 5 минут спокойного дыхания ДО первой чашки. Так ты вставляешь между кофе и сигаретой новое звено и постепенно перестраиваешь цепочку.' },
      { type: 'p', text: 'Можно завести и приятную замену самому моменту перекура: пара минут у окна с чашкой, короткое видео, разговор. Важно, чтобы пауза после кофе осталась — просто без дыма.' },
      { type: 'h', text: 'И немного про химию' },
      { type: 'p', text: 'Кофеин слегка ускоряет вывод никотина из организма и в первые дни может сам по себе подстёгивать тягу. Поэтому в самом начале есть смысл временно уменьшить количество кофе — не навсегда, просто пока острее всего.' },
      { type: 'p', text: 'А через 2–3 недели рефлекс ослабнет, и кофе снова станет просто кофе, который больше не тянет за собой сигарету. Ты сохранишь любимый напиток — и потеряешь только лишнюю привычку рядом с ним.' },
    ],
    bodyEn: [
      { type: 'h', text: 'Your hand reaches for a cigarette by itself' },
      { type: 'p', text: 'Morning. You pour a cup of coffee — and your hand almost reaches for a cigarette by itself. No thinking, no particular craving, just because "that is how it is done". If you recognise yourself — this is a very common story, and it has a clear mechanism.' },
      { type: 'p', text: 'The thing is, if you smoked together with coffee for years, the brain firmly glued them into one pair. The morning cup, the break after lunch, coffee with colleagues — tens of thousands of repetitions. And at some point the very sight and smell of coffee became a "time to smoke" signal — even without any nicotine craving.' },
      { type: 'h', text: 'It is a reflex, not a coffee addiction' },
      { type: 'p', text: 'This matters to understand: you are not addicted to coffee and coffee is not to blame. It is a conditioned reflex — the same mechanics as Pavlov’s dog, whose mouth watered at a bell. Your "bell" is coffee, and the "saliva" is the urge to smoke.' },
      { type: 'p', text: 'And since it is a reflex, the news has a great side: a reflex can be broken exactly the way it formed — by repeating a new script. Not with willpower, but with retraining. You do not need to "hold on" — you need to do the coffee ritual in a new way for a few weeks.' },
      { type: 'h', text: 'Change the whole coffee ritual' },
      { type: 'p', text: 'Concretely: for the first couple of weeks, deliberately change the whole coffee ritual. Drink it in a different place — not on that balcony or by that window where you smoked, but, say, at the kitchen table. Hold the cup with the other hand. Drink a little faster than usual, without dragging it out. You can even switch the mug itself.' },
      { type: 'p', text: 'The less it resembles the old script — the weaker the reflex fires. You are, in a sense, confusing the habit: it looks for the familiar setting, and there is none, so the "time to smoke" signal fades.' },
      { type: 'h', text: 'Insert a new link' },
      { type: 'p', text: 'It helps to add a new action at the start: do 5 minutes of calm breathing BEFORE the first cup. That way you insert a new link between coffee and cigarette and gradually rewire the chain.' },
      { type: 'p', text: 'You can also give the smoke-break moment itself a pleasant replacement: a couple of minutes by the window with the cup, a short video, a chat. The important thing is that the pause after coffee stays — just without the smoke.' },
      { type: 'h', text: 'And a little about chemistry' },
      { type: 'p', text: 'Caffeine slightly speeds the clearance of nicotine and in the first days can fuel cravings on its own. So at the very start it makes sense to cut coffee temporarily — not forever, just while it is sharpest.' },
      { type: 'p', text: 'And after 2–3 weeks the reflex weakens, and coffee becomes just coffee again, no longer pulling a cigarette with it. You keep your favourite drink — and lose only the extra habit beside it.' },
    ],
    takeawayRu: 'Кофе тянет курить из-за рефлекса. Меняй ритуал кофе 2 недели — связка распадётся.',
    takeawayEn: 'Coffee triggers smoking via a reflex. Change the coffee ritual for 2 weeks and the link breaks.',
  },
  {
    id: 'trig-alcohol', category: 'triggers', icon: 'drop2', color: '#BF5AF2', readMin: 5,
    titleRu: 'Алкоголь — главная ловушка', titleEn: 'Alcohol is the main trap',
    leadRu: 'Самая частая причина срыва — вечер с выпивкой.',
    leadEn: 'The most common cause of a slip — an evening with drinks.',
    bodyRu: [
      { type: 'h', text: 'Где люди срываются чаще всего' },
      { type: 'p', text: 'Если посмотреть, где люди срываются чаще всего, картина почти всегда одна и та же: пятница, компания, бокал, второй — и вот уже «да ладно, одну можно». Алкоголь — триггер номер один для срывов, и это не случайность.' },
      { type: 'p', text: 'Тут работают сразу три механизма, и работают они вместе, усиливая друг друга. Разберём каждый — когда понимаешь, как именно тебя ловят, ловушку гораздо легче обойти.' },
      { type: 'h', text: 'Механизм первый: падает самоконтроль' },
      { type: 'p', text: 'Первое и главное — алкоголь напрямую снижает самоконтроль. Префронтальная кора, та часть мозга, что отвечает за здравое «не надо, ты же бросаешь», отключается одной из первых, ещё до того как ты почувствуешь себя по-настоящему пьяным.' },
      { type: 'p', text: 'Поэтому решение «всего одну, ничего не будет» принимается так легко — не потому что ты слабый, а потому что в этот момент твой внутренний тормоз буквально выключен химией.' },
      { type: 'h', text: 'Механизмы второй и третий: связка и компания' },
      { type: 'p', text: 'Второе — связка, ровно как с кофе. Если ты годами курил в барах, на вечеринках, за разговором с бокалом, то сама эта обстановка — гомон, музыка, рюмка в руке — для мозга мощный сигнал «время курить». Тяга приходит не от никотина, а от декораций.' },
      { type: 'p', text: 'Третье — простая социальная физика: там, где пьют, чаще курят. Тебе предложат сигарету напрямую, протянут пачку, позовут «выйти подышать». И отказаться на трезвую голову куда легче, чем после третьего бокала.' },
      { type: 'h', text: 'Как это рушится — живой пример' },
      { type: 'p', text: 'Человек две недели держался идеально. Пошёл на день рождения, решил «расслаблюсь, я же молодец». После пары бокалов друг закурил рядом, протянул пачку — и рука сама взяла.' },
      { type: 'p', text: 'Наутро — тяжёлое чувство и мысль «как же так, я ведь справлялся». А справлялся — пока трезвый мозг принимал решения. Сорвался не «слабый человек», сорвался человек, у которого алкоголь выключил тормоз, а плана на этот случай не было.' },
      { type: 'h', text: 'Что делать в первые недели' },
      { type: 'p', text: 'Пока зависимость ещё свежая, самое надёжное — по возможности вообще избегать ситуаций с алкоголем или резко ограничить дозу. Это не навсегда, это просто защита самого хрупкого периода.' },
      { type: 'p', text: 'А если идёшь — иди с готовым планом, придуманным заранее и трезвым. Реши конкретно, не «как-нибудь разберусь на месте»: что именно ответишь, если предложат сигарету; будешь ли выходить на улицу с курящими или останешься внутри; во сколько уйдёшь домой.' },
      { type: 'p', text: 'План, составленный трезвой головой, — это и есть тот тормоз, который алкоголь потом отключит. Ты как будто оставляешь себе записку от более разумной версии себя.' },
    ],
    bodyEn: [
      { type: 'h', text: 'Where people slip most often' },
      { type: 'p', text: 'Look at where people slip most often, and the picture is almost always the same: Friday, company, one glass, a second — and already "come on, one is fine". Alcohol is the number one trigger for slips, and that is no accident.' },
      { type: 'p', text: 'Three mechanisms work here at once, and they work together, reinforcing each other. Let us take each one — when you understand how exactly you are caught, the trap is far easier to walk around.' },
      { type: 'h', text: 'Mechanism one: self-control drops' },
      { type: 'p', text: 'First and foremost — alcohol directly lowers self-control. The prefrontal cortex, the part responsible for the sensible "do not, you are quitting", is one of the first to switch off, even before you feel truly drunk.' },
      { type: 'p', text: 'That is why the decision "just one, nothing will happen" comes so easily — not because you are weak, but because at that moment your inner brake is literally switched off by chemistry.' },
      { type: 'h', text: 'Mechanisms two and three: the link and the company' },
      { type: 'p', text: 'Second — the link, exactly as with coffee. If you smoked for years in bars, at parties, in conversation with a glass, then that very setting — the noise, the music, a drink in hand — is a powerful "time to smoke" signal for the brain. The craving comes not from nicotine but from the scenery.' },
      { type: 'p', text: 'Third — simple social physics: where people drink, they smoke more. Someone will offer you a cigarette directly, hold out the pack, call you to "step out for air". And refusing with a clear head is far easier than after the third glass.' },
      { type: 'h', text: 'How it falls apart — a real example' },
      { type: 'p', text: 'A person held on perfectly for two weeks. Went to a birthday party, decided "I will relax, I have earned it". After a couple of glasses a friend lit up nearby, held out the pack — and the hand took it on its own.' },
      { type: 'p', text: 'In the morning — a heavy feeling and the thought "how could this happen, I was managing". They were managing — while a sober brain was making the decisions. It was not a "weak person" who slipped; it was a person whose brake alcohol switched off, with no plan for the moment.' },
      { type: 'h', text: 'What to do in the first weeks' },
      { type: 'p', text: 'While the dependence is still fresh, the most reliable thing is to avoid alcohol situations entirely where possible, or sharply limit the dose. This is not forever — it is just protection for the most fragile period.' },
      { type: 'p', text: 'And if you go — go with a ready plan, made in advance and sober. Decide concretely, not "I will figure it out on the spot": what exactly you will say if offered a cigarette; whether you will step outside with smokers or stay in; what time you will leave.' },
      { type: 'p', text: 'A plan made by a sober mind is the very brake that alcohol will later switch off. It is like leaving yourself a note from a wiser version of yourself.' },
    ],
    takeawayRu: 'Алкоголь снимает самоконтроль — отсюда срывы. Первые недели ограничь его и иди с планом.',
    takeawayEn: 'Alcohol removes self-control — hence slips. Limit it in the first weeks and go in with a plan.',
  },
  {
    id: 'trig-stress', category: 'triggers', icon: 'brain', color: '#BF5AF2', readMin: 5,
    titleRu: 'Никотин не снимает стресс', titleEn: 'Nicotine does not relieve stress',
    leadRu: 'Главный миф, который держит людей на сигарете.',
    leadEn: 'The main myth that keeps people smoking.',
    bodyRu: [
      { type: 'h', text: 'Фраза, которая держит крепче всего' },
      { type: 'p', text: '«Я курю, потому что это меня успокаивает». Если есть одна фраза, которая держит людей на сигарете крепче всего, — то это она. И именно она, при ближайшем рассмотрении, оказывается неправдой. Причём очень коварной неправдой.' },
      { type: 'p', text: 'Начнём с факта, который многих удивляет: курильщик в среднем живёт с более высоким базовым уровнем стресса и тревоги, чем некурящий. Не с меньшим — с большим. То есть сигарета не делает жизнь спокойнее, она делает её тревожнее.' },
      { type: 'h', text: 'Как возникает иллюзия' },
      { type: 'p', text: 'Как же тогда возникает ощущение, что она «помогает»? Вот как это устроено, шаг за шагом. Ты выкурил сигарету. Проходит час, полтора — и уровень никотина в крови падает.' },
      { type: 'p', text: 'Начинается лёгкая, почти незаметная отмена: нарастает раздражительность, внутреннее напряжение, лёгкое беспокойство. Ты можешь даже не связывать это с курением — просто «что-то нервничаю».' },
      { type: 'p', text: 'Потом ты закуриваешь снова. И напряжение спадает. Мозг радостно фиксирует: «сигарета меня успокоила». Но смотри внимательно — что именно она сняла? Не стресс от работы, не ссору, не дедлайн. Она сняла ту самую отмену никотина, которая возникла только потому, что ты куришь.' },
      { type: 'h', text: 'Замкнутый круг' },
      { type: 'p', text: 'Получается замкнутый круг. Сигарета создаёт небольшой стресс отмены — а следующая сигарета его снимает — и это снятие ты принимаешь за «расслабление».' },
      { type: 'p', text: 'Курильщик не лечит стресс жизни. Он бесконечно лечит ломку, которую сам себе и устроил. Это как носить тесную обувь весь день только ради блаженного момента, когда её снимаешь.' },
      { type: 'h', text: 'Кто на самом деле снимает напряжение' },
      { type: 'p', text: 'Представь обычную картину: тяжёлый разговор, ты выходишь покурить и чувствуешь облегчение. Но облегчение пришло не от никотина — оно пришло от того, что ты вышел из комнаты, постоял пять минут в тишине, подышал, переключился.' },
      { type: 'p', text: 'Ровно то же самое дала бы прогулка без сигареты. Просто никотин присвоил себе чужую заслугу. Пауза, тишина, дыхание, смена обстановки — вот что реально успокаивает, и всё это доступно тебе без дыма.' },
      { type: 'h', text: 'Что говорят исследования' },
      { type: 'p', text: 'И вот что говорят исследования — это, пожалуй, самое обнадёживающее. Через несколько недель после отказа базовый уровень тревоги у бросивших не растёт, а СНИЖАЕТСЯ. Не курить — объективно спокойнее, чем курить.' },
      { type: 'p', text: 'Просто эффект виден не сразу: первые дни отмена шумит и маскирует правду, а вот дальше открывается тишина, которой у тебя не было годами. Ты не теряешь «успокоительное» — ты избавляешься от источника фоновой тревоги.' },
    ],
    bodyEn: [
      { type: 'h', text: 'The phrase that holds tightest' },
      { type: 'p', text: '"I smoke because it calms me down." If there is one phrase that keeps people on cigarettes most firmly — it is this one. And it is precisely this one that, on closer inspection, turns out to be false. A very treacherous kind of false.' },
      { type: 'p', text: 'Let us start with a fact that surprises many: a smoker, on average, lives with a higher baseline level of stress and anxiety than a non-smoker. Not lower — higher. So a cigarette does not make life calmer, it makes it more anxious.' },
      { type: 'h', text: 'How the illusion arises' },
      { type: 'p', text: 'How then does the feeling that it "helps" arise? Here is how it works, step by step. You smoked a cigarette. An hour, an hour and a half pass — and the nicotine level in your blood drops.' },
      { type: 'p', text: 'A mild, almost unnoticeable withdrawal begins: irritability rises, inner tension, a slight unease. You might not even connect it to smoking — just "feeling a bit on edge".' },
      { type: 'p', text: 'Then you light up again. And the tension fades. The brain happily records: "the cigarette calmed me". But look closely — what exactly did it relieve? Not work stress, not the argument, not the deadline. It relieved that same nicotine withdrawal, which arose only because you smoke.' },
      { type: 'h', text: 'A closed loop' },
      { type: 'p', text: 'The result is a closed loop. A cigarette creates a small withdrawal stress — the next cigarette relieves it — and that relief you mistake for "relaxation".' },
      { type: 'p', text: 'A smoker does not treat life stress. They endlessly treat a withdrawal they inflicted on themselves. It is like wearing tight shoes all day just for the blissful moment of taking them off.' },
      { type: 'h', text: 'What actually relieves the tension' },
      { type: 'p', text: 'Picture an ordinary scene: a hard conversation, you step out for a smoke and feel relief. But the relief did not come from nicotine — it came from leaving the room, standing five minutes in quiet, breathing, switching off.' },
      { type: 'p', text: 'A walk without a cigarette would have given exactly the same. Nicotine simply took credit for someone else’s work. A pause, quiet, breathing, a change of setting — that is what actually calms you, and all of it is available to you without smoke.' },
      { type: 'h', text: 'What studies say' },
      { type: 'p', text: 'And here is what studies say — perhaps the most reassuring part. A few weeks after quitting, baseline anxiety in quitters does not rise but goes DOWN. Not smoking is objectively calmer than smoking.' },
      { type: 'p', text: 'The effect just is not visible right away: in the first days withdrawal makes noise and masks the truth, but after that a quiet opens up that you have not had for years. You are not losing a "sedative" — you are getting rid of a source of background anxiety.' },
    ],
    takeawayRu: 'Сигарета снимает не стресс, а свою же отмену. Через недели без неё тревоги становится меньше.',
    takeawayEn: 'A cigarette relieves its own withdrawal, not stress. Weeks later, baseline anxiety is lower.',
  },
  {
    id: 'body-timeline', category: 'body', icon: 'heart', color: '#FF453A', readMin: 5,
    titleRu: 'Что происходит с телом по дням', titleEn: 'What happens to your body, day by day',
    leadRu: 'Восстановление начинается через 20 минут.',
    leadEn: 'Recovery starts within 20 minutes.',
    bodyRu: [
      { type: 'h', text: 'Тело не ждёт «подходящего момента»' },
      { type: 'p', text: 'Вот что важно почувствовать в самом начале пути: тело не ждёт «подходящего момента», чтобы начать восстанавливаться. Оно берётся за дело почти сразу после твоей последней сигареты — и дальше уже не останавливается.' },
      { type: 'p', text: 'Пока ты читаешь это, ремонт уже идёт. Ниже — что и когда происходит, по порядку. Это не обещания, а описанная физиология восстановления.' },
      { type: 'h', text: 'Первые часы и сутки' },
      { type: 'p', text: 'Через 20 минут после последней сигареты пульс и артериальное давление, подстёгнутые никотином, начинают приходить в норму. Сердцу уже немного легче.' },
      { type: 'p', text: 'Через 8–12 часов уровень угарного газа в крови падает примерно вдвое. Это тот самый газ из дыма, который занимал в крови место кислорода. Теперь кислород возвращается — и его получают мышцы, мозг, каждая ткань. Многие именно в этот момент впервые замечают, что дышится чуть свободнее.' },
      { type: 'h', text: 'Первые дни' },
      { type: 'p', text: 'Через 2 суток никотин полностью выведен из организма — физическая зависимость от вещества, по сути, уже позади. И как приятный бонус начинают оживать притупленные курением вкус и обоняние: еда становится ярче, запахи — отчётливее. Это удивляет почти каждого бросившего.' },
      { type: 'p', text: 'Через 3 суток расслабляются бронхи, дышать становится заметно легче. А дальше, на отрезке от 2 до 12 недель, по-настоящему улучшается кровообращение и растёт функция лёгких — подняться по лестнице или пройтись быстрым шагом уже не так тяжело, как раньше.' },
      { type: 'h', text: 'Месяцы и годы' },
      { type: 'p', text: 'На дистанции от 1 до 9 месяцев постепенно уходит знакомый кашель курильщика. В лёгких восстанавливается реснитчатый эпителий — крошечные «реснички», которые выметают из лёгких слизь и грязь. У курильщика они были парализованы, теперь они снова работают и чистят тебя изнутри.' },
      { type: 'p', text: 'А на горизонте лет без курения цифры становятся по-настоящему весомыми: риск инфаркта, инсульта и рака лёгких снижается в разы. Тело отыгрывает назад годы вреда.' },
      { type: 'h', text: 'Каждый день — это ремонт' },
      { type: 'p', text: 'Запомни из этого одно. Каждый прожитый без сигарет день — это не просто «сегодня я не навредил себе». Это день активного, реального восстановления, которое происходит в твоём теле прямо сейчас, без твоих усилий.' },
      { type: 'p', text: 'Ты уже не разрушаешь — ты чинишь. И счётчик дней в приложении показывает именно это: не «сколько ты терпел», а сколько дней твоё тело занималось ремонтом.' },
    ],
    bodyEn: [
      { type: 'h', text: 'The body does not wait for the "right moment"' },
      { type: 'p', text: 'Here is what matters to feel at the very start of the journey: the body does not wait for the "right moment" to begin recovering. It gets to work almost immediately after your last cigarette — and from then on it does not stop.' },
      { type: 'p', text: 'As you read this, the repair is already under way. Below is what happens and when, in order. These are not promises but the described physiology of recovery.' },
      { type: 'h', text: 'The first hours and day' },
      { type: 'p', text: '20 minutes after the last cigarette, heart rate and blood pressure, spurred by nicotine, begin to return to normal. The heart already has it a little easier.' },
      { type: 'p', text: 'After 8–12 hours the carbon monoxide level in the blood drops by about half. That is the gas from smoke that took the place of oxygen in your blood. Now oxygen returns — and reaches the muscles, the brain, every tissue. Many people notice for the first time at this point that breathing feels a bit freer.' },
      { type: 'h', text: 'The first days' },
      { type: 'p', text: 'After 2 days nicotine is fully cleared from the body — the physical dependence on the substance is, in essence, already behind you. And as a pleasant bonus, the taste and smell dulled by smoking start to come alive: food gets brighter, smells sharper. This surprises almost every quitter.' },
      { type: 'p', text: 'After 3 days the bronchi relax and breathing becomes noticeably easier. And further on, over the stretch from 2 to 12 weeks, circulation genuinely improves and lung function grows — climbing stairs or walking briskly is no longer as hard as before.' },
      { type: 'h', text: 'Months and years' },
      { type: 'p', text: 'Over the span from 1 to 9 months the familiar smoker’s cough gradually fades. The lung cilia regenerate — the tiny "hairs" that sweep mucus and dirt out of the lungs. In a smoker they were paralysed; now they work again and clean you from the inside.' },
      { type: 'p', text: 'And on the horizon of years smoke-free the numbers become truly weighty: the risk of heart attack, stroke and lung cancer drops several-fold. The body wins back years of damage.' },
      { type: 'h', text: 'Every day is repair' },
      { type: 'p', text: 'Take one thing from this. Every smoke-free day is not just "today I did not harm myself". It is a day of active, real recovery happening in your body right now, without your effort.' },
      { type: 'p', text: 'You are no longer destroying — you are repairing. And the day counter in the app shows exactly that: not "how long you endured", but how many days your body has spent on repair.' },
    ],
    takeawayRu: 'Восстановление идёт уже с 20-й минуты. Каждый день без сигарет тело реально чинит себя.',
    takeawayEn: 'Recovery begins at minute 20. Every smoke-free day, your body is actively repairing itself.',
  },
  {
    id: 'body-weight', category: 'body', icon: 'leaf', color: '#FF453A', readMin: 4,
    titleRu: 'Прибавка в весе — правда?', titleEn: 'Weight gain — is it true?',
    leadRu: 'Что реально происходит и что с этим делать.',
    leadEn: 'What really happens and what to do about it.',
    bodyRu: [
      { type: 'h', text: 'Честно и по порядку' },
      { type: 'p', text: '«А правда, что если бросить, то растолстеешь?» Этот страх останавливает очень многих, особенно если человек и так следит за весом. Поэтому давай честно и по порядку — что тут правда, а что преувеличение.' },
      { type: 'p', text: 'Правда вот в чём: да, часть людей после отказа действительно немного набирает вес — в среднем 2–4 кг за первые месяцы. Ключевые слова — «часть» и «немного». Это не происходит со всеми, это не неизбежно, и это точно не тот масштаб, ради которого стоит и дальше травить себя дымом.' },
      { type: 'h', text: 'Откуда берутся эти килограммы' },
      { type: 'p', text: 'Причин две. Первая чисто физиологическая: никотин слегка подстёгивал обмен веществ и приглушал аппетит. Без него тело просто возвращается к своей нормальной, естественной скорости — той, что была до курения.' },
      { type: 'p', text: 'Вторая причина поведенческая: рука по привычке ищет ритуал «рука-рот», и его место часто занимает еда, особенно сладкое. Перекус становится новым способом «занять» тягу.' },
      { type: 'h', text: 'На обе причины можно мягко повлиять' },
      { type: 'p', text: 'Хорошая новость — и без героизма. Пей больше воды, особенно когда кажется, что хочется перекусить — жажду легко перепутать с голодом. Держи под рукой не печенье и конфеты, а орехи, нарезанные овощи, жвачку: они закрывают тот самый жест «рука-рот», но без сахарной горки.' },
      { type: 'p', text: 'Очень помогает движение. Добавь хотя бы 10–15 минут ходьбы в день — это одновременно и снижает аппетит, и сбивает тягу к сигарете, то есть бьёт сразу по двум зайцам. Не нужно изматывающих тренировок, достаточно регулярной прогулки.' },
      { type: 'h', text: 'Не делай два дела сразу' },
      { type: 'p', text: 'Одна важная оговорка: не садись на жёсткую диету одновременно с отказом от курения. Это две большие нагрузки сразу, и вместе они почти всегда заканчиваются срывом — либо по еде, либо по сигаретам.' },
      { type: 'p', text: 'Делай по одному. Сначала спокойно закрепи отказ, и только потом, без спешки, занимайся весом. Так у каждой задачи будет шанс получиться.' },
      { type: 'h', text: 'Главное — в цифрах' },
      { type: 'p', text: 'Чтобы расставить всё по местам: вред от 2–4 лишних килограммов несопоставимо, в десятки раз меньше вреда от курения. Чтобы по риску для сердца сравняться с курильщиком, человеку пришлось бы набрать порядка 35–40 кг — то есть в десять раз больше.' },
      { type: 'p', text: 'Так что приоритет очевиден: сначала бросаем курить, а вес, если он и появится, спокойно возвращаем потом. Это решаемая задача, и решать её куда легче, дыша полной грудью.' },
    ],
    bodyEn: [
      { type: 'h', text: 'Honestly, and in order' },
      { type: 'p', text: '"Is it true that if you quit, you get fat?" This fear stops a great many people, especially anyone who already watches their weight. So let us be honest and take it in order — what is true here and what is exaggerated.' },
      { type: 'p', text: 'Here is the truth: yes, some people do gain a little weight after quitting — on average 2–4 kg in the first months. The key words are "some" and "a little". It does not happen to everyone, it is not inevitable, and it is certainly not the kind of scale worth poisoning yourself with smoke over.' },
      { type: 'h', text: 'Where these kilograms come from' },
      { type: 'p', text: 'There are two reasons. The first is purely physiological: nicotine slightly spurred the metabolism and dulled appetite. Without it the body simply returns to its normal, natural pace — the one it had before smoking.' },
      { type: 'p', text: 'The second reason is behavioural: the hand keeps looking for the hand-to-mouth ritual out of habit, and food, especially sweets, often takes its place. A snack becomes a new way to "occupy" a craving.' },
      { type: 'h', text: 'Both causes can be gently managed' },
      { type: 'p', text: 'The good news — with no heroics. Drink more water, especially when you feel like snacking — thirst is easy to mistake for hunger. Keep nuts, cut vegetables and gum at hand instead of cookies and sweets: they cover that same hand-to-mouth gesture, but without the sugar pile.' },
      { type: 'p', text: 'Movement helps a lot. Add at least 10–15 minutes of walking a day — it both lowers appetite and knocks down the craving for a cigarette, hitting two targets at once. No exhausting workouts needed, a regular walk is enough.' },
      { type: 'h', text: 'Do not do two things at once' },
      { type: 'p', text: 'One important caveat: do not start a strict diet at the same time as quitting smoking. These are two big loads at once, and together they almost always end in a slip — either on food or on cigarettes.' },
      { type: 'p', text: 'Do one at a time. First calmly lock in the quit, and only then, without rushing, deal with weight. That way each task has a chance to succeed.' },
      { type: 'h', text: 'The main thing — in numbers' },
      { type: 'p', text: 'To put it all in place: the harm from 2–4 extra kilograms is incomparably, tens of times smaller than the harm from smoking. To match a smoker’s heart risk, a person would have to gain around 35–40 kg — ten times more.' },
      { type: 'p', text: 'So the priority is obvious: first quit smoking, and the weight, if it appears at all, you calmly address later. It is a solvable task, and far easier to solve while breathing freely.' },
    ],
    takeawayRu: 'Возможны 2–4 кг — это поправимо и в разы безопаснее курения. Сначала бросаем.',
    takeawayEn: '2–4 kg is possible — fixable and far safer than smoking. Quit first, address weight later.',
  },
  {
    id: 'body-vape', category: 'body', icon: 'wind', color: '#FF453A', readMin: 4,
    titleRu: 'Вейп бросить не легче', titleEn: 'Vaping is not easier to quit',
    leadRu: 'Почему «перешёл на вейп» — часто не выход.',
    leadEn: 'Why "switched to vaping" is often not a solution.',
    bodyRu: [
      { type: 'h', text: 'Сменил упаковку, а не вышел' },
      { type: 'p', text: '«Я бросил сигареты, перешёл на вейп» — звучит как победа. И многие искренне считают это шагом вперёд. Но если речь о никотиновой зависимости, то чаще всего человек не вышел из неё, а просто сменил упаковку.' },
      { type: 'p', text: 'Вейп действительно ощущается мягче: нет едкого дыма, нет запаха, пар кажется почти безобидным. Но зависимость он создаёт ту же самую — никотиновую. А по факту нередко даже более крепкую, чем от сигарет. И вот почему.' },
      { type: 'h', text: 'У сигарет есть встроенные тормоза' },
      { type: 'p', text: 'Всё дело в дозе и доступности. У сигарет, как ни странно, есть встроенные тормоза. Пачка заканчивается — надо идти покупать. На улице дождь и холод — лишний раз не выйдешь. Докурил — окурок выброшен, эпизод закрыт.' },
      { type: 'p', text: 'Эти естественные паузы невольно ограничивают, сколько никотина ты получаешь за день. Они раздражают курильщика, но именно они не дают дозе расти бесконечно.' },
      { type: 'h', text: 'У вейпа тормозов нет' },
      { type: 'p', text: 'У вейпа таких тормозов нет вообще. Затяжка занимает одну секунду и не требует ничего поджигать. Устройство всегда лежит в кармане или на столе под рукой. А крепость жидкости часто заметно выше, чем человеку кажется — солевой никотин бьёт мягко на вкус, и легко недооценить дозу.' },
      { type: 'p', text: 'В итоге получается парадокс: вейпер за день нередко получает больше никотина, чем получал курильщиком. И главное — он парит «на автомате», фоном, между делом, даже не замечая и не считая затяжки. Зависимость не ушла, она стала незаметнее, а оттого ещё цепче.' },
      { type: 'h', text: 'Бросают вейп так же, как сигареты' },
      { type: 'p', text: 'Поэтому хорошая новость в том, что бросать вейп нужно не «как-то иначе» — а ровно так же, как сигареты. Это та же зависимость, и работают те же инструменты: те же триггеры (кофе, стресс, алкоголь, скука), те же техники, те же волны тяги по 3–5 минут, которые проходят сами.' },
      { type: 'p', text: 'Всё, что ты читаешь в этом приложении, применимо к вейпу один в один. Тебе не нужна отдельная стратегия — нужна та же самая.' },
      { type: 'h', text: 'Пара уточнений для вейпа' },
      { type: 'p', text: 'Если решил снижать постепенно — снижай не количество затяжек, а крепость жидкости, то есть миллиграммы никотина. Считать затяжки бесполезно: рука легко начнёт парить чаще и компенсирует.' },
      { type: 'p', text: 'И обязательно убирай устройство из зоны лёгкого доступа — не носи в кармане, не клади на стол. Раз нет встроенных пауз — создай их себе сам.' },
    ],
    bodyEn: [
      { type: 'h', text: 'Changed the packaging, did not leave' },
      { type: 'p', text: '"I quit cigarettes, switched to vaping" — it sounds like a victory. And many sincerely consider it a step forward. But when it comes to nicotine dependence, most often the person has not left it — they have simply changed the packaging.' },
      { type: 'p', text: 'Vaping really does feel milder: no acrid smoke, no smell, the vapour seems almost harmless. But it creates the very same dependence — nicotine. And in fact often an even stronger one than cigarettes. Here is why.' },
      { type: 'h', text: 'Cigarettes have built-in brakes' },
      { type: 'p', text: 'It all comes down to dose and accessibility. Cigarettes, oddly enough, have built-in brakes. The pack runs out — you have to go buy more. It is raining and cold outside — you will not step out for an extra one. You finish — the butt is discarded, the episode closed.' },
      { type: 'p', text: 'These natural pauses involuntarily limit how much nicotine you get per day. They annoy the smoker, but it is exactly they that keep the dose from growing endlessly.' },
      { type: 'h', text: 'Vaping has no brakes' },
      { type: 'p', text: 'Vaping has no such brakes at all. A puff takes one second and requires nothing to be lit. The device is always in your pocket or on the desk within reach. And the liquid strength is often noticeably higher than the person thinks — salt nicotine hits softly on the taste, and the dose is easy to underestimate.' },
      { type: 'p', text: 'The result is a paradox: a vaper often gets more nicotine per day than they did as a smoker. And crucially — they vape on autopilot, in the background, between things, without even noticing or counting the puffs. The dependence has not gone, it has become less visible, and therefore even more tenacious.' },
      { type: 'h', text: 'Quit vaping the same way as cigarettes' },
      { type: 'p', text: 'So the good news is that quitting vaping does not need to be done "somehow differently" — it is done exactly the same way as cigarettes. It is the same dependence, and the same tools work: the same triggers (coffee, stress, alcohol, boredom), the same techniques, the same 3–5 minute craving waves that pass on their own.' },
      { type: 'p', text: 'Everything you read in this app applies to vaping one to one. You do not need a separate strategy — you need the very same one.' },
      { type: 'h', text: 'A couple of notes for vaping' },
      { type: 'p', text: 'If you decide to taper gradually — lower not the puff count but the liquid strength, that is, the milligrams of nicotine. Counting puffs is useless: the hand easily starts vaping more often and compensates.' },
      { type: 'p', text: 'And be sure to move the device out of easy reach — do not carry it in your pocket, do not leave it on the desk. Since there are no built-in pauses — create them for yourself.' },
    ],
    takeawayRu: 'Вейп — та же никотиновая зависимость, часто крепче. Бросают так же: триггеры, техники, волны.',
    takeawayEn: 'Vaping is the same nicotine dependence, often stronger. Quit it the same way.',
  },
  {
    id: 'meds-overview', category: 'meds', icon: 'shield', color: '#30D158', readMin: 5,
    titleRu: 'Лекарства: цитизин, бупропион, варениклин', titleEn: 'Medication: cytisine, bupropion, varenicline',
    leadRu: 'Когда таблетки помогают и как они работают.',
    leadEn: 'When pills help and how they work.',
    bodyRu: [
      { type: 'h', text: 'Лекарства — это не «жульничество»' },
      { type: 'p', text: 'Сразу проясним одну вещь, потому что вокруг неё много стыда: использовать лекарства, чтобы бросить, — это не «жульничество» и не признак слабости.' },
      { type: 'p', text: 'Поведенческие техники — дыхание, работа с триггерами, скольжение по тяге — отлично работают для очень многих. Но при сильной зависимости одних техник иногда не хватает, и это нормально. Тогда на помощь приходит медикаментозная поддержка: она снижает тягу и сглаживает отмену, освобождая силы на всё остальное.' },
      { type: 'h', text: 'Цитизин' },
      { type: 'p', text: 'Цитизин (известен как Табекс) — препарат растительного происхождения, в России продаётся без рецепта. Работает он умно: мягко занимает в мозге те же никотиновые рецепторы, что и никотин.' },
      { type: 'p', text: 'Из-за этого, во-первых, слабее ощущается тяга, а во-вторых, если человек закурит, сигарета даёт заметно меньше привычного «эффекта» — курить становится просто не так интересно. Курс короткий, около 25 дней, и сам препарат недорогой.' },
      { type: 'h', text: 'Бупропион и варениклин' },
      { type: 'p', text: 'Бупропион — рецептурный препарат, по своей основной природе антидепрессант, который вдобавок снижает тягу к никотину. Он особенно уместен, если отказ идёт на фоне сниженного настроения или подавленности — тогда он работает сразу в двух направлениях.' },
      { type: 'p', text: 'Варениклин — препарат, который по доказательной базе считается самым эффективным из всех. Он тоже рецептурный и тоже подбирается только врачом.' },
      { type: 'h', text: 'Назначает только врач' },
      { type: 'p', text: 'А теперь — самое важное, и это нужно сказать прямо. Приложение не назначает лекарства и не может этого делать. Бупропион и варениклин подбирает исключительно врач: у них есть противопоказания и возможные побочные эффекты, которые обязательно нужно сверить именно с твоей ситуацией и здоровьем.' },
      { type: 'p', text: 'Даже безрецептурный цитизин, который можно купить самому, всё равно стоит сначала обсудить с врачом или хотя бы с фармацевтом в аптеке. Самоназначение тут — плохая идея.' },
      { type: 'h', text: 'Чем тут полезно приложение' },
      { type: 'p', text: 'Зато вот в чём приложение реально полезно: когда врач уже подобрал тебе препарат, оно поможет вести расписание приёма и аккуратно напоминать о дозах. И это не мелочь.' },
      { type: 'p', text: 'У всех этих препаратов регулярность приёма напрямую влияет на результат — пропущенные таблетки заметно снижают эффект. Так что роль приложения — быть твоим надёжным напоминанием, а роль врача — выбрать, что именно принимать.' },
    ],
    bodyEn: [
      { type: 'h', text: 'Medication is not "cheating"' },
      { type: 'p', text: 'Let us clear one thing up right away, because there is a lot of shame around it: using medication to quit is not "cheating" and not a sign of weakness.' },
      { type: 'p', text: 'Behavioural techniques — breathing, working with triggers, urge surfing — work great for very many people. But with strong dependence, techniques alone are sometimes not enough, and that is normal. Then medication support steps in: it lowers cravings and smooths out withdrawal, freeing your energy for everything else.' },
      { type: 'h', text: 'Cytisine' },
      { type: 'p', text: 'Cytisine (known as Tabex) is a plant-derived drug, sold over the counter in Russia. It works cleverly: it gently occupies the same nicotine receptors in the brain that nicotine does.' },
      { type: 'p', text: 'Because of this, first, cravings feel weaker, and second, if a person does smoke, the cigarette gives noticeably less of the usual "effect" — smoking simply becomes less interesting. The course is short, about 25 days, and the drug itself is inexpensive.' },
      { type: 'h', text: 'Bupropion and varenicline' },
      { type: 'p', text: 'Bupropion is a prescription drug, by its main nature an antidepressant, which additionally lowers the craving for nicotine. It is especially relevant if quitting happens against a background of low mood — then it works in two directions at once.' },
      { type: 'p', text: 'Varenicline is the drug considered the most effective of all by the evidence base. It is also prescription-only and also chosen only by a doctor.' },
      { type: 'h', text: 'Only a doctor prescribes it' },
      { type: 'p', text: 'And now the most important part, which needs to be said plainly. The app does not prescribe medication and cannot do so. Bupropion and varenicline are chosen exclusively by a doctor: they have contraindications and possible side effects that must be checked against your specific situation and health.' },
      { type: 'p', text: 'Even over-the-counter cytisine, which you can buy yourself, is still worth discussing first with a doctor or at least a pharmacist. Self-prescribing here is a bad idea.' },
      { type: 'h', text: 'Where the app is useful here' },
      { type: 'p', text: 'But here is where the app is genuinely useful: once a doctor has chosen a drug for you, it helps you keep the dosing schedule and reminds you of doses carefully. And that is no small thing.' },
      { type: 'p', text: 'For all of these drugs, regular dosing directly affects the result — missed pills noticeably reduce the effect. So the app’s role is to be your reliable reminder, and the doctor’s role is to choose what exactly to take.' },
    ],
    takeawayRu: 'При сильной зависимости лекарства помогают. Бупропион и варениклин — только через врача.',
    takeawayEn: 'With strong dependence, medication helps. Bupropion and varenicline — only via a doctor.',
  },
  {
    id: 'mot-money', category: 'motivation', icon: 'sparkle', color: '#34C759', readMin: 4,
    titleRu: 'Куда уходят деньги', titleEn: 'Where the money goes',
    leadRu: 'Маленькая ежедневная сумма складывается в крупную.',
    leadEn: 'A small daily sum adds up to a large one.',
    bodyRu: [
      { type: 'h', text: 'Расход, который не замечаешь' },
      { type: 'p', text: 'Пачка сигарет в день по отдельности кажется мелочью — ну, небольшая трата, как чашка кофе, на неё даже не обращаешь внимания. Именно в этом и хитрость. Расход незаметен поштучно, но это ежедневный платёж, который не прекращается ни на один день.' },
      { type: 'p', text: 'А теперь посмотри на это не как на «пачку», а как на ежедневный платёж. Ты платишь каждый день, без выходных, год за годом. И если сложить всё, что уходит за год, получается сумма, на которую вполне можно купить что-то крупное и заметное — то, на что ты, возможно, давно «не можешь найти денег».' },
      { type: 'h', text: 'Приложение делает цифру конкретной' },
      { type: 'p', text: 'Приложение считает это за тебя — автоматически, в реальном времени, начиная с первой минуты без сигарет. И это важный момент: цифра экономии перестаёт быть абстракцией из разряда «ну да, наверное, что-то экономлю».' },
      { type: 'p', text: 'Ты видишь конкретные деньги, которые прямо сейчас остаются у тебя в кармане, а не превращаются в дым. Это уже не догадка — это число, которое растёт у тебя на глазах.' },
      { type: 'h', text: 'Поставь конкретную цель' },
      { type: 'p', text: 'Но чтобы эти деньги по-настоящему мотивировали, с ними нужно кое-что сделать. Просто растущая цифра — это приятно, но абстрактно, мозгу не за что зацепиться.' },
      { type: 'p', text: 'Поэтому сделай экономию видимой и конкретной: поставь в копилке цель. Не «копить вообще», а на определённую вещь — наушники, которые давно хотел, поездку, подарок близкому человеку, что-то для дома.' },
      { type: 'h', text: 'Отказ из потери превращается в приобретение' },
      { type: 'p', text: 'Вот тут включается психология. Когда сэкономленное на сигаретах постепенно превращается в конкретную вещь, которую ты в итоге берёшь в руки, происходит важная перемена.' },
      { type: 'p', text: 'Отказ от курения перестаёт ощущаться только как потеря — «у меня отняли сигарету». Он становится приобретением — «я кое-что получил взамен». А это совсем другое чувство, и держаться с ним намного легче.' },
      { type: 'h', text: 'Эта вещь — твой якорь' },
      { type: 'p', text: 'И эта вещь работает как якорь. В трудный день, когда тянет и кажется, что отказ — это сплошное лишение, ты смотришь на цель в копилке или на уже купленную вещь — и она спокойно напоминает: курить ты бросаешь не «в минус», а «в плюс».' },
      { type: 'p', text: 'Прогресс не только в чистых лёгких, которые не видно. Он лежит у тебя на полке — то, что ты смог себе позволить, потому что не сжёг эти деньги.' },
    ],
    bodyEn: [
      { type: 'h', text: 'An expense you do not notice' },
      { type: 'p', text: 'A pack of cigarettes a day, taken on its own, seems like a trifle — a small spend, like a cup of coffee, you do not even notice it. That is exactly the trick. The expense is invisible piece by piece, but it is a daily payment that does not stop for a single day.' },
      { type: 'p', text: 'Now look at it not as a "pack" but as a daily payment. You pay every day, no days off, year after year. And if you add up everything that goes out over a year, you get a sum that could quite well buy something large and noticeable — the thing you perhaps "can never find the money for".' },
      { type: 'h', text: 'The app makes the figure concrete' },
      { type: 'p', text: 'The app counts this for you — automatically, in real time, starting from the first smoke-free minute. And this is an important point: the savings figure stops being an abstraction of the "well, I suppose I save something" kind.' },
      { type: 'p', text: 'You see concrete money that right now stays in your pocket instead of turning into smoke. It is no longer a guess — it is a number growing before your eyes.' },
      { type: 'h', text: 'Set a concrete goal' },
      { type: 'p', text: 'But for that money to truly motivate you, you need to do something with it. A simply growing number is pleasant but abstract — the brain has nothing to grab onto.' },
      { type: 'p', text: 'So make the savings visible and concrete: set a goal in the jar. Not "save in general", but for a specific thing — the headphones you have long wanted, a trip, a gift for someone close, something for the home.' },
      { type: 'h', text: 'Quitting turns from a loss into a gain' },
      { type: 'p', text: 'This is where the psychology kicks in. When the money saved on cigarettes gradually turns into a concrete thing you finally hold in your hands, an important shift happens.' },
      { type: 'p', text: 'Quitting stops feeling only like a loss — "my cigarette was taken away". It becomes a gain — "I got something in return". And that is an entirely different feeling, and far easier to hold on with.' },
      { type: 'h', text: 'That thing is your anchor' },
      { type: 'p', text: 'And that thing works as an anchor. On a hard day, when a craving hits and quitting feels like nothing but deprivation, you look at the goal in the jar or at the thing you have already bought — and it calmly reminds you: you are quitting not "into the minus" but "into the plus".' },
      { type: 'p', text: 'The progress is not only in clean lungs you cannot see. It sits on your shelf — the thing you could afford because you did not burn that money.' },
    ],
    takeawayRu: 'Поставь конкретную цель в копилке. Когда экономия станет вещью — это якорь в трудный день.',
    takeawayEn: 'Set a concrete jar goal. When savings become a real thing, they anchor you on hard days.',
  },
];

export function getArticle(id: string): Article | undefined {
  return ARTICLES.find((a) => a.id === id);
}

// Card illustrations. Static requires — RN bundles only what's listed here.
export const ARTICLE_IMAGES: Record<string, any> = {
  'craving-wave':  require('../assets/articles/craving-wave.png'),
  'craving-now':   require('../assets/articles/craving-now.png'),
  'craving-day3':  require('../assets/articles/craving-day3.png'),
  'craving-halt':  require('../assets/articles/craving-halt.png'),
  'slip-not-fail': require('../assets/articles/slip-not-fail.png'),
  'slip-ave':      require('../assets/articles/slip-ave.png'),
  'trig-coffee':   require('../assets/articles/trig-coffee.png'),
  'trig-alcohol':  require('../assets/articles/trig-alcohol.png'),
  'trig-stress':   require('../assets/articles/trig-stress.png'),
  'body-timeline': require('../assets/articles/body-timeline.png'),
  'body-weight':   require('../assets/articles/body-weight.png'),
  'body-vape':     require('../assets/articles/body-vape.png'),
  'meds-overview': require('../assets/articles/meds-overview.png'),
};

// Natural aspect ratio of an article image — so the card matches the picture
// exactly: no crop, no letterbox bars, no distortion.
export function articleAspect(id: string): number {
  const img = ARTICLE_IMAGES[id];
  if (!img) return 16 / 9;
  const s = Image.resolveAssetSource(img);
  return s && s.height ? s.width / s.height : 16 / 9;
}
