// Knowledge base — short, evidence-based coping articles.
// Sources: Marlatt RP, CDC, Cochrane reviews, USPSTF, Surgeon General 2020,
// Brewer "Craving to Quit", Taylor 2007 (exercise & craving), West 2017 (stress).

import type { IconKey } from '../components/Icon';

export type ArticleCategory = 'craving' | 'slip' | 'triggers' | 'body' | 'meds' | 'motivation';

export type Article = {
  id: string;
  category: ArticleCategory;
  icon: IconKey;
  color: string;
  readMin: number;
  titleRu: string; titleEn: string;
  leadRu: string;  leadEn: string;
  bodyRu: string[]; bodyEn: string[];
  takeawayRu: string; takeawayEn: string;
};

export const ARTICLE_CATEGORY: Record<ArticleCategory, { ru: string; en: string; icon: IconKey; color: string }> = {
  craving:    { ru: 'Тяга',        en: 'Cravings',   icon: 'flame',   color: '#FF9500' },
  slip:       { ru: 'Срыв',        en: 'Slips',      icon: 'feather', color: '#5AC8FA' },
  triggers:   { ru: 'Триггеры',    en: 'Triggers',   icon: 'bolt',    color: '#BF5AF2' },
  body:       { ru: 'Тело',        en: 'Your body',  icon: 'heart',   color: '#FF453A' },
  meds:       { ru: 'Лекарства',   en: 'Medication', icon: 'shield',  color: '#30D158' },
  motivation: { ru: 'Мотивация',   en: 'Motivation', icon: 'sparkle', color: '#34C759' },
};

export const ARTICLES: Article[] = [
  {
    id: 'craving-wave', category: 'craving', icon: 'wave2', color: '#FF9500', readMin: 4,
    titleRu: 'Тяга — это волна', titleEn: 'A craving is a wave',
    leadRu: 'Почему тяга всегда проходит сама, если её не кормить.',
    leadEn: 'Why a craving always passes on its own if you do not feed it.',
    bodyRu: [
      'Представь: ты на работе, конец тяжёлого дня, и вдруг накрывает — «надо закурить, прямо сейчас». Кажется, что это чувство будет только расти, давить всё сильнее, пока ты не сдашься. Именно так тяга и обманывает: она прикидывается бесконечной. Но это иллюзия.',
      'На самом деле тяга устроена как волна. Она поднимается, доходит до пика — и спадает. Сама. Без твоего участия. Обычно весь цикл занимает 3–5 минут. Не час, не «весь вечер» — несколько минут. Пик, который сейчас кажется невыносимым, длится секунды.',
      'Почему же тогда сигарета будто «помогает»? Тут и кроется ловушка. Ты закуриваешь как раз тогда, когда волна и без того пошла на спад — и мозг делает ложный вывод: «вот что меня спасло». Но если бы ты не закурил, волна спала бы ровно так же. Просто без новой дозы никотина, без подкормки зависимости, без отката завтра.',
      'Каждый раз курильщик «доказывает» себе, что без сигареты тягу не пережить. И каждый раз ошибается — он просто не дал волне доиграть до конца. А зря: именно прожитая до конца волна и есть лекарство.',
      'Дело в том, что каждая пережитая волна ослабляет следующую. Ты буквально переучиваешь мозг: оказывается, тягу можно пережить, и ничего страшного не случится. Это не сила воли — это новый навык, и он накапливается. Через 2–4 недели волны становятся короче, приходят реже и бьют слабее.',
      'Что конкретно делать, когда накрыло? Не бороться и не уговаривать себя — это только раскручивает. Наоборот, стань наблюдателем. Где именно ощущение в теле — в груди, в горле, в руках? Какое оно — жжёт, давит, крутит, зудит? Назови его про себя, спокойно, как будто описываешь погоду.',
      'Потом — несколько длинных, медленных выдохов. Не вдохов, а именно выдохов: они переключают нервную систему в спокойный режим. И просто наблюдай, как волна растёт и опадает, словно ты сёрфер, который не дерётся с волной, а скользит по ней. Эта техника так и называется — «скольжение по тяге», urge surfing. Ты не подавляешь желание и не выполняешь его. Ты его пережидаешь.',
    ],
    bodyEn: [
      'Picture this: you are at work, the end of a brutal day, and suddenly it hits — "I need to smoke, right now." It feels like this feeling will only grow, press harder and harder until you give in. That is exactly how a craving fools you: it pretends to be endless. But it is an illusion.',
      'In reality a craving works like a wave. It rises, reaches a peak — and falls. On its own. Without your help. The whole cycle usually takes 3–5 minutes. Not an hour, not "the whole evening" — a few minutes. The peak that feels unbearable right now lasts seconds.',
      'So why does a cigarette seem to "help"? That is where the trap is. You light up exactly when the wave is already on its way down — and the brain draws a false conclusion: "that is what saved me." But if you had not smoked, the wave would have fallen just the same. Only without a new dose of nicotine, without feeding the dependence, without the rebound tomorrow.',
      'Every time, a smoker "proves" to themselves that a craving cannot be survived without a cigarette. And every time, they are wrong — they simply never let the wave play out to the end. A shame, because a wave ridden all the way through is the actual cure.',
      'The thing is, every wave you ride weakens the next one. You are literally retraining the brain: it turns out a craving can be survived, and nothing terrible happens. This is not willpower — it is a new skill, and it accumulates. Within 2–4 weeks waves get shorter, come less often and hit weaker.',
      'What exactly do you do when it hits? Do not fight or argue with yourself — that only winds it up. Instead, become an observer. Where exactly is the sensation in the body — chest, throat, hands? What is it like — burning, pressing, twisting, itching? Name it silently, calmly, as if describing the weather.',
      'Then take a few long, slow exhales. Not inhales — exhales: they switch the nervous system into a calm mode. And just watch the wave grow and fade, like a surfer who does not fight the wave but glides over it. This technique is called urge surfing. You are not suppressing the urge and not obeying it. You are riding it out.',
    ],
    takeawayRu: 'Тяга длится 3–5 минут и проходит сама. Твоя задача — не закурить, а переждать волну.',
    takeawayEn: 'A craving lasts 3–5 minutes and passes by itself. Your job is not to smoke — just to ride the wave.',
  },
  {
    id: 'craving-now', category: 'craving', icon: 'bolt', color: '#FF9500', readMin: 3,
    titleRu: 'Тянет прямо сейчас — что сделать', titleEn: 'Craving right now — what to do',
    leadRu: 'Короткий план на ближайшие 5 минут.',
    leadEn: 'A short plan for the next 5 minutes.',
    bodyRu: [
      'Если ты открыл эту статью прямо сейчас, потому что тянет, — хорошо, что открыл. Это уже выигранные тридцать секунд. А тяга, как ты помнишь, живёт всего 3–5 минут. Дальше — простой план, который их закроет.',
      '1. Засеки время. Прямо сейчас скажи себе: «я не курю ближайшие 5 минут». Не «никогда», не «всю оставшуюся жизнь» — это слишком огромно, мозг такое не берёт. Только 5 минут. Вот это посильно. С такой задачей справится кто угодно.',
      '2. Дыши. Звучит банально, но это работает на уровне физиологии: длинный выдох, вдвое длиннее вдоха, переключает нервную систему в спокойный режим примерно за минуту. Открой в приложении дыхательную практику или просто сделай 10 медленных выдохов, считая про себя. Вдох на 4 — выдох на 8.',
      '3. Смени обстановку. Тяга крепко привязана к месту и позе: тот самый стул, то самое окно, тот самый угол у подъезда. Разорви связку — встань, выйди из комнаты, умой лицо холодной водой, выпей стакан воды залпом. Тело удивится, и тяга на секунду потеряет нить.',
      '4. Займи руки и рот. Сигарета — это ведь не только никотин, это ещё и ритуал «рука-рот», который повторялся тысячи раз. Дай этому ритуалу замену: орех, мятную жвачку, кубик льда, эспандер, ручку повертеть. Это не «детский сад» и не несерьёзно — это конкретный способ разорвать привычный жест.',
      '5. Если совсем накрыло — не геройствуй в одиночку. Открой SOS в приложении, отвлекись на быструю игру, напиши кому-нибудь, выйди на короткую прогулку. Подойдёт что угодно, что займёт голову на пару минут.',
      'А теперь главное: через 5 минут вернись и проверь себя. Почти наверняка волна уже спала — стала тише, отступила, отпустила. Ты только что прожил тягу и не закурил. Запомни это ощущение: именно так выглядит победа, и она будет повторяться.',
    ],
    bodyEn: [
      'If you opened this article right now because a craving hit — good that you did. That is already thirty seconds won. And a craving, remember, lives only 3–5 minutes. Below is a simple plan to cover them.',
      '1. Start a timer. Right now, tell yourself: "I will not smoke for the next 5 minutes." Not "never", not "for the rest of my life" — that is too vast, the brain cannot hold it. Just 5 minutes. That is doable. Anyone can manage that.',
      '2. Breathe. It sounds trivial, but it works on a physiological level: a long exhale, twice as long as the inhale, switches the nervous system into a calm mode in about a minute. Open the breathing practice in the app, or just do 10 slow exhales, counting silently. Inhale for 4 — exhale for 8.',
      '3. Change your setting. A craving is firmly tied to place and posture: that chair, that window, that corner by the door. Break the link — stand up, leave the room, splash cold water on your face, drink a glass of water in one go. The body will be surprised, and the craving loses its thread for a second.',
      '4. Occupy hands and mouth. A cigarette is not only nicotine — it is also the hand-to-mouth ritual repeated thousands of times. Give that ritual a substitute: a nut, mint gum, an ice cube, a hand gripper, a pen to fidget with. This is not childish or unserious — it is a concrete way to break the familiar gesture.',
      '5. If it really overwhelms you — do not tough it out alone. Open SOS in the app, distract yourself with a quick game, text someone, step out for a short walk. Anything that occupies your mind for a couple of minutes will do.',
      'And now the main thing: after 5 minutes, come back and check yourself. Almost certainly the wave has passed — gone quieter, receded, let go. You have just lived through a craving without smoking. Remember this feeling: this is what a win looks like, and it will keep happening.',
    ],
    takeawayRu: 'Не «бросить навсегда», а «не курить 5 минут». Дыши, двигайся, займи руки — волна спадёт.',
    takeawayEn: 'Not "quit forever" — just "do not smoke for 5 minutes". Breathe, move, occupy your hands.',
  },
  {
    id: 'craving-day3', category: 'craving', icon: 'flame', color: '#FF9500', readMin: 3,
    titleRu: 'Почему 3-й день самый трудный', titleEn: 'Why day 3 is the hardest',
    leadRu: 'И почему это хорошая новость.',
    leadEn: 'And why that is good news.',
    bodyRu: [
      'Если ты на втором или третьем дне без сигарет и тебе кажется, что ты сходишь с ума, — остановись на секунду. Ты не сходишь с ума. Ты ровно по графику. То, что ты сейчас чувствуешь, чувствуют почти все, и этому есть точное объяснение.',
      'Никотин уходит с рецепторов мозга примерно за 72 часа. Всё это время мозг, привыкший получать дозу каждый час, недоумённо требует своё. Именно поэтому на 2–4 день симптомы отмены достигают пика: раздражительность по пустякам, тревога без причины, рваный сон, сильная тяга, ощущение «не в своей тарелке».',
      'И вот тут — главная ловушка момента. Кажется, что раз так плохо уже сейчас, то дальше будет только хуже, и впереди недели такого ада. Это неправда. Всё наоборот.',
      'Пик — это не начало подъёма в гору. Пик — это вершина. Поворотная точка. После 3-го дня физическая зависимость резко слабеет, просто потому что никотина в теле уже почти не осталось — нечему больше требовать дозу. Дальше идёт спуск.',
      'Подумай об этом так: если ты дошёл до 3-го дня, значит, самое тяжёлое происходит с тобой прямо сейчас, в эту минуту, — а не где-то впереди. Худшее не «надвигается». Худшее ты уже проходишь. И это не повод сдаться — это повод стиснуть зубы ещё на чуть-чуть, потому что обиднее всего сорваться именно на вершине.',
      'Чтобы пройти эти дни мягче, помоги телу. Больше сна — отмена выматывает, и это нормально. Меньше кофе и алкоголя — они подстёгивают тягу. Лёгкая физическая нагрузка — даже короткая прогулка сбивает напряжение. Простая еда и побольше воды. Не грузи себя в эти дни сложными задачами, если есть возможность их отложить.',
      'И запомни: симптомы отмены — это не новая норма, это временная буря. Через неделю их почти не будет. То, что сейчас ощущается как «я так не выдержу», через семь дней станет фразой «а ведь уже почти отпустило».',
    ],
    bodyEn: [
      'If you are on day two or three without cigarettes and feel like you are losing your mind — stop for a second. You are not losing your mind. You are exactly on schedule. What you feel right now is felt by almost everyone, and there is a precise explanation for it.',
      'Nicotine clears the brain receptors in about 72 hours. All that time the brain, used to a dose every hour, keeps demanding its share in confusion. That is why on days 2–4 withdrawal symptoms peak: irritability over trifles, anxiety with no cause, broken sleep, strong cravings, a general "off" feeling.',
      'And here is the main trap of the moment. It feels like, since it is already this bad, it will only get worse, with weeks of this hell ahead. That is not true. The opposite is the case.',
      'The peak is not the start of a climb up a mountain. The peak is the summit. The turning point. After day 3 the physical dependence drops sharply, simply because there is almost no nicotine left in the body — nothing left to demand a dose. From here it is the descent.',
      'Think of it this way: if you have reached day 3, then the hardest part is happening to you right now, this very minute — not somewhere ahead. The worst is not "approaching". The worst is what you are already going through. And that is not a reason to give up — it is a reason to grit your teeth a little longer, because slipping right at the summit would be the most heartbreaking timing of all.',
      'To get through these days more gently, help your body. More sleep — withdrawal is exhausting, and that is normal. Less coffee and alcohol — they fuel cravings. Light exercise — even a short walk knocks down the tension. Simple food and plenty of water. Do not load yourself with hard tasks these days if you can postpone them.',
      'And remember: withdrawal symptoms are not a new normal, they are a temporary storm. In a week they will be almost gone. What now feels like "I cannot stand this" will, in seven days, become "it has almost let go already".',
    ],
    takeawayRu: 'Пик отмены — 2–4 день. Это значит: дальше будет легче, а не тяжелее.',
    takeawayEn: 'Withdrawal peaks on days 2–4. It means it gets easier from here, not harder.',
  },
  {
    id: 'craving-halt', category: 'craving', icon: 'pulse', color: '#FF9500', readMin: 3,
    titleRu: 'HALT: проверь 4 нужды', titleEn: 'HALT: check 4 needs',
    leadRu: 'Часто тебе нужен не никотин, а что-то другое.',
    leadEn: 'Often you need something other than nicotine.',
    bodyRu: [
      'Бывает так: вроде день идёт нормально, и вдруг — резко, сильно — тянет закурить. Будто на ровном месте. Но на ровном месте тяга почти не приходит. Если присмотреться, под ней почти всегда лежит что-то ещё. И есть простой способ это «что-то» поймать.',
      'Он называется HALT — по первым буквам четырёх английских слов. Это четыре состояния, в которых тяга резко усиливается: Hungry — голоден, Angry — зол или раздражён, Lonely — одинок, Tired — устал. Зависимость хитрая: она пользуется любой из этих дыр, чтобы протолкнуть мысль о сигарете.',
      'Поэтому в момент, когда хочется закурить, не хватайся сразу за пачку. Сделай паузу на десять секунд и спокойно пройдись по списку, по очереди: я голоден? я злюсь или чем-то раздражён? мне одиноко? я устал? Очень часто ответ «да» найдётся в одном из четырёх пунктов — и вот она, настоящая причина. Сигарета её просто маскировала.',
      'Смотри, как это выглядит в жизни. Ты не обедал с утра, к пяти часам сахар в крови упал — и ты «вдруг» захотел курить. На самом деле ты захотел есть. Или совещание вывело из себя, внутри всё кипит — рука сама тянется к сигарете, потому что курение годами было способом «спустить пар».',
      'И вот что важно понять: ни одну из этих четырёх нужд сигарета на самом деле не закрывает. Голоден — поешь нормально, а не «заешь» голод дымом. Зол — выпусти эмоцию по-настоящему: подвигайся, быстро пройдись, напиши всё, что думаешь, проговори вслух. Одинок — напиши близкому человеку, позвони, не сиди один. Устал — дай себе отдохнуть или поспать, хотя бы двадцать минут.',
      'Сигарета не кормит, не успокаивает злость, не лечит одиночество и не даёт отдыха. Она лишь на несколько минут приглушает сигнал тела — а потом сигнал возвращается, и нужда никуда не делась, только добавилась доза никотина.',
      'Поэтому HALT — это не просто аббревиатура, это рабочая привычка. Закрой настоящую потребность — поешь, остынь, поговори, отдохни — и обнаружишь, что тяга часто растворяется сама, без всякой борьбы. Ты дал телу то, что ему было нужно на самом деле.',
    ],
    bodyEn: [
      'It happens like this: the day seems to be going fine, and suddenly — sharply, strongly — you want to smoke. As if out of nowhere. But a craving almost never comes out of nowhere. Look closer, and there is almost always something else underneath it. And there is a simple way to catch that "something".',
      'It is called HALT — from the first letters of four words. These are four states in which cravings spike sharply: Hungry, Angry, Lonely, Tired. The dependence is cunning: it uses any of these gaps to push the thought of a cigarette through.',
      'So the moment you want to smoke, do not reach straight for the pack. Pause for ten seconds and calmly run through the list, one by one: am I hungry? am I angry or irritated? am I lonely? am I tired? Very often a "yes" turns up in one of the four — and there it is, the real cause. The cigarette was simply masking it.',
      'Here is how it looks in life. You skipped lunch, by five o\'clock your blood sugar dropped — and you "suddenly" wanted to smoke. In fact you wanted to eat. Or a meeting got you worked up, everything is boiling inside — your hand reaches for a cigarette, because smoking was for years your way to "let off steam".',
      'And here is the key thing to grasp: a cigarette does not actually meet any of those four needs. Hungry — eat properly, do not "smother" hunger with smoke. Angry — release the emotion for real: move, walk fast, write down everything you think, say it out loud. Lonely — text someone close, call them, do not sit alone. Tired — let yourself rest or sleep, even twenty minutes.',
      'A cigarette does not feed you, does not calm anger, does not cure loneliness and gives no rest. It only mutes the body signal for a few minutes — and then the signal returns, the need is still there, only now with an added dose of nicotine.',
      'So HALT is not just an acronym, it is a working habit. Meet the real need — eat, cool down, talk, rest — and you will find the craving often dissolves on its own, with no fight at all. You gave the body what it actually needed.',
    ],
    takeawayRu: 'Голоден, зол, одинок, устал? Закрой настоящую нужду — и тяга часто уходит сама.',
    takeawayEn: 'Hungry, angry, lonely, tired? Meet the real need and the craving often fades on its own.',
  },
  {
    id: 'slip-not-fail', category: 'slip', icon: 'feather', color: '#5AC8FA', readMin: 3,
    titleRu: 'Срыв — это не провал', titleEn: 'A slip is not a failure',
    leadRu: 'Почти все, кто бросил насовсем, срывались по пути.',
    leadEn: 'Almost everyone who quit for good slipped along the way.',
    bodyRu: [
      'Если ты сорвался и читаешь это с тяжёлым чувством — давай сразу, без предисловий: срыв не означает, что «всё пропало». И ты не «всё испортил». Это просто часть процесса, через который проходят почти все.',
      'Вот что показывают исследования: большинству людей нужно несколько попыток, прежде чем бросить окончательно. Не одна, идеальная, с первого раза — а несколько. Это не признак слабости и не твоя личная неудача. Это статистика, обычный путь, по которому шли миллионы бросивших.',
      'Подумай вот о чём. Разница между человеком, который в итоге бросил, и человеком, который вернулся к пачке в день, — вовсе не в том, что первый ни разу не споткнулся. Споткнулись оба. Разница только в том, что они сделали сразу после.',
      'Один человек закурил сигарету и сказал себе: «ну всё, я провалился, нет смысла, я слабак» — и эта мысль потянула за собой вторую сигарету, третью, пачку. Другой закурил ровно такую же сигарету и сказал: «окей, это просто данные — где я оступился и почему» — и пошёл дальше. Сигарета у обоих была одна и та же. Разошлись они в реакции.',
      'И ещё важное, про цифры. Одна сигарета не отменяет, скажем, 14 дней без курения. Твоё тело всё равно очищалось все эти две недели — кровь, лёгкие, сосуды реально восстанавливались. Этого у тебя никто не отнимет. Именно поэтому счётчик в приложении намеренно не обнуляется до нуля от одной сигареты: прогресс действительно есть, и он реальный.',
      'После срыва опасна не первая сигарета — она уже случилась, её не вернёшь. Опасна вторая. Именно она превращает разовый эпизод в возврат к курению.',
      'Поэтому сделай ровно одно: не тяни. Сразу спокойно разбери — что было триггером? что застало врасплох? что в следующий раз попробуешь сделать иначе? — и вернись на путь. Не завтра, не «с понедельника» — сейчас. Чем быстрее вернёшься, тем меньше этот срыв вообще значит. Через месяц он будет просто строчкой в истории, а не концом истории.',
    ],
    bodyEn: [
      'If you slipped and are reading this with a heavy feeling — let us say it straight, no preamble: a slip does not mean "everything is lost". And you did not "ruin everything". It is simply part of the process almost everyone goes through.',
      'Here is what research shows: most people need several attempts before quitting for good. Not one perfect attempt on the first try — several. That is not a sign of weakness or your personal failure. It is statistics, the ordinary path that millions of quitters walked.',
      'Think about this. The difference between someone who eventually quit and someone who went back to a pack a day is not that the first never stumbled. Both stumbled. The difference is only in what they did right afterwards.',
      'One person smoked a cigarette and told themselves: "that is it, I failed, no point, I am weak" — and that thought dragged a second cigarette behind it, a third, a pack. The other smoked exactly the same cigarette and said: "okay, this is just data — where did I trip and why" — and carried on. The cigarette was identical for both. They parted ways in the reaction.',
      'And another important point, about the numbers. One cigarette does not cancel, say, 14 smoke-free days. Your body still healed across those two weeks — blood, lungs, vessels really did recover. No one can take that from you. That is exactly why the counter in the app deliberately does not reset to zero from a single cigarette: the progress is real.',
      'After a slip the danger is not the first cigarette — it has already happened, you cannot undo it. The danger is the second. That is what turns a one-off episode into a return to smoking.',
      'So do exactly one thing: do not delay. Calmly review right away — what was the trigger? what caught you off guard? what will you try differently next time? — and return to the path. Not tomorrow, not "from Monday" — now. The faster you return, the less this slip means at all. In a month it will be just a line in the story, not the end of it.',
    ],
    takeawayRu: 'Срыв ≠ провал. Опасна не первая сигарета, а вторая. Разбери триггер и вернись.',
    takeawayEn: 'A slip is not a failure. The danger is not the first cigarette but the second. Review and return.',
  },
  {
    id: 'slip-ave', category: 'slip', icon: 'brain', color: '#5AC8FA', readMin: 3,
    titleRu: 'Эффект «раз сорвался — гори всё»', titleEn: 'The "I blew it" effect',
    leadRu: 'Самая опасная мысль после срыва — и как её обезвредить.',
    leadEn: 'The most dangerous thought after a slip — and how to defuse it.',
    bodyRu: [
      'После срыва в голове почти всегда щёлкает одна и та же мысль: «всё, я сорвался, я слабак, день потерян — какая теперь разница, можно курить дальше». Если ты её узнаёшь — ты не один. Это настолько типичная штука, что у неё есть научное название: эффект нарушения воздержания, по-английски AVE.',
      'И вот в чём ключевой момент, который стоит понять раз и навсегда: именно эта мысль, а не сама сигарета, превращает разовый срыв в полный возврат к курению.',
      'Посчитай буквально. Одна сигарета — это одна сигарета. Один эпизод. Небольшой откат, который легко наверстать. А вот пачка, выкуренная за вечер, — это уже не «срыв», это работа AVE. Это та самая мысль «гори всё», доведённая до логического конца. Вред нанесла не первая сигарета, а разрешение, которое ты сам себе выдал после неё.',
      'Хорошая новость: эту мысль можно обезвредить. Способ называется переатрибуция — если проще, смена объяснения. Сравни две формулировки одного и того же срыва.',
      'Первая: «я сорвался, потому что я слабый и безвольный». Это объяснение внутреннее (дело во мне самом), постоянное (я такой всегда) и глобальное (это про всю мою личность). Из него нет выхода — оно просто бьёт по самооценке и оставляет в яме.',
      'Вторая: «я сорвался, потому что попал в сильный триггер — выпил на дне рождения, рядом курили — и не подготовил план на эту ситуацию». Это объяснение внешнее, конкретное и, главное, исправимое. Причина не в том, что ты «такой», а в том, что конкретная ситуация застала врасплох.',
      'Разница не в словах — разница в том, что из второй формулировки есть конкретное действие: продумать, как вести себя на следующем дне рождения. Из первой действия нет вообще, только чувство вины. Поэтому правило простое: после срыва осознанно выбирай ту формулировку, из которой ведёт дверь, а не ту, что просто запирает тебя внутри.',
    ],
    bodyEn: [
      'After a slip, almost always the same thought clicks in your head: "that is it, I slipped, I am weak, the day is lost — what difference does it make now, I might as well keep smoking". If you recognise it — you are not alone. It is so typical it has a scientific name: the Abstinence Violation Effect, or AVE.',
      'And here is the key point worth understanding once and for all: it is this thought, not the cigarette itself, that turns a one-off slip into a full relapse.',
      'Count it literally. One cigarette is one cigarette. A single episode. A small setback that is easy to make up. But a pack smoked in an evening is no longer a "slip" — it is AVE at work. It is that very "I blew it" thought taken to its logical end. The harm was done not by the first cigarette but by the permission you handed yourself after it.',
      'Good news: this thought can be defused. The method is called reattribution — put simply, changing the explanation. Compare two framings of the very same slip.',
      'The first: "I slipped because I am weak and have no willpower". This explanation is internal (it is about me), permanent (I am always like this) and global (it is about my whole personality). There is no way out of it — it just hits your self-esteem and leaves you in the pit.',
      'The second: "I slipped because I hit a strong trigger — I drank at a birthday party, people around were smoking — and I had no plan for that situation". This explanation is external, specific and, crucially, fixable. The cause is not that you "are like that", but that a particular situation caught you off guard.',
      'The difference is not in the words — it is that the second framing leads to a concrete action: thinking through how to handle the next birthday party. The first leads to no action at all, only guilt. So the rule is simple: after a slip, consciously choose the framing that has a door out, not the one that just locks you inside.',
    ],
    takeawayRu: 'Срыв в рецидив превращает мысль «гори всё», а не сигарета. Причина — триггер, а не «я слабак».',
    takeawayEn: 'It is the "I blew it" thought, not the cigarette, that causes relapse. The cause is a trigger, not weakness.',
  },
  {
    id: 'trig-coffee', category: 'triggers', icon: 'drop', color: '#BF5AF2', readMin: 3,
    titleRu: 'Кофе и сигарета: разорвать связку', titleEn: 'Coffee and cigarette: break the link',
    leadRu: 'Почему утренний кофе так тянет закурить.',
    leadEn: 'Why morning coffee makes you want to smoke.',
    bodyRu: [
      'Утро. Ты наливаешь чашку кофе — и рука почти сама тянется к сигарете. Без раздумий, без особой тяги, просто потому что «так положено». Если узнаёшь себя — это очень частая история, и у неё есть понятный механизм.',
      'Дело в том, что если ты годами курил вместе с кофе, мозг прочно склеил их в одну пару. Утренняя чашка, перекур после обеда, кофе в перерыве с коллегами — десятки тысяч повторений. И в какой-то момент сам по себе вид и запах кофе стал сигналом «пора курить» — даже без всякой тяги к никотину.',
      'Это важно понять: ты не зависим от кофе и кофе тут не виноват. Это условный рефлекс — та же механика, что у собаки Павлова, у которой текла слюна на звонок. У тебя «звонок» — это кофе, а «слюна» — желание закурить.',
      'И раз это рефлекс, у новости есть отличная сторона: рефлекс можно разорвать ровно так же, как он сложился — повторением нового сценария. Не силой воли, а переучиванием.',
      'Конкретно: первые недели две сознательно меняй весь ритуал кофе. Пей его в другом месте — не на том балконе или у того окна, где курил, а, скажем, за кухонным столом. Держи чашку другой рукой. Пей чуть быстрее обычного, не растягивая. Можно сменить саму чашку. Чем меньше похоже на старый сценарий — тем слабее срабатывает рефлекс.',
      'Хорошо помогает добавить новое действие в начало: сделай 5 минут спокойного дыхания ДО первой чашки. Так ты вставляешь между кофе и сигаретой новое звено и постепенно перестраиваешь цепочку.',
      'И ещё момент про химию: кофеин слегка ускоряет вывод никотина из организма и в первые дни может сам по себе подстёгивать тягу. Поэтому в самом начале есть смысл временно уменьшить количество кофе — не навсегда, просто пока острее всего. А через 2–3 недели рефлекс ослабнет, и кофе снова станет просто кофе, который больше не тянет за собой сигарету.',
    ],
    bodyEn: [
      'Morning. You pour a cup of coffee — and your hand almost reaches for a cigarette by itself. No thinking, no particular craving, just because "that is how it is done". If you recognise yourself — this is a very common story, and it has a clear mechanism.',
      'The thing is, if you smoked together with coffee for years, the brain firmly glued them into one pair. The morning cup, the break after lunch, coffee with colleagues — tens of thousands of repetitions. And at some point the very sight and smell of coffee became a "time to smoke" signal — even without any nicotine craving.',
      'This matters to understand: you are not addicted to coffee and coffee is not to blame. It is a conditioned reflex — the same mechanics as Pavlov\'s dog, whose mouth watered at a bell. Your "bell" is coffee, and the "saliva" is the urge to smoke.',
      'And since it is a reflex, the news has a great side: a reflex can be broken exactly the way it formed — by repeating a new script. Not with willpower, but with retraining.',
      'Concretely: for the first couple of weeks, deliberately change the whole coffee ritual. Drink it in a different place — not on that balcony or by that window where you smoked, but, say, at the kitchen table. Hold the cup with the other hand. Drink a little faster than usual, without dragging it out. You can even switch the mug itself. The less it resembles the old script — the weaker the reflex fires.',
      'It helps to add a new action at the start: do 5 minutes of calm breathing BEFORE the first cup. That way you insert a new link between coffee and cigarette and gradually rewire the chain.',
      'And one more point about chemistry: caffeine slightly speeds the clearance of nicotine and in the first days can fuel cravings on its own. So at the very start it makes sense to cut coffee temporarily — not forever, just while it is sharpest. And after 2–3 weeks the reflex weakens, and coffee becomes just coffee again, no longer pulling a cigarette with it.',
    ],
    takeawayRu: 'Кофе тянет курить из-за рефлекса. Меняй ритуал кофе 2 недели — связка распадётся.',
    takeawayEn: 'Coffee triggers smoking via a reflex. Change the coffee ritual for 2 weeks and the link breaks.',
  },
  {
    id: 'trig-alcohol', category: 'triggers', icon: 'drop2', color: '#BF5AF2', readMin: 3,
    titleRu: 'Алкоголь — главная ловушка', titleEn: 'Alcohol is the main trap',
    leadRu: 'Самая частая причина срыва — вечер с выпивкой.',
    leadEn: 'The most common cause of a slip — an evening with drinks.',
    bodyRu: [
      'Если посмотреть, где люди срываются чаще всего, картина почти всегда одна и та же: пятница, компания, бокал, второй — и вот уже «да ладно, одну можно». Алкоголь — триггер номер один для срывов, и это не случайность. Тут работают сразу три механизма, и работают они вместе, усиливая друг друга.',
      'Первое и главное — алкоголь напрямую снижает самоконтроль. Префронтальная кора, та часть мозга, что отвечает за здравое «не надо, ты же бросаешь», отключается одной из первых, ещё до того как ты почувствуешь себя по-настоящему пьяным. Поэтому решение «всего одну, ничего не будет» принимается так легко — не потому что ты слабый, а потому что в этот момент твой внутренний тормоз буквально выключен химией.',
      'Второе — связка, ровно как с кофе. Если ты годами курил в барах, на вечеринках, за разговором с бокалом, то сама эта обстановка — гомон, музыка, рюмка в руке — для мозга мощный сигнал «время курить». Тяга приходит не от никотина, а от декораций.',
      'Третье — простая социальная физика: там, где пьют, чаще курят. Тебе предложат сигарету напрямую, протянут пачку, позовут «выйти подышать». И отказаться на трезвую голову куда легче, чем после третьего бокала.',
      'Вот живой пример того, как это рушится. Человек две недели держался идеально. Пошёл на день рождения, решил «расслаблюсь, я же молодец». После пары бокалов друг закурил рядом, протянул пачку — и рука сама взяла. Наутро — тяжёлое чувство и мысль «как же так, я ведь справлялся». А справлялся — пока трезвый мозг принимал решения.',
      'Что с этим делать в первые недели, пока зависимость ещё свежая. Самое надёжное — по возможности вообще избегать ситуаций с алкоголем или резко ограничить дозу. Это не навсегда, это просто защита самого хрупкого периода.',
      'А если идёшь — иди с готовым планом, придуманным заранее и трезвым. Реши конкретно, не «как-нибудь разберусь на месте»: что именно ответишь, если предложат сигарету; будешь ли выходить на улицу с курящими или останешься внутри; во сколько уйдёшь домой. План, составленный трезвой головой, — это и есть тот тормоз, который алкоголь потом отключит. Ты как будто оставляешь себе записку от более разумной версии себя.',
    ],
    bodyEn: [
      'Look at where people slip most often, and the picture is almost always the same: Friday, company, one glass, a second — and already "come on, one is fine". Alcohol is the number one trigger for slips, and that is no accident. Three mechanisms work here at once, and they work together, reinforcing each other.',
      'First and foremost — alcohol directly lowers self-control. The prefrontal cortex, the part responsible for the sensible "do not, you are quitting", is one of the first to switch off, even before you feel truly drunk. That is why the decision "just one, nothing will happen" comes so easily — not because you are weak, but because at that moment your inner brake is literally switched off by chemistry.',
      'Second — the link, exactly as with coffee. If you smoked for years in bars, at parties, in conversation with a glass, then that very setting — the noise, the music, a drink in hand — is a powerful "time to smoke" signal for the brain. The craving comes not from nicotine but from the scenery.',
      'Third — simple social physics: where people drink, they smoke more. Someone will offer you a cigarette directly, hold out the pack, call you to "step out for air". And refusing with a clear head is far easier than after the third glass.',
      'Here is a vivid example of how it falls apart. A person held on perfectly for two weeks. Went to a birthday party, decided "I will relax, I have earned it". After a couple of glasses a friend lit up nearby, held out the pack — and the hand took it on its own. In the morning — a heavy feeling and the thought "how could this happen, I was managing". They were managing — while a sober brain was making the decisions.',
      'What to do about it in the first weeks, while the dependence is still fresh. The most reliable thing is to avoid alcohol situations entirely where possible, or sharply limit the dose. This is not forever — it is just protection for the most fragile period.',
      'And if you go — go with a ready plan, made in advance and sober. Decide concretely, not "I will figure it out on the spot": what exactly you will say if offered a cigarette; whether you will step outside with smokers or stay in; what time you will leave. A plan made by a sober mind is the very brake that alcohol will later switch off. It is like leaving yourself a note from a wiser version of yourself.',
    ],
    takeawayRu: 'Алкоголь снимает самоконтроль — отсюда срывы. Первые недели ограничь его и иди с планом.',
    takeawayEn: 'Alcohol removes self-control — hence slips. Limit it in the first weeks and go in with a plan.',
  },
  {
    id: 'trig-stress', category: 'triggers', icon: 'brain', color: '#BF5AF2', readMin: 3,
    titleRu: 'Никотин не снимает стресс', titleEn: 'Nicotine does not relieve stress',
    leadRu: 'Главный миф, который держит людей на сигарете.',
    leadEn: 'The main myth that keeps people smoking.',
    bodyRu: [
      '«Я курю, потому что это меня успокаивает». Если есть одна фраза, которая держит людей на сигарете крепче всего, — то это она. И именно она, при ближайшем рассмотрении, оказывается неправдой. Причём очень коварной неправдой.',
      'Начнём с факта, который многих удивляет: курильщик в среднем живёт с более высоким базовым уровнем стресса и тревоги, чем некурящий. Не с меньшим — с большим. То есть сигарета не делает жизнь спокойнее, она делает её тревожнее. Как же тогда возникает ощущение, что она «помогает»?',
      'Вот как это устроено, шаг за шагом. Ты выкурил сигарету. Проходит час, полтора — и уровень никотина в крови падает. Начинается лёгкая, почти незаметная отмена: нарастает раздражительность, внутреннее напряжение, лёгкое беспокойство. Ты можешь даже не связывать это с курением — просто «что-то нервничаю».',
      'Потом ты закуриваешь снова. И напряжение спадает. Мозг радостно фиксирует: «сигарета меня успокоила». Но смотри внимательно — что именно она сняла? Не стресс от работы, не ссору, не дедлайн. Она сняла ту самую отмену никотина, которая возникла только потому, что ты куришь.',
      'Получается замкнутый круг. Сигарета создаёт небольшой стресс отмены — а следующая сигарета его снимает — и это снятие ты принимаешь за «расслабление». Курильщик не лечит стресс жизни. Он бесконечно лечит ломку, которую сам себе и устроил. Это как носить тесную обувь весь день только ради блаженного момента, когда её снимаешь.',
      'Представь обычную картину: тяжёлый разговор, ты выходишь покурить и чувствуешь облегчение. Но облегчение пришло не от никотина — оно пришло от того, что ты вышел из комнаты, постоял пять минут в тишине, подышал, переключился. Ровно то же самое дала бы прогулка без сигареты. Просто никотин присвоил себе чужую заслугу.',
      'И вот что говорят исследования — это, пожалуй, самое обнадёживающее. Через несколько недель после отказа базовый уровень тревоги у бросивших не растёт, а СНИЖАЕТСЯ. Не курить — объективно спокойнее, чем курить. Просто эффект виден не сразу: первые дни отмена шумит и маскирует правду, а вот дальше открывается тишина, которой у тебя не было годами.',
    ],
    bodyEn: [
      '"I smoke because it calms me down." If there is one phrase that keeps people on cigarettes most firmly — it is this one. And it is precisely this one that, on closer inspection, turns out to be false. A very treacherous kind of false.',
      'Let us start with a fact that surprises many: a smoker, on average, lives with a higher baseline level of stress and anxiety than a non-smoker. Not lower — higher. So a cigarette does not make life calmer, it makes it more anxious. How then does the feeling that it "helps" arise?',
      'Here is how it works, step by step. You smoked a cigarette. An hour, an hour and a half pass — and the nicotine level in your blood drops. A mild, almost unnoticeable withdrawal begins: irritability rises, inner tension, a slight unease. You might not even connect it to smoking — just "feeling a bit on edge".',
      'Then you light up again. And the tension fades. The brain happily records: "the cigarette calmed me". But look closely — what exactly did it relieve? Not work stress, not the argument, not the deadline. It relieved that same nicotine withdrawal, which arose only because you smoke.',
      'The result is a closed loop. A cigarette creates a small withdrawal stress — the next cigarette relieves it — and that relief you mistake for "relaxation". A smoker does not treat life stress. They endlessly treat a withdrawal they inflicted on themselves. It is like wearing tight shoes all day just for the blissful moment of taking them off.',
      'Picture an ordinary scene: a hard conversation, you step out for a smoke and feel relief. But the relief did not come from nicotine — it came from leaving the room, standing five minutes in quiet, breathing, switching off. A walk without a cigarette would have given exactly the same. Nicotine simply took credit for someone else\'s work.',
      'And here is what studies say — perhaps the most reassuring part. A few weeks after quitting, baseline anxiety in quitters does not rise but goes DOWN. Not smoking is objectively calmer than smoking. The effect just is not visible right away: in the first days withdrawal makes noise and masks the truth, but after that a quiet opens up that you have not had for years.',
    ],
    takeawayRu: 'Сигарета снимает не стресс, а свою же отмену. Через недели без неё тревоги становится меньше.',
    takeawayEn: 'A cigarette relieves its own withdrawal, not stress. Weeks later, baseline anxiety is lower.',
  },
  {
    id: 'body-timeline', category: 'body', icon: 'heart', color: '#FF453A', readMin: 4,
    titleRu: 'Что происходит с телом по дням', titleEn: 'What happens to your body, day by day',
    leadRu: 'Восстановление начинается через 20 минут.',
    leadEn: 'Recovery starts within 20 minutes.',
    bodyRu: [
      'Вот что важно почувствовать в самом начале пути: тело не ждёт «подходящего момента», чтобы начать восстанавливаться. Оно берётся за дело почти сразу после твоей последней сигареты — и дальше уже не останавливается. Пока ты читаешь это, ремонт уже идёт.',
      'Через 20 минут после последней сигареты пульс и артериальное давление, подстёгнутые никотином, начинают приходить в норму. Сердцу уже немного легче.',
      'Через 8–12 часов уровень угарного газа в крови падает примерно вдвое. Это тот самый газ из дыма, который занимал в крови место кислорода. Теперь кислород возвращается — и его получают мышцы, мозг, каждая ткань. Многие именно в этот момент впервые замечают, что дышится чуть свободнее.',
      'Через 2 суток никотин полностью выведен из организма — физическая зависимость от вещества, по сути, уже позади. И как приятный бонус начинают оживать притупленные курением вкус и обоняние: еда становится ярче, запахи — отчётливее. Это удивляет почти каждого бросившего.',
      'Через 3 суток расслабляются бронхи, дышать становится заметно легче. А дальше, на отрезке от 2 до 12 недель, по-настоящему улучшается кровообращение и растёт функция лёгких — подняться по лестнице или пройтись быстрым шагом уже не так тяжело, как раньше.',
      'На дистанции от 1 до 9 месяцев постепенно уходит знакомый кашель курильщика. В лёгких восстанавливается реснитчатый эпителий — крошечные «реснички», которые выметают из лёгких слизь и грязь. У курильщика они были парализованы, теперь они снова работают и чистят тебя изнутри.',
      'А на горизонте лет без курения цифры становятся по-настоящему весомыми: риск инфаркта, инсульта и рака лёгких снижается в разы. Тело отыгрывает назад годы вреда.',
      'Запомни из этого одно. Каждый прожитый без сигарет день — это не просто «сегодня я не навредил себе». Это день активного, реального восстановления, которое происходит в твоём теле прямо сейчас, без твоих усилий. Ты уже не разрушаешь — ты чинишь. И счётчик дней в приложении показывает именно это.',
    ],
    bodyEn: [
      'Here is what matters to feel at the very start of the journey: the body does not wait for the "right moment" to begin recovering. It gets to work almost immediately after your last cigarette — and from then on it does not stop. As you read this, the repair is already under way.',
      '20 minutes after the last cigarette, heart rate and blood pressure, spurred by nicotine, begin to return to normal. The heart already has it a little easier.',
      'After 8–12 hours the carbon monoxide level in the blood drops by about half. That is the gas from smoke that took the place of oxygen in your blood. Now oxygen returns — and reaches the muscles, the brain, every tissue. Many people notice for the first time at this point that breathing feels a bit freer.',
      'After 2 days nicotine is fully cleared from the body — the physical dependence on the substance is, in essence, already behind you. And as a pleasant bonus, the taste and smell dulled by smoking start to come alive: food gets brighter, smells sharper. This surprises almost every quitter.',
      'After 3 days the bronchi relax and breathing becomes noticeably easier. And further on, over the stretch from 2 to 12 weeks, circulation genuinely improves and lung function grows — climbing stairs or walking briskly is no longer as hard as before.',
      'Over the span from 1 to 9 months the familiar smoker\'s cough gradually fades. The lung cilia regenerate — the tiny "hairs" that sweep mucus and dirt out of the lungs. In a smoker they were paralysed; now they work again and clean you from the inside.',
      'And on the horizon of years smoke-free the numbers become truly weighty: the risk of heart attack, stroke and lung cancer drops several-fold. The body wins back years of damage.',
      'Take one thing from this. Every smoke-free day is not just "today I did not harm myself". It is a day of active, real recovery happening in your body right now, without your effort. You are no longer destroying — you are repairing. And the day counter in the app shows exactly that.',
    ],
    takeawayRu: 'Восстановление идёт уже с 20-й минуты. Каждый день без сигарет тело реально чинит себя.',
    takeawayEn: 'Recovery begins at minute 20. Every smoke-free day, your body is actively repairing itself.',
  },
  {
    id: 'body-weight', category: 'body', icon: 'leaf', color: '#FF453A', readMin: 3,
    titleRu: 'Прибавка в весе — правда?', titleEn: 'Weight gain — is it true?',
    leadRu: 'Что реально происходит и что с этим делать.',
    leadEn: 'What really happens and what to do about it.',
    bodyRu: [
      '«А правда, что если бросить, то растолстеешь?» Этот страх останавливает очень многих, особенно если человек и так следит за весом. Поэтому давай честно и по порядку — что тут правда, а что преувеличение.',
      'Правда вот в чём: да, часть людей после отказа действительно немного набирает вес — в среднем 2–4 кг за первые месяцы. Ключевые слова — «часть» и «немного». Это не происходит со всеми, это не неизбежно, и это точно не тот масштаб, ради которого стоит и дальше травить себя дымом.',
      'Откуда вообще берутся эти килограммы — причин две. Первая чисто физиологическая: никотин слегка подстёгивал обмен веществ и приглушал аппетит. Без него тело просто возвращается к своей нормальной, естественной скорости — той, что была до курения. Вторая причина поведенческая: рука по привычке ищет ритуал «рука-рот», и его место часто занимает еда, особенно сладкое. Перекус становится новым способом «занять» тягу.',
      'Хорошая новость — на обе причины можно мягко повлиять, и без героизма. Пей больше воды, особенно когда кажется, что хочется перекусить — жажду легко перепутать с голодом. Держи под рукой не печенье и конфеты, а орехи, нарезанные овощи, жвачку: они закрывают тот самый жест «рука-рот», но без сахарной горки.',
      'Очень помогает движение. Добавь хотя бы 10–15 минут ходьбы в день — это одновременно и снижает аппетит, и сбивает тягу к сигарете, то есть бьёт сразу по двум зайцам. Не нужно изматывающих тренировок, достаточно регулярной прогулки.',
      'И одна важная оговорка: не садись на жёсткую диету одновременно с отказом от курения. Это две большие нагрузки сразу, и вместе они почти всегда заканчиваются срывом — либо по еде, либо по сигаретам. Делай по одному. Сначала спокойно закрепи отказ, и только потом, без спешки, занимайся весом.',
      'И, наконец, главное — в цифрах, чтобы расставить всё по местам. Вред от 2–4 лишних килограммов несопоставимо, в десятки раз меньше вреда от курения. Чтобы по риску для сердца сравняться с курильщиком, человеку пришлось бы набрать порядка 35–40 кг — то есть в десять раз больше. Так что приоритет очевиден: сначала бросаем курить, а вес, если он и появится, спокойно возвращаем потом. Это решаемая задача, и решать её куда легче, дыша полной грудью.',
    ],
    bodyEn: [
      '"Is it true that if you quit, you get fat?" This fear stops a great many people, especially anyone who already watches their weight. So let us be honest and take it in order — what is true here and what is exaggerated.',
      'Here is the truth: yes, some people do gain a little weight after quitting — on average 2–4 kg in the first months. The key words are "some" and "a little". It does not happen to everyone, it is not inevitable, and it is certainly not the kind of scale worth poisoning yourself with smoke over.',
      'Where do these kilograms even come from — there are two reasons. The first is purely physiological: nicotine slightly spurred the metabolism and dulled appetite. Without it the body simply returns to its normal, natural pace — the one it had before smoking. The second reason is behavioural: the hand keeps looking for the hand-to-mouth ritual out of habit, and food, especially sweets, often takes its place. A snack becomes a new way to "occupy" a craving.',
      'The good news is that both causes can be gently managed, with no heroics. Drink more water, especially when you feel like snacking — thirst is easy to mistake for hunger. Keep nuts, cut vegetables and gum at hand instead of cookies and sweets: they cover that same hand-to-mouth gesture, but without the sugar pile.',
      'Movement helps a lot. Add at least 10–15 minutes of walking a day — it both lowers appetite and knocks down the craving for a cigarette, hitting two targets at once. No exhausting workouts needed, a regular walk is enough.',
      'And one important caveat: do not start a strict diet at the same time as quitting smoking. These are two big loads at once, and together they almost always end in a slip — either on food or on cigarettes. Do one at a time. First calmly lock in the quit, and only then, without rushing, deal with weight.',
      'And finally, the main thing — in numbers, to put it all in place. The harm from 2–4 extra kilograms is incomparably, tens of times smaller than the harm from smoking. To match a smoker\'s heart risk, a person would have to gain around 35–40 kg — ten times more. So the priority is obvious: first quit smoking, and the weight, if it appears at all, you calmly address later. It is a solvable task, and far easier to solve while breathing freely.',
    ],
    takeawayRu: 'Возможны 2–4 кг — это поправимо и в разы безопаснее курения. Сначала бросаем.',
    takeawayEn: '2–4 kg is possible — fixable and far safer than smoking. Quit first, address weight later.',
  },
  {
    id: 'body-vape', category: 'body', icon: 'wind', color: '#FF453A', readMin: 3,
    titleRu: 'Вейп бросить не легче', titleEn: 'Vaping is not easier to quit',
    leadRu: 'Почему «перешёл на вейп» — часто не выход.',
    leadEn: 'Why "switched to vaping" is often not a solution.',
    bodyRu: [
      '«Я бросил сигареты, перешёл на вейп» — звучит как победа. И многие искренне считают это шагом вперёд. Но если речь о никотиновой зависимости, то чаще всего человек не вышел из неё, а просто сменил упаковку.',
      'Вейп действительно ощущается мягче: нет едкого дыма, нет запаха, пар кажется почти безобидным. Но зависимость он создаёт ту же самую — никотиновую. А по факту нередко даже более крепкую, чем от сигарет. И вот почему.',
      'Всё дело в дозе и доступности. У сигарет, как ни странно, есть встроенные тормоза. Пачка заканчивается — надо идти покупать. На улице дождь и холод — лишний раз не выйдешь. Докурил — окурок выброшен, эпизод закрыт. Эти естественные паузы невольно ограничивают, сколько никотина ты получаешь за день.',
      'У вейпа таких тормозов нет вообще. Затяжка занимает одну секунду и не требует ничего поджигать. Устройство всегда лежит в кармане или на столе под рукой. А крепость жидкости часто заметно выше, чем человеку кажется — солевой никотин бьёт мягко на вкус, и легко недооценить дозу.',
      'В итоге получается парадокс: вейпер за день нередко получает больше никотина, чем получал курильщиком. И главное — он парит «на автомате», фоном, между делом, даже не замечая и не считая затяжки. Зависимость не ушла, она стала незаметнее, а оттого ещё цепче.',
      'Поэтому хорошая новость в том, что бросать вейп нужно не «как-то иначе» — а ровно так же, как сигареты. Это та же зависимость, и работают те же инструменты: те же триггеры (кофе, стресс, алкоголь, скука), те же техники, те же волны тяги по 3–5 минут, которые проходят сами. Всё, что ты читаешь в этом приложении, применимо к вейпу один в один.',
      'Пара практичных уточнений именно для вейпа. Если решил снижать постепенно — снижай не количество затяжек, а крепость жидкости, то есть миллиграммы никотина. Считать затяжки бесполезно: рука легко начнёт парить чаще и компенсирует. И обязательно убирай устройство из зоны лёгкого доступа — не носи в кармане, не клади на стол. Раз нет встроенных пауз — создай их себе сам.',
    ],
    bodyEn: [
      '"I quit cigarettes, switched to vaping" — it sounds like a victory. And many sincerely consider it a step forward. But when it comes to nicotine dependence, most often the person has not left it — they have simply changed the packaging.',
      'Vaping really does feel milder: no acrid smoke, no smell, the vapour seems almost harmless. But it creates the very same dependence — nicotine. And in fact often an even stronger one than cigarettes. Here is why.',
      'It all comes down to dose and accessibility. Cigarettes, oddly enough, have built-in brakes. The pack runs out — you have to go buy more. It is raining and cold outside — you will not step out for an extra one. You finish — the butt is discarded, the episode closed. These natural pauses involuntarily limit how much nicotine you get per day.',
      'Vaping has no such brakes at all. A puff takes one second and requires nothing to be lit. The device is always in your pocket or on the desk within reach. And the liquid strength is often noticeably higher than the person thinks — salt nicotine hits softly on the taste, and the dose is easy to underestimate.',
      'The result is a paradox: a vaper often gets more nicotine per day than they did as a smoker. And crucially — they vape on autopilot, in the background, between things, without even noticing or counting the puffs. The dependence has not gone, it has become less visible, and therefore even more tenacious.',
      'So the good news is that quitting vaping does not need to be done "somehow differently" — it is done exactly the same way as cigarettes. It is the same dependence, and the same tools work: the same triggers (coffee, stress, alcohol, boredom), the same techniques, the same 3–5 minute craving waves that pass on their own. Everything you read in this app applies to vaping one to one.',
      'A couple of practical notes specific to vaping. If you decide to taper gradually — lower not the puff count but the liquid strength, that is, the milligrams of nicotine. Counting puffs is useless: the hand easily starts vaping more often and compensates. And be sure to move the device out of easy reach — do not carry it in your pocket, do not leave it on the desk. Since there are no built-in pauses — create them for yourself.',
    ],
    takeawayRu: 'Вейп — та же никотиновая зависимость, часто крепче. Бросают так же: триггеры, техники, волны.',
    takeawayEn: 'Vaping is the same nicotine dependence, often stronger. Quit it the same way.',
  },
  {
    id: 'meds-overview', category: 'meds', icon: 'shield', color: '#30D158', readMin: 4,
    titleRu: 'Лекарства: цитизин, бупропион, варениклин', titleEn: 'Medication: cytisine, bupropion, varenicline',
    leadRu: 'Когда таблетки помогают и как они работают.',
    leadEn: 'When pills help and how they work.',
    bodyRu: [
      'Сразу проясним одну вещь, потому что вокруг неё много стыда: использовать лекарства, чтобы бросить, — это не «жульничество» и не признак слабости. Поведенческие техники — дыхание, работа с триггерами, скольжение по тяге — отлично работают для очень многих. Но при сильной зависимости одних техник иногда не хватает, и это нормально. Тогда на помощь приходит медикаментозная поддержка: она снижает тягу и сглаживает отмену, освобождая силы на всё остальное.',
      'Коротко о трёх основных препаратах — чтобы ты понимал, о чём вообще речь, когда об этом зайдёт разговор с врачом.',
      'Цитизин (известен как Табекс) — препарат растительного происхождения, в России продаётся без рецепта. Работает он умно: мягко занимает в мозге те же никотиновые рецепторы, что и никотин. Из-за этого, во-первых, слабее ощущается тяга, а во-вторых, если человек закурит, сигарета даёт заметно меньше привычного «эффекта» — курить становится просто не так интересно. Курс короткий, около 25 дней, и сам препарат недорогой.',
      'Бупропион — рецептурный препарат, по своей основной природе антидепрессант, который вдобавок снижает тягу к никотину. Он особенно уместен, если отказ идёт на фоне сниженного настроения или подавленности — тогда он работает сразу в двух направлениях.',
      'Варениклин — препарат, который по доказательной базе считается самым эффективным из всех. Он тоже рецептурный и тоже подбирается только врачом.',
      'А теперь — самое важное, и это нужно сказать прямо. Приложение не назначает лекарства и не может этого делать. Бупропион и варениклин подбирает исключительно врач: у них есть противопоказания и возможные побочные эффекты, которые обязательно нужно сверить именно с твоей ситуацией и здоровьем. Даже безрецептурный цитизин, который можно купить самому, всё равно стоит сначала обсудить с врачом или хотя бы с фармацевтом в аптеке. Самоназначение тут — плохая идея.',
      'Зато вот в чём приложение реально полезно: когда врач уже подобрал тебе препарат, оно поможет вести расписание приёма и аккуратно напоминать о дозах. И это не мелочь. У всех этих препаратов регулярность приёма напрямую влияет на результат — пропущенные таблетки заметно снижают эффект. Так что роль приложения — быть твоим надёжным напоминанием, а роль врача — выбрать, что именно принимать.',
    ],
    bodyEn: [
      'Let us clear one thing up right away, because there is a lot of shame around it: using medication to quit is not "cheating" and not a sign of weakness. Behavioural techniques — breathing, working with triggers, urge surfing — work great for very many people. But with strong dependence, techniques alone are sometimes not enough, and that is normal. Then medication support steps in: it lowers cravings and smooths out withdrawal, freeing your energy for everything else.',
      'A brief word on the three main drugs — so you understand what is being discussed when it comes up with a doctor.',
      'Cytisine (known as Tabex) is a plant-derived drug, sold over the counter in Russia. It works cleverly: it gently occupies the same nicotine receptors in the brain that nicotine does. Because of this, first, cravings feel weaker, and second, if a person does smoke, the cigarette gives noticeably less of the usual "effect" — smoking simply becomes less interesting. The course is short, about 25 days, and the drug itself is inexpensive.',
      'Bupropion is a prescription drug, by its main nature an antidepressant, which additionally lowers the craving for nicotine. It is especially relevant if quitting happens against a background of low mood — then it works in two directions at once.',
      'Varenicline is the drug considered the most effective of all by the evidence base. It is also prescription-only and also chosen only by a doctor.',
      'And now the most important part, which needs to be said plainly. The app does not prescribe medication and cannot do so. Bupropion and varenicline are chosen exclusively by a doctor: they have contraindications and possible side effects that must be checked against your specific situation and health. Even over-the-counter cytisine, which you can buy yourself, is still worth discussing first with a doctor or at least a pharmacist. Self-prescribing here is a bad idea.',
      'But here is where the app is genuinely useful: once a doctor has chosen a drug for you, it helps you keep the dosing schedule and reminds you of doses carefully. And that is no small thing. For all of these drugs, regular dosing directly affects the result — missed pills noticeably reduce the effect. So the app\'s role is to be your reliable reminder, and the doctor\'s role is to choose what exactly to take.',
    ],
    takeawayRu: 'При сильной зависимости лекарства помогают. Бупропион и варениклин — только через врача.',
    takeawayEn: 'With strong dependence, medication helps. Bupropion and varenicline — only via a doctor.',
  },
  {
    id: 'mot-money', category: 'motivation', icon: 'sparkle', color: '#34C759', readMin: 3,
    titleRu: 'Куда уходят деньги', titleEn: 'Where the money goes',
    leadRu: 'Маленькая ежедневная сумма складывается в крупную.',
    leadEn: 'A small daily sum adds up to a large one.',
    bodyRu: [
      'Пачка сигарет в день по отдельности кажется мелочью — ну, небольшая трата, как чашка кофе, на неё даже не обращаешь внимания. Именно в этом и хитрость. Расход незаметен поштучно, но это ежедневный платёж, который не прекращается ни на один день.',
      'А теперь посмотри на это не как на «пачку», а как на подписку. Ты платишь каждый день, без выходных, год за годом. И если сложить всё, что уходит за год, получается сумма, на которую вполне можно купить что-то крупное и заметное — то, на что ты, возможно, давно «не можешь найти денег».',
      'Приложение считает это за тебя — автоматически, в реальном времени, начиная с первой минуты без сигарет. И это важный момент: цифра экономии перестаёт быть абстракцией из разряда «ну да, наверное, что-то экономлю». Ты видишь конкретные деньги, которые прямо сейчас остаются у тебя в кармане, а не превращаются в дым.',
      'Но чтобы эти деньги по-настоящему мотивировали, с ними нужно кое-что сделать. Просто растущая цифра — это приятно, но абстрактно, мозгу не за что зацепиться. Поэтому сделай экономию видимой и конкретной: поставь в копилке цель. Не «копить вообще», а на определённую вещь — наушники, которые давно хотел, поездку, подарок близкому человеку, что-то для дома.',
      'Вот тут включается психология. Когда сэкономленное на сигаретах постепенно превращается в конкретную вещь, которую ты в итоге берёшь в руки, происходит важная перемена. Отказ от курения перестаёт ощущаться только как потеря — «у меня отняли сигарету». Он становится приобретением — «я кое-что получил взамен».',
      'И эта вещь работает как якорь. В трудный день, когда тянет и кажется, что отказ — это сплошное лишение, ты смотришь на цель в копилке или на уже купленную вещь — и она спокойно напоминает: курить ты бросаешь не «в минус», а «в плюс». Прогресс не только в чистых лёгких, которые не видно. Он лежит у тебя на полке.',
    ],
    bodyEn: [
      'A pack of cigarettes a day, taken on its own, seems like a trifle — a small spend, like a cup of coffee, you do not even notice it. That is exactly the trick. The expense is invisible piece by piece, but it is a daily payment that does not stop for a single day.',
      'Now look at it not as a "pack" but as a subscription. You pay every day, no days off, year after year. And if you add up everything that goes out over a year, you get a sum that could quite well buy something large and noticeable — the thing you perhaps "can never find the money for".',
      'The app counts this for you — automatically, in real time, starting from the first smoke-free minute. And this is an important point: the savings figure stops being an abstraction of the "well, I suppose I save something" kind. You see concrete money that right now stays in your pocket instead of turning into smoke.',
      'But for that money to truly motivate you, you need to do something with it. A simply growing number is pleasant but abstract — the brain has nothing to grab onto. So make the savings visible and concrete: set a goal in the jar. Not "save in general", but for a specific thing — the headphones you have long wanted, a trip, a gift for someone close, something for the home.',
      'This is where the psychology kicks in. When the money saved on cigarettes gradually turns into a concrete thing you finally hold in your hands, an important shift happens. Quitting stops feeling only like a loss — "my cigarette was taken away". It becomes a gain — "I got something in return".',
      'And that thing works as an anchor. On a hard day, when a craving hits and quitting feels like nothing but deprivation, you look at the goal in the jar or at the thing you have already bought — and it calmly reminds you: you are quitting not "into the minus" but "into the plus". The progress is not only in clean lungs you cannot see. It sits on your shelf.',
    ],
    takeawayRu: 'Поставь конкретную цель в копилке. Когда экономия станет вещью — это якорь в трудный день.',
    takeawayEn: 'Set a concrete jar goal. When savings become a real thing, they anchor you on hard days.',
  },
];

export function getArticle(id: string): Article | undefined {
  return ARTICLES.find((a) => a.id === id);
}
