// Per-method day-by-day curricula. Each StepLevel has its own track —
// duration, daily focus, optional medication action. Sources:
// • L1: Cochrane Whittaker 2024 (mHealth), Marlatt RP.
// • L2/L3: Cochrane Lindson 2023 (NRT mono RR 1.55, combo RR 1.27 vs mono).
// • L4 cytisine: Walker NEJM 2014/2021, RAUORA Courtney JAMA 2021 — 25-day schedule.
// • L4 bupropion: Cochrane Howes 2020 — 8-week course.
// • L5 varenicline: EAGLES NEJM 2016, Cochrane Livingstone-Banks 2023, FDA label.

import type { StepLevel } from './storage';

export type TrackDay = {
  day: number;                 // 1-based
  focusRu: string;
  focusEn: string;
  scienceRu: string;
  scienceEn: string;
  taskRu: string;
  taskEn: string;
  practice?: string;           // route to /practice/[id]
  // Why THIS technique today — connects the practice to the plan.
  whyRu?: string;
  whyEn?: string;
  // Medication action (if applicable)
  medRu?: string;
  medEn?: string;
};

export type Track = {
  stepId: StepLevel;
  totalDays: number;
  hasMedication: boolean;
  medAdherenceLabelRu?: string;
  medAdherenceLabelEn?: string;
  days: TrackDay[];
};

/* ============================================================
   L1 — Behavioural only (28 days)
   Days 1-14 each train a DIFFERENT evidence-based skill, so the
   first two weeks build a full toolkit rather than repeating one
   technique. `whyRu/whyEn` explains why the plan picks this skill today.
============================================================ */
const L1_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт. Удержись 24 часа.',
    focusEn: 'Start. Hold for 24 hours.',
    scienceRu: 'Никотин с рецепторов сходит за ~10 часов. Самые сильные тяги — короткие волны 3–5 минут.',
    scienceEn: 'Nicotine clears receptors in ~10h. Strongest cravings are 3–5 min waves.',
    taskRu: 'Урок дыхания «двойной вдох». 5 минут.',
    taskEn: 'Cyclic sighing breath. 5 minutes.',
    practice: 'cyclic_sigh',
    whyRu: 'В первый день тяга самая резкая, а готовых навыков ещё нет. Дыхание — самый быстрый рычаг: длинный выдох включает «тормоз» нервной системы и гасит пик за минуту. С него начинаем, потому что оно работает сразу и не требует подготовки.',
    whyEn: 'On day one the craving is sharpest and you have no skills ready yet. Breathing is the fastest lever: a long exhale switches on the nervous system\'s "brake" and tames the peak within a minute. We start here because it works instantly and needs no preparation.',
  },
  { day: 2,
    focusRu: 'Подготовь автопилот.',
    focusEn: 'Pre-load the autopilot.',
    scienceRu: 'Сила воли садится. If-then планы доказано работают, когда мозг устал (Armitage 2016).',
    scienceEn: 'Willpower drains. If-then plans work when the brain is tired (Armitage 2016).',
    taskRu: 'Создай 3 «Если триггер X → то действие Y».',
    taskEn: 'Write 3 "If trigger X → then action Y" plans.',
    practice: 'if_then',
    whyRu: 'Дыхание спасает в моменте, но в трудный момент думать некогда. Сегодня готовим решения заранее: план «Если — то» срабатывает автоматически, когда силы воли уже нет. Это твоя защита на следующие дни.',
    whyEn: 'Breathing saves you in the moment, but in a hard moment there\'s no time to think. Today we prepare decisions in advance: an if-then plan fires automatically when willpower is already gone. This is your defence for the days ahead.',
  },
  { day: 3,
    focusRu: 'Пик абстиненции.',
    focusEn: 'Peak withdrawal.',
    scienceRu: 'День 3 — пик симптомов. После сегодня станет легче. Не ярлык, а биохимия.',
    scienceEn: 'Day 3 = symptom peak. After today it gets easier. Biochemistry, not a label.',
    taskRu: 'Замена ритуала: сделай прямо сейчас.',
    taskEn: 'Ritual replacement: do it now.',
    practice: 'replace',
    whyRu: 'Сегодня тяжелее всего — пик абстиненции. Тянет не только никотин, но и пустота на месте привычного ритуала. Замена ритуала даёт рукам и телу новое действие вместо сигареты — именно то, что нужно в самый острый день.',
    whyEn: 'Today is the hardest — the peak of withdrawal. It\'s not just nicotine pulling at you, but the emptiness where the familiar ritual used to be. Replacing the ritual gives your hands and body a new action instead of a cigarette — exactly what you need on the most acute day.',
  },
  { day: 4,
    focusRu: 'Перепиши свои мысли.',
    focusEn: 'Rewrite your thoughts.',
    scienceRu: 'CBT-рефрейминг — золотой стандарт когнитивной части. Ловишь — оспариваешь — заменяешь.',
    scienceEn: 'CBT reframing is the cognitive gold standard. Catch — challenge — replace.',
    taskRu: 'Запиши одну мысль и переформулируй её.',
    taskEn: 'Log one thought and reframe it.',
    practice: 'reframe',
    whyRu: 'Пик позади, и теперь главную роль играют мысли-оправдания: «всего одна», «не справлюсь». Сегодня учимся ловить их и оспаривать фактами. Это переключает работу с тела на мышление — следующий слой защиты.',
    whyEn: 'The peak is behind you, and now justifying thoughts take the lead: "just one", "I can\'t cope". Today we learn to catch them and challenge them with facts. This shifts the work from the body to the mind — the next layer of defence.',
  },
  { day: 5,
    focusRu: 'Учись наблюдать тягу.',
    focusEn: 'Learn to observe the urge.',
    scienceRu: 'Urge surfing (Marlatt) — тяга это волна, не команда. Просто наблюдай.',
    scienceEn: 'Urge surfing (Marlatt) — a craving is a wave, not a command. Just observe.',
    taskRu: 'Прокати одну волну тяги.',
    taskEn: 'Surf one wave.',
    practice: 'urge_surf',
    whyRu: 'Ты уже умеешь дышать и спорить с мыслями. Сегодня — навык ничего не делать: наблюдать тягу как волну, пока она не спадёт сама. Это снимает ощущение, что тяга — приказ.',
    whyEn: 'You already know how to breathe and argue with thoughts. Today — the skill of doing nothing: observing a craving as a wave until it fades on its own. This removes the feeling that a craving is an order.',
  },
  { day: 6,
    focusRu: 'Заземление.',
    focusEn: 'Grounding.',
    scienceRu: '5-4-3-2-1 возвращает префронтальную кору в работу. Тяга питается мозгом, отключённым от тела.',
    scienceEn: '5-4-3-2-1 brings the prefrontal cortex back online. Cravings feed on a body-disconnected mind.',
    taskRu: 'Пройди упражнение 5-4-3-2-1.',
    taskEn: 'Do the 5-4-3-2-1 exercise.',
    practice: 'grounding',
    whyRu: 'Для острых, паникующих тяг нужен быстрый якорь. Заземление 5-4-3-2-1 переключает внимание с мыслей на органы чувств и возвращает контроль. Добавляем его в набор как «скорую помощь».',
    whyEn: 'For acute, panicky cravings you need a fast anchor. Grounding 5-4-3-2-1 switches attention from thoughts to the senses and brings back control. We add it to the toolkit as "first aid".',
  },
  { day: 7,
    focusRu: 'Неделя без сигарет. Анализируй.',
    focusEn: 'One week clean. Analyse.',
    scienceRu: 'EMA-логи показывают паттерны лучше памяти. Где твои триггеры?',
    scienceEn: 'EMA logs show patterns better than memory. Where are your triggers?',
    taskRu: 'Открой дневник тяги — посмотри топ-триггеров.',
    taskEn: 'Open the craving journal — review top triggers.',
    practice: 'ema',
    whyRu: 'У тебя уже есть набор техник. Чтобы применять их прицельно, нужно знать свои триггеры. Дневник тяги показывает их точнее памяти — это карта, по которой ты будешь готовить планы.',
    whyEn: 'You already have a set of techniques. To apply them with precision, you need to know your triggers. The craving journal shows them more accurately than memory — it\'s the map you\'ll use to prepare your plans.',
  },
  { day: 8,
    focusRu: 'Чек 4 нужд как привычка.',
    focusEn: 'HALT as a daily habit.',
    scienceRu: 'Голод / Злость / Одиночество / Усталость — часто настоящая нужда не в никотине.',
    scienceEn: 'Hungry / Angry / Lonely / Tired — the real need is often not nicotine.',
    taskRu: 'Пройди чек HALT.',
    taskEn: 'Run a HALT check.',
    practice: 'halt_check',
    whyRu: 'Дневник показал твои триггеры — и часто за ними не никотин, а голод, усталость или эмоция. Чек 4 нужд учит распознавать настоящую потребность и закрывать её напрямую, без сигареты.',
    whyEn: 'The journal showed your triggers — and behind them is often not nicotine but hunger, tiredness or an emotion. The HALT check teaches you to recognise the real need and meet it directly, without a cigarette.',
  },
  { day: 9,
    focusRu: 'Дыхание по квадрату.',
    focusEn: 'Box breathing.',
    scienceRu: 'Ритмичное дыхание 4-4-4-4 активирует парасимпатику и гасит стресс-реакцию.',
    scienceEn: 'Rhythmic 4-4-4-4 breathing activates the parasympathetic system and dampens the stress response.',
    taskRu: 'Сделай 6 кругов дыхания по квадрату.',
    taskEn: 'Do 6 rounds of box breathing.',
    practice: 'box_breath',
    whyRu: 'Под рукой полезно иметь больше одного дыхательного приёма. Дыхание по квадрату — короткое и предельно простое: ровный счёт 4-4-4-4 быстро успокаивает где угодно, даже на людях.',
    whyEn: 'It helps to have more than one breathing tool at hand. Box breathing is short and dead simple: an even 4-4-4-4 count calms you quickly anywhere, even around other people.',
  },
  { day: 10,
    focusRu: 'Сделай деньги видимыми.',
    focusEn: 'Make the money visible.',
    scienceRu: 'Активные финансовые стимулы — Cochrane RR ~1.5. Конкретная цель сильнее «экономии».',
    scienceEn: 'Active incentives — Cochrane RR ~1.5. A concrete goal beats abstract "savings".',
    taskRu: 'Поставь конкретную цель в копилке.',
    taskEn: 'Set a concrete goal in the jar.',
    practice: 'money',
    whyRu: 'Острая фаза почти позади — теперь важна долгая мотивация. Конкретная цель в копилке превращает невидимую пользу отказа в видимый прогресс к мечте. Это топливо на недели вперёд.',
    whyEn: 'The acute phase is almost over — now long-term motivation matters. A concrete goal in the jar turns the invisible benefit of quitting into visible progress toward a dream. That\'s fuel for the weeks ahead.',
  },
  { day: 11,
    focusRu: 'Социальный контракт.',
    focusEn: 'Social contract.',
    scienceRu: 'Скажи одному близкому. Социальное обязательство повышает шанс (Cochrane 2025).',
    scienceEn: 'Tell one person close. Social commitment raises the odds (Cochrane 2025).',
    taskRu: 'Напиши близкому, что бросаешь.',
    taskEn: 'Text someone close that you are quitting.',
    whyRu: 'Пока решение живёт только в твоей голове, сорваться легко и незаметно. Сегодня делаем его публичным: один близкий человек, который знает, — и включается социальная подотчётность.',
    whyEn: 'While the decision lives only in your head, slipping is easy and unnoticed. Today we make it public: one close person who knows — and social accountability kicks in.',
  },
  { day: 12,
    focusRu: 'Обнови план «Если — то».',
    focusEn: 'Refresh your if-then.',
    scienceRu: 'Триггеры смещаются. Раз в 2 недели обновляй план — иначе он устаревает.',
    scienceEn: 'Triggers shift. Refresh the plan every 2 weeks or it goes stale.',
    taskRu: 'Сделай 1 новый план «Если — то» на следующую неделю.',
    taskEn: 'Make 1 fresh if-then for next week.',
    practice: 'if_then',
    whyRu: 'Прошло 10 дней — твои триггеры уже не те, что в первый день. Дневник показал свежие ситуации. Обновляем планы «Если — то», чтобы защита соответствовала реальности, а не устаревшей картине.',
    whyEn: 'Ten days have passed — your triggers are no longer what they were on day one. The journal showed fresh situations. We refresh the if-then plans so your defence matches reality, not an outdated picture.',
  },
  { day: 13,
    focusRu: 'Тренируй ум 10 минут.',
    focusEn: 'Train the mind 10 min.',
    scienceRu: 'Практика осознанности снижает реактивность к триггерам. 10 минут раз в день.',
    scienceEn: 'Mindfulness practice lowers trigger reactivity. 10 minutes once a day.',
    taskRu: 'Майндфулнес-сессия 10 минут.',
    taskEn: 'Mindfulness session 10 minutes.',
    practice: 'mindfulness',
    whyRu: 'Острые техники у тебя есть. Теперь добавляем профилактику: 10 минут осознанности в день постепенно снижают силу триггеров — так тяг становится меньше ещё до того, как они вспыхнут.',
    whyEn: 'You have the acute-response techniques. Now we add prevention: 10 minutes of mindfulness a day gradually lowers the strength of triggers — so there are fewer cravings before they even flare up.',
  },
  { day: 14,
    focusRu: '2 недели. Острая фаза позади.',
    focusEn: '2 weeks. Acute phase done.',
    scienceRu: 'Симптомы абстиненции почти ушли. Дальше — поддержка, не дать срыву каскадом превратиться в полный возврат.',
    scienceEn: 'Withdrawal almost gone. Now: maintenance.',
    taskRu: 'Запланируй 1 личный приз за достигнутое.',
    taskEn: 'Plan 1 personal reward.',
    whyRu: 'За две недели ты собрал полный набор техник: дыхание, планы, наблюдение тяги, заземление, дневник, осознанность. Сегодня без новой техники — просто отметь результат и закрепи мотивацию наградой.',
    whyEn: 'In two weeks you\'ve assembled a full toolkit: breathing, plans, urge observation, grounding, the journal, mindfulness. Today no new technique — just mark the result and lock in motivation with a reward.',
  },
  { day: 17,
    focusRu: 'Кофе без сигарет.',
    focusEn: 'Coffee without cigarettes.',
    scienceRu: 'Утренняя сигарета — пик связи кофе↔никотин. Дыхание до кофе разрывает ассоциацию.',
    scienceEn: 'The morning cigarette has the strongest coffee↔nicotine link. Breathing before coffee breaks it.',
    taskRu: 'Сделай дыхание ДО первой чашки кофе.',
    taskEn: 'Do breathing BEFORE your first coffee.',
    practice: 'cyclic_sigh',
    whyRu: 'Связка «кофе → сигарета» — одна из самых прочных. Возвращаемся к дыханию, но с конкретной задачей: вставить его между кофе и привычкой, чтобы разорвать автоматизм.',
    whyEn: 'The "coffee → cigarette" link is one of the strongest. We return to breathing, but with a concrete job: insert it between coffee and the habit to break the automatism.',
  },
  { day: 21,
    focusRu: 'Дофамин восстанавливается.',
    focusEn: 'Dopamine resetting.',
    scienceRu: 'Рецепторы возвращают чувствительность. Простые удовольствия ярче.',
    scienceEn: 'Receptors regain sensitivity. Simple pleasures feel brighter.',
    taskRu: 'Назови 3 вещи, которые стали ярче.',
    taskEn: 'Name 3 things that feel sharper.',
    whyRu: 'Сегодня без техники — задача в другом. Мозг возвращает чувствительность к простым радостям, и важно это заметить: так закрепляется связь «без сигарет жизнь ярче».',
    whyEn: 'No technique today — the task is different. The brain is regaining sensitivity to simple joys, and it matters to notice it: that\'s how the link "life is brighter without cigarettes" gets reinforced.',
  },
  { day: 25,
    focusRu: 'Перепиши одну мысль.',
    focusEn: 'Rewrite one thought.',
    scienceRu: 'CBT-рефрейм за 5 минут в день — золотой стандарт когнитивной терапии.',
    scienceEn: 'A 5-minute CBT reframe a day is the cognitive gold standard.',
    taskRu: 'Сделай одну запись «мысль → факты → замена».',
    taskEn: 'Do one "thought → facts → swap" entry.',
    practice: 'reframe',
    whyRu: 'Острая фаза давно позади, но мысли-оправдания возвращаются и в спокойные дни. Освежаем навык рефрейминга, чтобы он оставался автоматическим — это профилактика поздних срывов.',
    whyEn: 'The acute phase is long behind, but justifying thoughts come back even on calm days. We refresh the reframing skill so it stays automatic — this is prevention of late slips.',
  },
  { day: 28,
    focusRu: 'Месяц. Фаза maintenance.',
    focusEn: 'One month. Maintenance phase.',
    scienceRu: 'Лёгкие очищаются, кашель уходит. Ты прошёл главное окно риска.',
    scienceEn: 'Lungs clearing, cough fading. You passed the main risk window.',
    taskRu: 'Купи себе небольшой подарок из копилки.',
    taskEn: 'Buy a small gift from the jar.',
    practice: 'money',
    whyRu: 'Месяц пройден. Сегодня закрываем цикл: достань реальную награду из копилки. Видимый, осязаемый приз закрепляет всё, что ты сделал, и задаёт настрой на следующую цель.',
    whyEn: 'A month is done. Today we close the loop: take a real reward from the jar. A visible, tangible prize locks in everything you\'ve done and sets the tone for the next goal.',
  },
];

/* ============================================================
   L2 — Cytisine (Tabex) 25-day course (Walker NEJM 2014/2021)
   Quit date = day 5. Schedule per Sopharma Tabex instructions.
============================================================ */
const L2_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт цитизина (Табекс). Quit date — день 5.',
    focusEn: 'Cytisine (Tabex) start. Quit date = day 5.',
    scienceRu: 'Цитизин блокирует никотиновые рецепторы. Курс 25 дней. RR 2.21 vs плацебо. Цена — десятки раз дешевле варениклина.',
    scienceEn: 'Cytisine blocks nicotine receptors. 25-day course. RR 2.21 vs placebo. Many times cheaper than varenicline.',
    taskRu: 'Прими первую таблетку с водой. Поставь напоминания на каждые 2 часа.',
    taskEn: 'Take the first tablet with water. Set 2-hour reminders.',
    medRu: 'Дни 1–3: 1 табл (1.5 мг) каждые 2 часа, всего 6 раз в день. Курить можно.',
    medEn: 'Days 1–3: 1 tab (1.5 mg) every 2 h, 6/day. Smoking allowed.',
  },
  { day: 3,
    focusRu: 'Снижай число сигарет на 50%.',
    focusEn: 'Cut cigarettes 50%.',
    scienceRu: 'К дню 5 — последняя сигарета. Цитизин уже работает на рецепторах.',
    scienceEn: 'By day 5 — last cigarette. Cytisine already working on receptors.',
    taskRu: 'Запиши сколько сигарет сегодня и поставь цель −50% завтра.',
    taskEn: 'Log today’s cigarette count, set −50% target tomorrow.',
    practice: 'ema',
    medRu: 'Продолжай 6 табл/день. Тошнота — принимать после еды.',
    medEn: 'Keep 6 tab/day. Nausea — take after food.',
  },
  { day: 4,
    focusRu: 'Снижение частоты приёма.',
    focusEn: 'Lower dosing frequency.',
    scienceRu: 'С дня 4 — каждые 2.5 ч. Quit date завтра.',
    scienceEn: 'From day 4 — every 2.5 h. Quit date tomorrow.',
    taskRu: 'Готовься к завтра: убери сигареты, сделай if-then.',
    taskEn: 'Prep for tomorrow: remove cigarettes, make if-then.',
    practice: 'if_then',
    medRu: 'Дни 4–12: 1 табл каждые 2.5 ч, 5 раз в день.',
    medEn: 'Days 4–12: 1 tab every 2.5 h, 5/day.',
  },
  { day: 5,
    focusRu: 'QUIT DATE. Последняя сигарета сегодня.',
    focusEn: 'QUIT DATE. Last cigarette today.',
    scienceRu: 'Цитизин уже на рецепторах. Сигарета не даёт того кайфа — это и есть план.',
    scienceEn: 'Cytisine occupies receptors. Cigarette feels muted — that’s the mechanism.',
    taskRu: 'Выкури последнюю осознанно. С завтра — ноль.',
    taskEn: 'Smoke the last one mindfully. Tomorrow — zero.',
    medRu: '5 табл/день продолжай.',
    medEn: 'Continue 5 tab/day.',
  },
  { day: 6,
    focusRu: 'День 1 без сигарет.',
    focusEn: 'Day 1 smoke-free.',
    scienceRu: 'Цитизин блокирует тягу. Если есть — записать в дневник.',
    scienceEn: 'Cytisine blocks craving. If still present — log it.',
    taskRu: 'Сделай чек-ин дня.',
    taskEn: 'Daily check-in.',
    practice: 'ema',
    medRu: 'Продолжай 5 табл/день.',
    medEn: 'Continue 5 tab/day.',
  },
  { day: 13,
    focusRu: 'Снижаем дозу.',
    focusEn: 'Lower dose.',
    scienceRu: 'Постепенный отвыкаем от препарата.',
    scienceEn: 'Gradual wean.',
    taskRu: 'Принимай 1 табл каждые 3 часа.',
    taskEn: 'Take 1 tab every 3 hours.',
    medRu: 'Дни 13–16: 4 табл/день (каждые 3 ч).',
    medEn: 'Days 13–16: 4 tab/day (every 3 h).',
  },
  { day: 17,
    focusRu: 'Дальнейшее снижение.',
    focusEn: 'Further reduction.',
    scienceRu: 'Доза падает, тяга должна оставаться слабой.',
    scienceEn: 'Dose down, craving should stay weak.',
    taskRu: 'Запиши уровень тяги.',
    taskEn: 'Log craving level.',
    medRu: 'Дни 17–20: 3 табл/день.',
    medEn: 'Days 17–20: 3 tab/day.',
  },
  { day: 21,
    focusRu: 'Финальная фаза.',
    focusEn: 'Final phase.',
    scienceRu: 'Курс почти окончен.',
    scienceEn: 'Course nearly done.',
    taskRu: 'Сделай 2 новых if-then плана на следующий месяц.',
    taskEn: 'Make 2 new if-then plans for next month.',
    practice: 'if_then',
    medRu: 'Дни 21–25: 1–2 табл/день.',
    medEn: 'Days 21–25: 1–2 tab/day.',
  },
  { day: 25,
    focusRu: 'Курс цитизина окончен.',
    focusEn: 'Cytisine course done.',
    scienceRu: 'Адхерентность критична: ~30% бросают раньше срока и срываются. Ты прошёл полный курс.',
    scienceEn: 'Adherence critical: ~30% stop early and relapse. You completed the full course.',
    taskRu: 'Перейди в режим поддержания. Ежедневный чек-ин.',
    taskEn: 'Enter maintenance. Daily check-in.',
  },
];

/* ============================================================
   L3 — Bupropion SR 8 weeks (Cochrane Howes 2020, RR 1.64)
   Quit date = day 8. Prescription only.
============================================================ */
const L3_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт бупропиона. 150 мг утром.',
    focusEn: 'Bupropion start. 150 mg in the morning.',
    scienceRu: 'Бупропион — антидепрессант, снижает тягу. Курс 8 нед. Quit date — день 8.',
    scienceEn: 'Bupropion — antidepressant lowering craving. 8-week course. Quit date = day 8.',
    taskRu: 'Прими 150 мг утром после еды. Запиши настроение.',
    taskEn: 'Take 150 mg morning after food. Log mood.',
    medRu: 'Дни 1–3: 150 мг 1 раз в день утром. Курить можно.',
    medEn: 'Days 1–3: 150 mg once daily in morning. Smoking allowed.',
  },
  { day: 4,
    focusRu: 'Удвоение дозы.',
    focusEn: 'Dose doubled.',
    scienceRu: 'С дня 4 переходим на 2 раза в день. Вторую дозу — не позже 17:00 (бессонница).',
    scienceEn: 'From day 4 — twice daily. Second dose no later than 5pm (insomnia).',
    taskRu: '150 мг утром + 150 мг после обеда. Никакой второй дозы вечером.',
    taskEn: '150 mg morning + 150 mg after lunch. No evening dose.',
    medRu: 'Дни 4–конец: 150 мг × 2/день, интервал ≥8 ч, второй приём до 17:00.',
    medEn: 'Days 4–end: 150 mg × 2/day, ≥8 h apart, 2nd dose by 5pm.',
  },
  { day: 8,
    focusRu: 'QUIT DATE. Последняя сигарета.',
    focusEn: 'QUIT DATE. Last cigarette.',
    scienceRu: 'Препарат накопил концентрацию. Тяга уже снижена. Можно бросать.',
    scienceEn: 'Drug at full concentration. Craving already reduced. Time to quit.',
    taskRu: 'Выкури последнюю сегодня. С завтра — ноль.',
    taskEn: 'Last cigarette today. Tomorrow — zero.',
    medRu: 'Продолжай 150 мг × 2/день.',
    medEn: 'Continue 150 mg × 2/day.',
  },
  { day: 14,
    focusRu: '1 неделя без сигарет.',
    focusEn: '1 week smoke-free.',
    scienceRu: 'Бессонница / сухость во рту / тошнота — частые побочки. Обычно проходят к нед 3.',
    scienceEn: 'Insomnia / dry mouth / nausea — common side effects. Usually fade by week 3.',
    taskRu: 'Если бессонница — сдвинь вторую дозу на 15:00.',
    taskEn: 'Insomnia? Shift second dose to 3pm.',
    medRu: '150 мг × 2/день. Если судороги, сильная сыпь, мысли о суициде — отмена + врач.',
    medEn: '150 mg × 2/day. Seizures, severe rash, suicidal thoughts → stop + doctor.',
  },
  { day: 28,
    focusRu: 'Месяц без сигарет.',
    focusEn: '1 month smoke-free.',
    scienceRu: 'Лёгкие очищаются, кашель уходит. Препарат продолжаем.',
    scienceEn: 'Lungs clearing, cough fading. Continue med.',
    taskRu: 'Купи себе подарок из копилки.',
    taskEn: 'Buy a gift from the jar.',
    practice: 'money',
  },
  { day: 56,
    focusRu: '8 недель. Курс окончен.',
    focusEn: '8 weeks. Course done.',
    scienceRu: 'Резкая отмена бупропиона ОК — титровать вниз не нужно.',
    scienceEn: 'Abrupt bupropion stop is OK — no taper needed.',
    taskRu: 'Прими последнюю дозу. Поставь новую цель.',
    taskEn: 'Take last dose. Set a new goal.',
    practice: 'money',
  },
];

/* ============================================================
   L4 / L5 — Varenicline (Champix). EAGLES NEJM 2016. Quit date = day 8.
   L4 = 12-week course, L5 = extended (24-week) course — same daily content.
============================================================ */
const VARENICLINE_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт варениклина. Титрование.',
    focusEn: 'Varenicline start. Titration.',
    scienceRu: 'Самая эффективная монотерапия. RR 2.32 vs плацебо. 12 недель.',
    scienceEn: 'Most effective monotherapy. RR 2.32 vs placebo. 12 weeks.',
    taskRu: '0.5 мг 1 раз в день. После плотной еды + стакан воды.',
    taskEn: '0.5 mg once a day. After full meal + glass of water.',
    medRu: 'Дни 1–3: 0.5 мг × 1/день. Можно курить.',
    medEn: 'Days 1–3: 0.5 mg × 1/day. Smoking allowed.',
  },
  { day: 4,
    focusRu: 'Удвоение дозы.',
    focusEn: 'Dose doubled.',
    scienceRu: 'Постепенно повышаем чтобы избежать тошноты.',
    scienceEn: 'Gradual ramp to avoid nausea.',
    taskRu: '0.5 мг 2 раза в день.',
    taskEn: '0.5 mg twice a day.',
    medRu: 'Дни 4–7: 0.5 мг × 2/день. Можно курить.',
    medEn: 'Days 4–7: 0.5 mg × 2/day. Smoking allowed.',
  },
  { day: 8,
    focusRu: 'QUIT DATE. Полная доза, последняя сигарета.',
    focusEn: 'QUIT DATE. Full dose, last cigarette.',
    scienceRu: 'Препарат уже работает. Сигарета даёт ослабленный кайф — это и есть механизм.',
    scienceEn: 'Drug already working. Cigarette feels muted — that’s the mechanism.',
    taskRu: 'Сегодня — последняя сигарета. Перейди на 1 мг 2р/день.',
    taskEn: 'Last cigarette today. Switch to 1 mg twice daily.',
    medRu: 'С дня 8: 1 мг × 2/день, утром и вечером, после еды.',
    medEn: 'From day 8: 1 mg × 2/day, morning and evening, after meals.',
  },
  { day: 14,
    focusRu: '1 неделя без сигарет.',
    focusEn: '1 week smoke-free.',
    scienceRu: 'Если тошнит — принимай после плотной еды + вода. Странные сны — нормально.',
    scienceEn: 'Nausea? Take after full meal + water. Vivid dreams are normal.',
    taskRu: 'Чек-ин дня + дневник тяги.',
    taskEn: 'Daily check-in + craving journal.',
    practice: 'ema',
  },
  { day: 28,
    focusRu: 'Месяц без сигарет.',
    focusEn: '1 month smoke-free.',
    scienceRu: 'Лёгкие очищаются, кашель уходит. Препарат продолжаем.',
    scienceEn: 'Lungs clearing, cough fading. Continue med.',
    taskRu: 'Купи себе подарок из копилки.',
    taskEn: 'Buy a gift from the jar.',
    practice: 'money',
  },
  { day: 56,
    focusRu: '8 недель. Готовимся к финишу.',
    focusEn: '8 weeks. Approaching finish.',
    scienceRu: 'Курс ещё 4 недели. Не бросай раньше.',
    scienceEn: 'Course 4 more weeks. Don’t stop early.',
    taskRu: 'Сделай 3 новых if-then плана на жизнь после препарата.',
    taskEn: 'Make 3 new if-then plans for life after the med.',
    practice: 'if_then',
  },
  { day: 84,
    focusRu: 'Курс варениклина окончен.',
    focusEn: 'Varenicline course done.',
    scienceRu: 'Можно продлить ещё на 12 недель если есть риск срыва (Tonstad JAMA 2006).',
    scienceEn: 'Can extend 12 more weeks if relapse risk (Tonstad JAMA 2006).',
    taskRu: 'Решение о продлении — с врачом.',
    taskEn: 'Extension decision — with a clinician.',
  },
];

export const TRACKS: Record<StepLevel, Track> = {
  L1_behavioral: { stepId: 'L1_behavioral', totalDays: 28, hasMedication: false, days: L1_DAYS },
  L2_nrt_light: {
    stepId: 'L2_nrt_light', totalDays: 25, hasMedication: true,
    medAdherenceLabelRu: 'Принял Табекс по схеме', medAdherenceLabelEn: 'Took Tabex per schedule',
    days: L2_DAYS,
  },
  L3_nrt_combo: {
    stepId: 'L3_nrt_combo', totalDays: 56, hasMedication: true,
    medAdherenceLabelRu: 'Принял бупропион (по схеме)', medAdherenceLabelEn: 'Took bupropion (per schedule)',
    days: L3_DAYS,
  },
  L4_pharma: {
    stepId: 'L4_pharma', totalDays: 84, hasMedication: true,
    medAdherenceLabelRu: 'Принял варениклин (2 раза)', medAdherenceLabelEn: 'Took varenicline (twice)',
    days: VARENICLINE_DAYS,
  },
  L5_intensive: {
    stepId: 'L5_intensive', totalDays: 168, hasMedication: true,
    medAdherenceLabelRu: 'Принял варениклин (2 раза)', medAdherenceLabelEn: 'Took varenicline (twice)',
    days: VARENICLINE_DAYS,
  },
};

export function getTrack(stepId: StepLevel | undefined): Track {
  return TRACKS[stepId ?? 'L1_behavioral'];
}

// Find day content for the user's current day on this method.
export function trackDay(stepId: StepLevel | undefined, day: number): TrackDay {
  const tr = getTrack(stepId);
  const exact = tr.days.find((d) => d.day === day);
  if (exact) return exact;
  // Fallback: closest preceding day
  const prev = [...tr.days].reverse().find((d) => d.day < day);
  if (prev) return prev;
  // Generic synth
  return {
    day,
    focusRu: 'Удерживай курс.',
    focusEn: 'Hold the course.',
    scienceRu: 'Каждый день закрепляет новое поведение.',
    scienceEn: 'Every day wires the new behaviour deeper.',
    taskRu: 'Сделай чек-ин дня.',
    taskEn: 'Do today’s check-in.',
  };
}
