// Per-method day-by-day curricula. Each StepLevel has its own track —
// duration, daily focus, optional medication action. Sources:
// • L1: Cochrane Whittaker 2024 (mHealth), Marlatt RP.
// • L2/L3: Cochrane Lindson 2023 (NRT mono RR 1.55, combo RR 1.27 vs mono).
// • L4 cytisine: Walker NEJM 2014/2021, RAUORA Courtney JAMA 2021 — 25-day schedule.
// • L4 bupropion: Cochrane Howes 2020 — 8-week course.
// • L5 varenicline: EAGLES NEJM 2016, Cochrane Livingstone-Banks 2023, FDA label.

import type { StepLevel } from './storage';

export type TrackDay = {
  day: number;                 // 1-based
  focusRu: string;
  focusEn: string;
  scienceRu: string;
  scienceEn: string;
  taskRu: string;
  taskEn: string;
  practice?: string;           // route to /practice/[id]
  // Medication action (if applicable)
  medRu?: string;
  medEn?: string;
};

export type Track = {
  stepId: StepLevel;
  totalDays: number;
  hasMedication: boolean;
  medAdherenceLabelRu?: string;
  medAdherenceLabelEn?: string;
  days: TrackDay[];
};

/* ============================================================
   L1 — Behavioural only (28 days)
============================================================ */
const L1_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт. Удержись 24 часа.',
    focusEn: 'Start. Hold for 24 hours.',
    scienceRu: 'Никотин с рецепторов сходит за ~10 часов. Самые сильные тяги — короткие волны 3–5 минут.',
    scienceEn: 'Nicotine clears receptors in ~10h. Strongest cravings are 3–5 min waves.',
    taskRu: 'Урок дыхания «cyclic sighing». 5 минут.',
    taskEn: 'Cyclic sighing breath. 5 minutes.',
    practice: 'cyclic_sigh',
  },
  { day: 2,
    focusRu: 'Подготовь автопилот.',
    focusEn: 'Pre-load the autopilot.',
    scienceRu: 'Сила воли садится. If-then планы доказано работают, когда мозг устал (Armitage 2016).',
    scienceEn: 'Willpower drains. If-then plans work when the brain is tired (Armitage 2016).',
    taskRu: 'Создай 3 «Если триггер X → то действие Y».',
    taskEn: 'Write 3 "If trigger X → then action Y" plans.',
    practice: 'if_then',
  },
  { day: 3,
    focusRu: 'Пик абстиненции.',
    focusEn: 'Peak withdrawal.',
    scienceRu: 'День 3 — пик симптомов. После сегодня станет легче. Не ярлык, а биохимия.',
    scienceEn: 'Day 3 = symptom peak. After today it gets easier. Biochemistry, not a label.',
    taskRu: 'Замена ритуала: сделай сейчас.',
    taskEn: 'Ritual replacement: do it now.',
    practice: 'replace',
  },
  { day: 5,
    focusRu: 'Перепиши свои мысли.',
    focusEn: 'Rewrite your thoughts.',
    scienceRu: 'CBT-рефрейминг — золотой стандарт когнитивной части.',
    scienceEn: 'CBT reframing is the cognitive gold standard.',
    taskRu: 'Запиши одну мысль и переформулируй её.',
    taskEn: 'Log one thought and reframe it.',
    practice: 'reframe',
  },
  { day: 7,
    focusRu: 'Неделя без сигарет. Анализируй.',
    focusEn: 'One week clean. Analyse.',
    scienceRu: 'EMA-логи показывают паттерны лучше памяти. Где твои триггеры?',
    scienceEn: 'EMA logs show patterns better than memory. Where are your triggers?',
    taskRu: 'Открой дневник тяги.',
    taskEn: 'Open the craving journal.',
    practice: 'ema',
  },
  { day: 14,
    focusRu: '2 недели. Острая фаза позади.',
    focusEn: '2 weeks. Acute phase done.',
    scienceRu: 'Симптомы абстиненции почти ушли. Дальше — поддержка, не дать срыву каскадом превратиться в полный возврат.',
    scienceEn: 'Withdrawal almost gone. Now: maintenance.',
    taskRu: 'Запланируй 1 личный приз.',
    taskEn: 'Plan 1 personal reward.',
  },
  { day: 21,
    focusRu: 'Дофамин восстанавливается.',
    focusEn: 'Dopamine resetting.',
    scienceRu: 'Рецепторы возвращают чувствительность. Простые удовольствия ярче.',
    scienceEn: 'Receptors regain sensitivity. Simple pleasures feel brighter.',
    taskRu: 'Назови 3 вещи, которые стали ярче.',
    taskEn: 'Name 3 things that feel sharper.',
  },
  { day: 28,
    focusRu: 'Месяц. Фаза maintenance.',
    focusEn: 'One month. Maintenance phase.',
    scienceRu: 'Лёгкие очищаются, кашель уходит. Ты прошёл главное окно риска.',
    scienceEn: 'Lungs clearing, cough fading. You passed the main risk window.',
    taskRu: 'Купи себе небольшой подарок из копилки.',
    taskEn: 'Buy a small gift from the jar.',
    practice: 'money',
  },
];

/* ============================================================
   L2 — Cytisine (Tabex) 25-day course (Walker NEJM 2014/2021)
   Quit date = day 5. Schedule per Sopharma Tabex instructions.
============================================================ */
const L2_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт цитизина (Табекс). Quit date — день 5.',
    focusEn: 'Cytisine (Tabex) start. Quit date = day 5.',
    scienceRu: 'Цитизин блокирует никотиновые рецепторы. Курс 25 дней. RR 2.21 vs плацебо. Цена — десятки раз дешевле варениклина.',
    scienceEn: 'Cytisine blocks nicotine receptors. 25-day course. RR 2.21 vs placebo. Many times cheaper than varenicline.',
    taskRu: 'Прими первую таблетку с водой. Поставь напоминания на каждые 2 часа.',
    taskEn: 'Take the first tablet with water. Set 2-hour reminders.',
    medRu: 'Дни 1–3: 1 табл (1.5 мг) каждые 2 часа, всего 6 раз в день. Курить можно.',
    medEn: 'Days 1–3: 1 tab (1.5 mg) every 2 h, 6/day. Smoking allowed.',
  },
  { day: 3,
    focusRu: 'Снижай число сигарет на 50%.',
    focusEn: 'Cut cigarettes 50%.',
    scienceRu: 'К дню 5 — последняя сигарета. Цитизин уже работает на рецепторах.',
    scienceEn: 'By day 5 — last cigarette. Cytisine already working on receptors.',
    taskRu: 'Запиши сколько сигарет сегодня и поставь цель −50% завтра.',
    taskEn: 'Log today’s cigarette count, set −50% target tomorrow.',
    practice: 'ema',
    medRu: 'Продолжай 6 табл/день. Тошнота — принимать после еды.',
    medEn: 'Keep 6 tab/day. Nausea — take after food.',
  },
  { day: 4,
    focusRu: 'Снижение частоты приёма.',
    focusEn: 'Lower dosing frequency.',
    scienceRu: 'С дня 4 — каждые 2.5 ч. Quit date завтра.',
    scienceEn: 'From day 4 — every 2.5 h. Quit date tomorrow.',
    taskRu: 'Готовься к завтра: убери сигареты, сделай if-then.',
    taskEn: 'Prep for tomorrow: remove cigarettes, make if-then.',
    practice: 'if_then',
    medRu: 'Дни 4–12: 1 табл каждые 2.5 ч, 5 раз в день.',
    medEn: 'Days 4–12: 1 tab every 2.5 h, 5/day.',
  },
  { day: 5,
    focusRu: 'QUIT DATE. Последняя сигарета сегодня.',
    focusEn: 'QUIT DATE. Last cigarette today.',
    scienceRu: 'Цитизин уже на рецепторах. Сигарета не даёт того кайфа — это и есть план.',
    scienceEn: 'Cytisine occupies receptors. Cigarette feels muted — that’s the mechanism.',
    taskRu: 'Выкури последнюю осознанно. С завтра — ноль.',
    taskEn: 'Smoke the last one mindfully. Tomorrow — zero.',
    medRu: '5 табл/день продолжай.',
    medEn: 'Continue 5 tab/day.',
  },
  { day: 6,
    focusRu: 'День 1 без сигарет.',
    focusEn: 'Day 1 smoke-free.',
    scienceRu: 'Цитизин блокирует тягу. Если есть — записать в дневник.',
    scienceEn: 'Cytisine blocks craving. If still present — log it.',
    taskRu: 'Сделай чек-ин дня.',
    taskEn: 'Daily check-in.',
    practice: 'ema',
    medRu: 'Продолжай 5 табл/день.',
    medEn: 'Continue 5 tab/day.',
  },
  { day: 13,
    focusRu: 'Снижаем дозу.',
    focusEn: 'Lower dose.',
    scienceRu: 'Постепенный отвыкаем от препарата.',
    scienceEn: 'Gradual wean.',
    taskRu: 'Принимай 1 табл каждые 3 часа.',
    taskEn: 'Take 1 tab every 3 hours.',
    medRu: 'Дни 13–16: 4 табл/день (каждые 3 ч).',
    medEn: 'Days 13–16: 4 tab/day (every 3 h).',
  },
  { day: 17,
    focusRu: 'Дальнейшее снижение.',
    focusEn: 'Further reduction.',
    scienceRu: 'Доза падает, тяга должна оставаться слабой.',
    scienceEn: 'Dose down, craving should stay weak.',
    taskRu: 'Запиши уровень тяги.',
    taskEn: 'Log craving level.',
    medRu: 'Дни 17–20: 3 табл/день.',
    medEn: 'Days 17–20: 3 tab/day.',
  },
  { day: 21,
    focusRu: 'Финальная фаза.',
    focusEn: 'Final phase.',
    scienceRu: 'Курс почти окончен.',
    scienceEn: 'Course nearly done.',
    taskRu: 'Сделай 2 новых if-then плана на следующий месяц.',
    taskEn: 'Make 2 new if-then plans for next month.',
    practice: 'if_then',
    medRu: 'Дни 21–25: 1–2 табл/день.',
    medEn: 'Days 21–25: 1–2 tab/day.',
  },
  { day: 25,
    focusRu: 'Курс цитизина окончен.',
    focusEn: 'Cytisine course done.',
    scienceRu: 'Адхерентность критична: ~30% бросают раньше срока и срываются. Ты прошёл полный курс.',
    scienceEn: 'Adherence critical: ~30% stop early and relapse. You completed the full course.',
    taskRu: 'Перейди в режим поддержания. Ежедневный чек-ин.',
    taskEn: 'Enter maintenance. Daily check-in.',
  },
];

/* ============================================================
   L3 — Bupropion SR 8 weeks (Cochrane Howes 2020, RR 1.64)
   Quit date = day 8. Prescription only.
============================================================ */
const L3_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт бупропиона. 150 мг утром.',
    focusEn: 'Bupropion start. 150 mg in the morning.',
    scienceRu: 'Бупропион — антидепрессант, снижает тягу. Курс 8 нед. Quit date — день 8.',
    scienceEn: 'Bupropion — antidepressant lowering craving. 8-week course. Quit date = day 8.',
    taskRu: 'Прими 150 мг утром после еды. Запиши настроение.',
    taskEn: 'Take 150 mg morning after food. Log mood.',
    medRu: 'Дни 1–3: 150 мг 1 раз в день утром. Курить можно.',
    medEn: 'Days 1–3: 150 mg once daily in morning. Smoking allowed.',
  },
  { day: 4,
    focusRu: 'Удвоение дозы.',
    focusEn: 'Dose doubled.',
    scienceRu: 'С дня 4 переходим на 2 раза в день. Вторую дозу — не позже 17:00 (бессонница).',
    scienceEn: 'From day 4 — twice daily. Second dose no later than 5pm (insomnia).',
    taskRu: '150 мг утром + 150 мг после обеда. Никакой второй дозы вечером.',
    taskEn: '150 mg morning + 150 mg after lunch. No evening dose.',
    medRu: 'Дни 4–конец: 150 мг × 2/день, интервал ≥8 ч, второй приём до 17:00.',
    medEn: 'Days 4–end: 150 mg × 2/day, ≥8 h apart, 2nd dose by 5pm.',
  },
  { day: 8,
    focusRu: 'QUIT DATE. Последняя сигарета.',
    focusEn: 'QUIT DATE. Last cigarette.',
    scienceRu: 'Препарат накопил концентрацию. Тяга уже снижена. Можно бросать.',
    scienceEn: 'Drug at full concentration. Craving already reduced. Time to quit.',
    taskRu: 'Выкури последнюю сегодня. С завтра — ноль.',
    taskEn: 'Last cigarette today. Tomorrow — zero.',
    medRu: 'Продолжай 150 мг × 2/день.',
    medEn: 'Continue 150 mg × 2/day.',
  },
  { day: 14,
    focusRu: '1 неделя без сигарет.',
    focusEn: '1 week smoke-free.',
    scienceRu: 'Бессонница / сухость во рту / тошнота — частые побочки. Обычно проходят к нед 3.',
    scienceEn: 'Insomnia / dry mouth / nausea — common side effects. Usually fade by week 3.',
    taskRu: 'Если бессонница — сдвинь вторую дозу на 15:00.',
    taskEn: 'Insomnia? Shift second dose to 3pm.',
    medRu: '150 мг × 2/день. Если судороги, сильная сыпь, мысли о суициде — отмена + врач.',
    medEn: '150 mg × 2/day. Seizures, severe rash, suicidal thoughts → stop + doctor.',
  },
  { day: 28,
    focusRu: 'Месяц без сигарет.',
    focusEn: '1 month smoke-free.',
    scienceRu: 'Лёгкие очищаются, кашель уходит. Препарат продолжаем.',
    scienceEn: 'Lungs clearing, cough fading. Continue med.',
    taskRu: 'Купи себе подарок из копилки.',
    taskEn: 'Buy a gift from the jar.',
    practice: 'money',
  },
  { day: 56,
    focusRu: '8 недель. Курс окончен.',
    focusEn: '8 weeks. Course done.',
    scienceRu: 'Резкая отмена бупропиона ОК — титровать вниз не нужно.',
    scienceEn: 'Abrupt bupropion stop is OK — no taper needed.',
    taskRu: 'Прими последнюю дозу. Поставь новую цель.',
    taskEn: 'Take last dose. Set a new goal.',
    practice: 'money',
  },
];

/* ============================================================
   L4 — Cytisine 25-day (Walker NEJM 2014/2021 RAUORA)
   Quit date = day 5.
============================================================ */
const L4_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт цитизина. Quit date — день 5.',
    focusEn: 'Cytisine start. Quit date = day 5.',
    scienceRu: 'Цитизин (Табекс) ~варенику. RR 2.21 vs плацебо. Курс 25 дней.',
    scienceEn: 'Cytisine ≈ varenicline. RR 2.21 vs placebo. 25-day course.',
    taskRu: 'Принимай 1 табл каждые 2 часа (6 раз за день).',
    taskEn: 'Take 1 tab every 2 hours (6/day).',
    medRu: 'Дни 1–3: 1 табл × 6/день (каждые 2 часа). Можно курить.',
    medEn: 'Days 1–3: 1 tab × 6/day (every 2 h). Smoking allowed.',
  },
  { day: 4,
    focusRu: 'Снижение частоты.',
    focusEn: 'Frequency drop.',
    scienceRu: 'С дня 4 принимать реже. Quit date — завтра.',
    scienceEn: 'From day 4 take less often. Quit date — tomorrow.',
    taskRu: 'Готовь quit date: убери сигареты, сделай if-then.',
    taskEn: 'Prep quit date: remove cigarettes, make if-then.',
    practice: 'if_then',
    medRu: 'Дни 4–12: 1 табл × 5/день (каждые 2.5 часа).',
    medEn: 'Days 4–12: 1 tab × 5/day (every 2.5 h).',
  },
  { day: 5,
    focusRu: 'QUIT DATE. Сегодня — последняя сигарета.',
    focusEn: 'QUIT DATE. Last cigarette today.',
    scienceRu: 'Цитизин уже на рецепторах. Сигарета не даст того кайфа — это и есть план.',
    scienceEn: 'Cytisine on receptors. Smoking won’t feel right — that’s the plan.',
    taskRu: 'Выкури последнюю осознанно. Завтра — ноль.',
    taskEn: 'Smoke the last one mindfully. Tomorrow — zero.',
    medRu: '5/день продолжай.',
    medEn: 'Keep 5/day.',
  },
  { day: 6,
    focusRu: 'День 1 без сигарет.',
    focusEn: 'Day 1 smoke-free.',
    scienceRu: 'Цитизин блокирует тягу. Если есть — записать в дневник.',
    scienceEn: 'Cytisine blocks craving. If still there — log it.',
    taskRu: 'Сделай чек-ин дня.',
    taskEn: 'Do daily check-in.',
    practice: 'ema',
  },
  { day: 13,
    focusRu: 'Снижаем дозу.',
    focusEn: 'Lower dose.',
    scienceRu: 'Постепенный отвыкаем от препарата.',
    scienceEn: 'Gradual wean.',
    taskRu: 'Принимай 1 табл каждые 3 часа.',
    taskEn: 'Take 1 tab every 3 hours.',
    medRu: 'Дни 13–16: 4/день (каждые 3 часа).',
    medEn: 'Days 13–16: 4/day (every 3 h).',
  },
  { day: 17,
    focusRu: 'Дальнейшее снижение.',
    focusEn: 'Further reduction.',
    scienceRu: 'Доза уменьшается, тяга должна оставаться слабой.',
    scienceEn: 'Dose down, craving should stay weak.',
    taskRu: 'Запиши уровень тяги в дневник.',
    taskEn: 'Log craving level.',
    medRu: 'Дни 17–20: 3 табл/день.',
    medEn: 'Days 17–20: 3 tab/day.',
  },
  { day: 21,
    focusRu: 'Финальная фаза.',
    focusEn: 'Final phase.',
    scienceRu: 'Курс почти окончен.',
    scienceEn: 'Course nearly done.',
    taskRu: 'Сделай 2 новых if-then плана на следующий месяц.',
    taskEn: 'Make 2 new if-then plans for next month.',
    practice: 'if_then',
    medRu: 'Дни 21–25: 1–2 табл/день.',
    medEn: 'Days 21–25: 1–2 tab/day.',
  },
  { day: 25,
    focusRu: 'Курс цитизина окончен.',
    focusEn: 'Cytisine course done.',
    scienceRu: 'Дальше — поддержка только поведенческая.',
    scienceEn: 'From here — behavioural maintenance only.',
    taskRu: 'Перейди в режим поддержания. Чек-ин ежедневно.',
    taskEn: 'Enter maintenance. Daily check-in.',
  },
  { day: 56,
    focusRu: '8 недель чисто. Курс пройден.',
    focusEn: '8 weeks clean. Course complete.',
    scienceRu: 'Это длина клинических курсов. Дальше — поддержка и редкие чек-ины.',
    scienceEn: 'Length of clinical courses. Now: maintenance.',
    taskRu: 'Поставь новую цель в копилке.',
    taskEn: 'Set new goal in jar.',
    practice: 'money',
  },
];

/* ============================================================
   L5 — Varenicline (Champix) 12 weeks. EAGLES NEJM 2016. Quit date = day 8.
============================================================ */
const L5_DAYS: TrackDay[] = [
  { day: 1,
    focusRu: 'Старт варениклина. Титрование.',
    focusEn: 'Varenicline start. Titration.',
    scienceRu: 'Самая эффективная монотерапия. RR 2.32 vs плацебо. 12 недель.',
    scienceEn: 'Most effective monotherapy. RR 2.32 vs placebo. 12 weeks.',
    taskRu: '0.5 мг 1 раз в день. После плотной еды + стакан воды.',
    taskEn: '0.5 mg once a day. After full meal + glass of water.',
    medRu: 'Дни 1–3: 0.5 мг × 1/день. Можно курить.',
    medEn: 'Days 1–3: 0.5 mg × 1/day. Smoking allowed.',
  },
  { day: 4,
    focusRu: 'Удвоение дозы.',
    focusEn: 'Dose doubled.',
    scienceRu: 'Постепенно повышаем чтобы избежать тошноты.',
    scienceEn: 'Gradual ramp to avoid nausea.',
    taskRu: '0.5 мг 2 раза в день.',
    taskEn: '0.5 mg twice a day.',
    medRu: 'Дни 4–7: 0.5 мг × 2/день. Можно курить.',
    medEn: 'Days 4–7: 0.5 mg × 2/day. Smoking allowed.',
  },
  { day: 8,
    focusRu: 'QUIT DATE. Полная доза, последняя сигарета.',
    focusEn: 'QUIT DATE. Full dose, last cigarette.',
    scienceRu: 'Препарат уже работает. Сигарета даёт ослабленный кайф — это и есть механизм.',
    scienceEn: 'Drug already working. Cigarette feels muted — that’s the mechanism.',
    taskRu: 'Сегодня — последняя сигарета. Перейди на 1 мг 2р/день.',
    taskEn: 'Last cigarette today. Switch to 1 mg twice daily.',
    medRu: 'С дня 8: 1 мг × 2/день, утром и вечером, после еды.',
    medEn: 'From day 8: 1 mg × 2/day, morning and evening, after meals.',
  },
  { day: 14,
    focusRu: '1 неделя без сигарет.',
    focusEn: '1 week smoke-free.',
    scienceRu: 'Если тошнит — принимай после плотной еды + вода. Странные сны — нормально.',
    scienceEn: 'Nausea? Take after full meal + water. Vivid dreams are normal.',
    taskRu: 'Чек-ин дня + дневник тяги.',
    taskEn: 'Daily check-in + craving journal.',
    practice: 'ema',
  },
  { day: 28,
    focusRu: 'Месяц без сигарет.',
    focusEn: '1 month smoke-free.',
    scienceRu: 'Лёгкие очищаются, кашель уходит. Препарат продолжаем.',
    scienceEn: 'Lungs clearing, cough fading. Continue med.',
    taskRu: 'Купи себе подарок из копилки.',
    taskEn: 'Buy a gift from the jar.',
    practice: 'money',
  },
  { day: 56,
    focusRu: '8 недель. Готовимся к финишу.',
    focusEn: '8 weeks. Approaching finish.',
    scienceRu: 'Курс ещё 4 недели. Не бросай раньше.',
    scienceEn: 'Course 4 more weeks. Don’t stop early.',
    taskRu: 'Сделай 3 новых if-then плана на жизнь после препарата.',
    taskEn: 'Make 3 new if-then plans for life after the med.',
    practice: 'if_then',
  },
  { day: 84,
    focusRu: 'Курс варениклина окончен.',
    focusEn: 'Varenicline course done.',
    scienceRu: 'Можно продлить ещё на 12 недель если есть риск срыва (Tonstad JAMA 2006).',
    scienceEn: 'Can extend 12 more weeks if relapse risk (Tonstad JAMA 2006).',
    taskRu: 'Решение о продлении — с врачом.',
    taskEn: 'Extension decision — with a clinician.',
  },
];

export const TRACKS: Record<StepLevel, Track> = {
  L1_behavioral: { stepId: 'L1_behavioral', totalDays: 28, hasMedication: false, days: L1_DAYS },
  L2_nrt_light: {
    stepId: 'L2_nrt_light', totalDays: 25, hasMedication: true,
    medAdherenceLabelRu: 'Принял Табекс по схеме', medAdherenceLabelEn: 'Took Tabex per schedule',
    days: L2_DAYS,
  },
  L3_nrt_combo: {
    stepId: 'L3_nrt_combo', totalDays: 56, hasMedication: true,
    medAdherenceLabelRu: 'Принял бупропион (по схеме)', medAdherenceLabelEn: 'Took bupropion (per schedule)',
    days: L3_DAYS,
  },
  L4_pharma: {
    stepId: 'L4_pharma', totalDays: 84, hasMedication: true,
    medAdherenceLabelRu: 'Принял варениклин (2 раза)', medAdherenceLabelEn: 'Took varenicline (twice)',
    days: L4_DAYS,
  },
  L5_intensive: {
    stepId: 'L5_intensive', totalDays: 168, hasMedication: true,
    medAdherenceLabelRu: 'Принял варениклин (2 раза)', medAdherenceLabelEn: 'Took varenicline (twice)',
    days: L5_DAYS,
  },
};

export function getTrack(stepId: StepLevel | undefined): Track {
  return TRACKS[stepId ?? 'L1_behavioral'];
}

// Find day content for the user's current day on this method.
export function trackDay(stepId: StepLevel | undefined, day: number): TrackDay {
  const tr = getTrack(stepId);
  const exact = tr.days.find((d) => d.day === day);
  if (exact) return exact;
  // Fallback: closest preceding day
  const prev = [...tr.days].reverse().find((d) => d.day < day);
  if (prev) return prev;
  // Generic synth
  return {
    day,
    focusRu: 'Удерживай курс.',
    focusEn: 'Hold the course.',
    scienceRu: 'Каждый день закрепляет новое поведение.',
    scienceEn: 'Every day wires the new behaviour deeper.',
    taskRu: 'Сделай чек-ин дня.',
    taskEn: 'Do today’s check-in.',
  };
}
